#+TITLE: Work, Energy, Power Notes
#+AUTHOR: Hankertrix
#+STARTUP: showeverything
#+OPTIONS: toc:2
#+LATEX_HEADER: \usepackage{siunitx}

* Definitions

** Work done by a constant force
Work done by a constant force is a scalar quantity that is equal to the force multiplied by the displacement in the direction of the force.
\[W = \vec{F} \cdot \vec{s}\]

** Work done by a variable force in 1D
The work done by a variable force is the *area* under the curve of the $F-x$ graph from the initial position $x_1$ to the final position $x_2$.
\[W = \int_{x_1}^{x_2} F_x \, dx\]

** Work done by a variable force in 2D & 3D
The work done by a variable force in 2D and 3D is given by a line integral:
\[W = \lim_{\Delta l_i \rightarrow 0} \sum F_i \cos \theta_i \Delta l_i = \int_a^b \vec{F} \cdot d \vec{l}\]

** Work-energy theorem
The work-energy theorem states that the work done by the *net force* on a particle equals the *change* in the particle's kinetic energy.
\[W = KE_{f} - KE_{i}\]
\[W = \frac{1}{2} mv_f^2 - \frac{1}{2}mv_i^2\]

** Kinetic energy
Kinetic energy is a form of energy that a body possesses due to its motion.
\[KE = \frac{1}{2}mv^2\]

Where $m$ is the mass of the object and $v$ is the velocity of the object.

** Conservative force
A force is *conservative* if the work done by the force on an object moving from one point to another *depends only on the initial and final positions* of the object, and is *independent of the particular path* taken.
\\

A force is *conservative* if the net work done around *any closed path* is *zero*.
\\

The work done between two points by any conservative force:
- can be expressed in terms of a *potential energy function*
- is *reversible*
- is *independent of the path* between the two points
- is *zero* if the starting and ending points are the *same*

** Non-conservative or dissipative force
A non-conservative or dissipative force is just a force that is not conservative. Examples of such forces include friction and air resistance.

** Gravitational potential energy
The *change* in gravitational potential energy of an object is the work done by an *external force in moving the object*.
\[\Delta U = W_{ext} = \int \vec{F}_{ext} \cdot d \vec{l}\]

Equivalently, the *change* in gravitational potential energy of an object is the *negative* of the *work done by the gravitational force*.
\[\Delta U = -W_{grav} = -\int \vec{F}_{grav} \cdot d \vec{l}\]

** Mechanical energy
Mechanical energy is defined as the *sum* of the *kinetic* and *potential* energy. If only conservative forces are doing work, the total mechanical energy of a system is constant.

** Principle of conservation of energy
The law of conservation of energy states that energy is *never created or destroyed*; it only changes form.
\\

Non-conservative forces do not store potential energy, but they do change the *internal energy* of a system.
\\

Hence, the law of conservation of energy can be expressed as:
\[\Delta K + \Delta U + \Delta U_{int} = 0\]

Or equivalently:
\[\Delta K + \Delta U + \text{ (change in all other forms of energy)} = 0\]

** Hooke's Law
Hooke's law states that the deformation of an elastic object is proportional to the stress applied to it, up to a limit.
\[\vec{F}_{spring} = - k \vec{x}\]

Where $k$ is the spring constant (the bigger the $k$, the stiffer the spring) and $\vec{x}$ is the extension from the unextended length.

** Power (SI Unit: \(\qty{1}{\unit{W}} = \qty{1}{\unit{J.s^{-1}}} = \qty{1}{\unit{kg.m^2.s^{-3}}}\))
Power is the *rate* at which work is done.

** Average power
Average power is the work done during the time interval divided by the duration of the time interval:
\[P_{av} = \frac{\Delta W}{\Delta t}\]

** Instantaneous Power
Instantaneous power is the average power over an infinitesimally short time interval, or the *gradient* of the *work done versus time* graph.
\[P = \lim_{\Delta t \rightarrow 0} \frac{\Delta W}{\Delta t} = \frac{dW}{dt}\]

** Mechanical Power
Mechanical power is the force acting on the particle multiplied by the velocity of the particle, and it is a form of instantaneous power.
\[P = \vec{F} \cdot \vec{v}\]

* Formulas

** Potential energy
\[\Delta U = - \int \vec{F} \cdot d \vec{l}\]

** Gravitational potential energy
\[GPE = mgh\]
\[U_{g} = mgh\]

Where $m$ is the mass of the object, $g$ is the acceleration due to gravity and $h$ is the height of the object.

** Elastic potential energy
\[EPE = \frac{1}{2}kx^2\]
\[U_{el} = \frac{1}{2}kx^2\]

Where $k$ is the spring constant and $x$ is the extension or compression of the spring.

*** Derivation
\begin{align*}
U_{el} &= - \int_0^x \vec{F}_{spring} \cdot d \vec{x} \\
&= \int_0^x kx \, dx \ \ (\because d \vec{x} \equiv \hat{x} \, dx ) \\
&= \frac{1}{2}kx^2
\end{align*}


* Force and potential energy in 1D
\[F_x(x) = - \frac{dU(x)}{dx}\]

Which means that the *force from potential energy* in *one-dimensional* motion (the value of a conservative force at point $x$) is the *negative of the derivative* at $x$ of the associated potential-energy functions.

Implications:
- In regions where $U(x)$ changes most rapidly with $x$, this corresponds to a large force.
- When $F_x(x)$ is in the positive \(x\)-direction, $U(x)$ decreases with increasing $x$.
- A conservative force always acts to push the system towards lower potential energy.

\newpage

* Force and potential energy in 3D
\[F_x = -\frac{\partial U}{\partial x} \quad F_y = -\frac{\partial U}{\partial y} \quad F_z = -\frac{\partial U}{\partial z}\]

In *three-dimensional* motion, the value at a given point of each component of a conservative force is the *negative* of the *partial derivative* at that point of the associated potential-energy function.
\\

When we take the partial derivative of $U$ with respect to each coordinate and multiply them by the corresponding unit vector, and then take the vector sum, this is called the *gradient* of $U$, which is a *vector* quantity.
\[\vec{F} = - \left( \frac{\partial U}{\partial x} \hat{i} + \frac{\partial U}{\partial y} \hat{j} + \frac{\partial U}{\partial z} \hat{k} \right) = - \vec{\boldsymbol{\nabla}} U\]

This means that the *vector value* of a *conservative force* at a given point is the *negative of the gradient* at that point of the associated potential-energy function.
\\

** The del operator (not very important)
The del operator is defined in Cartesian coordinates as:
\[\nabla \equiv \hat{x} \frac{\partial}{\partial x} + \hat{y} \frac{\partial}{\partial y} + \hat{z} \frac{\partial}{\partial z}\]

The del operator needs a function on the right to operate on, so it is meaningless when written on its own.
\\

A point in 3D in the spherical coordinate system is specified by \((r, \theta, \phi)\). The unit vectors \(\hat{r}, \hat{\theta}, \hat{\phi}\) move with the point.
\\

In a curvilinear coordinate system, such as the spherical coordinate system above, the del operator can be derived via a coordinate transformation to be:
\[\nabla \equiv \hat{r} \frac{\partial}{\partial r} + \hat{\theta} \frac{1}{r} \frac{\partial}{\partial \theta} + \hat{\phi} \frac{1}{r \sin \theta} \frac{\partial}{\partial \phi}\]

This is useful for systems with spherical symmetry, such as gravitational forces on a planetary scale.

* Derivations (not very important)

** Derivation of the work done by a variable force in 2D & 3D
Consider a variable force applied to a particle, which moves in 2D space from point $a$ to point $b$. The path can be divided into small intervals (\(\Delta l_i\)) such that in each short interval, the force acting on the particle during each $\Delta l_i$ is approximately constant.
\\

For each finite interval, the force does an amount of work:
\[\Delta W \approx \sum F_1 \cos \theta_1 \Delta l_1 \]

The work done over all the finite intervals from $a$ to $b$ is:
\[W \approx \sum F_i \cos \theta_i \Delta l_i\]

In the limit of infinitesimally short intervals, the force during each interval is constant. The work done by the force is then given by:
\[W = \lim_{\Delta l_i \rightarrow 0} \sum F_i \cos \theta_i \Delta l_i = \int_a^b \vec{F} \cdot d \vec{l}\]

\newpage

** Derivation of the work-energy theorem
Consider a net force $F$ on a particle moving from point $a$ to point $b$. The net work done by the force is given by:
\[W_{net} = \int \vec{F}_{net} \cdot d \vec{l} = \int F_{net} \cos \theta \, dl = \int F_{||} \, dl\]

The subscript || represents the component of the force parallel to each infinitesimally small displacement.
\\

Since \(F = ma\):
\[F_{||} = ma_{||} = m \frac{dv_{||}}{dt} = m \frac{dv}{dt}\]

The subscript || represents the component tangent to the curve.
\\

Because the particle is moving along the curve, the velocity has only a component tangent to the curve, $\vec{v} = \vec{v}_{||}$, hence $\frac{dv_{||}}{dt} = \frac{dv}{dt}$.
\\

Therefore, the work done by $F$ is:
\begin{align*}
W_{net} &= \int_i^f F_{||} \, dl \\
&= \int_i^f m \frac{dv}{dt} \, dl \\
&= \int_i^f m \frac{dv}{dl} \frac{dl}{dt} \, dl \text{ (using chain rule)} \\
&= \int_i^f mv \frac{dv}{dl} \, dl \\
&= \int_i^f mv \, dv \\
&= \frac{1}{2}mv_f^2 - \frac{1}{2}mv_i^2
\end{align*}

\newpage

** Derivation of gravitational potential energy
Consider a system comprising the Earth and an object of mass $m$. The object is lifted vertically by a displacement $\vec{s}$. In order for this to happen, an external force needs to be applied by an agent that does not belong the system of Earth and the object.
\\

This external force needs to be equal and opposite to the weight of the object:
\[\vec{F}_{ext} = -m \vec{g}\]

The work done by the external force is given by:
\begin{align*}
W_{ext} &= \int_{y_1}^{y_2} \vec{F}_{ext} \cdot d \vec{y} \\
&= \int_{y_1}^{y_2} mg \hat{y} \cdot \hat{y} \, dy \\
&= \int_{y_1}^{y_2} mg \, dy \\
&= mg(y_2 - y_1)
\end{align*}

Once at this new height, this work or energy input can be recovered, and the object has the ability to do work. We can say that the work done in lifting the object has been stored as gravitational potential energy.
