#+TITLE: Physics Electric Fields Cheat Sheet
#+AUTHOR: Hankertrix
#+STARTUP: showeverything
#+OPTIONS: toc:2
#+LATEX_HEADER: \usepackage{siunitx, graphicx}
#+LATEX_HEADER: \graphicspath{ {./images/} }

\newpage

* Definitions

** Principle of charge conservation
The principle of charge conservation states that the algebraic sum of all the electric charges in any closed system is constant.

** Coulomb's law
Coulomb's law states that the force between two *point charges* is given by:
\[F = \frac{1}{4 \pi \varepsilon_0} \frac{q_1 q_2}{r^2}\]

Where:
- $\varepsilon_0$ is the permittivity of vacuum, with a value of approximately \(\\ 8.85 \times 10^{-12} \ \unit{F.m^{-1}}\).
- \(q_1\) is the charge of the first point charge.
- \(q_2\) is the charge of the second point charge.

If the charges reside within a medium which contains atoms and molecules, like air, then the interaction of the medium with the charge will cause the effective force to be *reduced* by a factor \(\varepsilon_r = \frac{\varepsilon_{media}}{\varepsilon_0}\), which is called the relative permittivity of the medium. It is given by the ratio of the (absolute) permittivity of the medium to the vacuum permittivity of the medium to the vacuum permittivity, i.e. the force becomes:
\[F = \frac{1}{4 \pi \varepsilon_r \varepsilon_0} \frac{q_1 q_2}{r^2}\]

\newpage

** Principle of linear superposition
The principle of linear superposition states that every charge in space creates an electric field at point $\boldsymbol{r}$ independent of the presence of other charges in that medium. The resultant electric field is a vector sum of the electric field due to individual charges.

*** Discrete charge distribution
\begin{align*}
\vec{E}_{net} (\vec{r}) &= \sum_{i} \vec{E}_{i} (\vec{r}) \\
&= \sum_{i} \frac{q_i}{4 \pi \varepsilon_0 |\vec{r} - \vec{r}_i|^2}
\end{align*}

*** Continuous charge distribution
\begin{align*}
\vec{E}_{net} (\vec{r}) &= \int \, d \vec{E} (\vec{r}) \\
&= \int \frac{1}{4 \pi \varepsilon_0 |\vec{r} - \vec{r}_i|^2} \, dq \\
&= \int \frac{\rho (\vec{r'})}{4 \pi \varepsilon_0 |\vec{r} - \vec{r}_i|^2} \, dV \\
\end{align*}

\newpage

** Electric dipole
An electric dipole is an arrangement of two point charges, separated by a distance \(d\).
\\

Even though an electric dipole is electrically neutral, it interacts with an external electric field. An electric dipole *experiences torque in a uniform electric field*.
\[\vec{\tau} = \vec{p} \times \vec{E} \]

Where:
- $\vec{\tau}$ is the torque vector on an electric dipole
- $\vec{p}$ is the electric dipole moment
- $\vec{E}$ is the electric field

This torque causes the dipole to undergo rotation or angular displacement, which means that there is work done by the electric field on the dipole.
\\

A net force can only experienced by a dipole placed in a *non-uniform* electric field.

** Dipole moment (SI Unit: \(\unit{C.m}\))
The dipole moment, $p$ is a *vector* which points from the *negative to the positive* point charge.
\[p = qd\]

** Electric potential
Electric potential is defined as the potential energy per unit charge.
\[V = \frac{U}{q}\]

Where:
- $V$ is the electric potential
- $U$ is the electric potential energy
- $q$ is the electric charge

Electric potential is also the *negative* of the integral of the electric field:
\[V = - \int \vec{E} \, d \vec{r}\]

*** Single point charge
\[V = \frac{1}{4 \pi \varepsilon_0} \frac{q}{r}\]

Where:
- $V$ is the electric potential due to a point charge
- $\varepsilon_0$ is the permittivity of vacuum
- $q$ is the value of the point charge
- $r$ is the distance from the point charge to where the potential is measured

*** Collection of point charges
\[V = \frac{1}{4 \pi \varepsilon_0} \sum_i \frac{q_i}{r_i}\]

Where:
- $V$ is the electric potential due to a collection of point charges
- $\varepsilon_0$ is the permittivity of vacuum
- $q$ is the value of the $i^{th}$ point charge
- $r_i$ is the distance from the $i^{th}$ point charge to where the potential is measured

*** Relationship with electric field
Moving *with the direction of the electric field* means moving in the direction of *decreasing* potential and vice versa.

\newpage

** Potential difference
The potential difference between two points is equal to the work done per unit charge by an external force in moving a test charge from one point to another.
\[V_{ba} = V_{b} - V_{a}\]

Where:
- $a$ and $b$ are two points in space
- $V$ is the electric potential
- $V_{ba}$ is the potential difference between points $a$ and $b$

*** In terms of electric field
\[V_{ba} = - \int_a^b \vec{E} \cdot d \vec{l}\]

Where:
- $a$ and $b$ are two points in space
- $V_{ba}$ is the potential difference between points $a$ and $b$
- $\vec{E}$ is the electric field vector
- $d \vec{l}$ is the distance between points $a$ and $b$

** Equipotential surfaces
An equipotential surface is a surface on which the electric potential is the same at every point. Field lines and equipotential surfaces are always perpendicular to each other.

\newpage

* Formulas

** Electric field of a point charge (SI Unit: \(\unit{N.C^{-1}} \text{ or } \unit{V.m^{-1}}\))

\[\vec{E} = \frac{1}{4 \pi \varepsilon_0} \frac{q}{r^2} \hat{r}\]

Where:
- $\vec{E}$ is the electric field due to a point charge.
- $\varepsilon_0$ is the permittivity of vacuum, with a value of approximately \(\\ 8.85 \times 10^{-12} \ \unit{F.m^{-1}}\).
- $q$ is the magnitude of the point charge.
- $r$ is the distance from the point charge to where the field is measured.
- $\hat{r}$ is the unit vector from the point charge towards where the field is measured.

** Electric field of a ring of charge
\[E = \frac{Q}{4 \pi \varepsilon_0} \frac{x}{(r^2 + x^2)^{\frac{3}{2}}}\]

Where:
- $E$ is the magnitude of the electric field
- $Q$ is the total charge of the ring
- $\varepsilon_0$ is the permittivity of vacuum
- $r$ is the radius of the ring of charge
- $x$ is the distance away from the ring of charge

\newpage

** Electric field of a cylinder
\[E = \frac{\lambda}{2 \pi \varepsilon_0 r}\]

Where:
- $E$ is the magnitude of the electric field
- $\lambda$ is the charge per unit length
- $\varepsilon_0$ is the permittivity of vacuum
- $r$ is the radius of the cylinder

** Electric field of a long line of charge
\[E = \frac{1}{2 \pi \varepsilon_0} \frac{\lambda}{x}\]

Where:
- $E$ is the magnitude of the electric field
- $\varepsilon_0$ is the permittivity of vacuum
- $\lambda$ is the charge per unit length ($\unit{C.m^{-1}}$)
- $x$ is the distance from the long line of charge

** Electric field of an infinite thin plane of charge
\[E = \frac{\sigma}{2 \varepsilon_0}\]

Where:
- $E$ is the magnitude of the electric field
- $\varepsilon_0$ is the permittivity of vacuum
- $\sigma$ is the uniform surface charge density ($\unit{C.m^{-2}}$)

If there are 2 planes in the same direction, multiply the electric field by 2, i.e.
\[E = \frac{\sigma}{\varepsilon_0}\]

** Electric field at the surface of a conductor
\[E_{\perp} = \frac{\sigma}{\varepsilon_0}\]

Where:
- $E_{\perp}$ is the electric field at the surface of a conductor, which is also the $\vec{E}$ perpendicular to the surface
- $\sigma$ is the surface charge density
- $\varepsilon_0$ is the permittivity of vacuum

This formula is very similar to the electric field for an infinite thin plane of charge, except that the electric field extends out from only *one side* and is *zero on the other side*. Thus, there is a difference by a factor of 2.

** Electric field in terms of electric potential
Each electric field component is equal to the *negative* of the corresponding partial derivative of the electric potential function $V$.
\[\vec{E} = - \hat{x} \frac{\partial V}{\partial x} - \hat{y} \frac{\partial V}{\partial y} - \hat{z} \frac{\partial V}{\partial z} \equiv - \nabla V\]

\[E_x = - \frac{\partial V}{\partial x} \qquad E_y = - \frac{\partial V}{\partial y} \qquad E_z = - \frac{\partial V}{\partial z}\]

Where:
- $E$ is the electric field components found from potential

In 2 dimensions, electric field is the *negative* of the differential of the electric potential:
\[E = -\frac{dV}{dr}\]

*** Electric field between 2 uniformly charged plates
\[E = \frac{V}{d}\]

Where:
- $E$ is the magnitude of the electric field
- $V$ is the potential difference between the two plates
- $d$ is the separation between the two plates

\newpage

** Electric flux (SI Unit: \(\unit{N.m^2.C^{-1}}\))
\begin{align*}
\Phi_E &= \int E \cos \phi \, dA \\
&= \int E_{\perp} \, dA \\
&= \int \vec{E} \cdot d \vec{A}
\end{align*}

Where:
- $\Phi_E$ is the electric flux through a surface
- $E$ is the magnitude of the electric field
- $\phi$ is the angle between the electric field and the *normal to the surface*
- $dA$ is the element of surface area
- $E_{\perp}$ is the component of $\vec{E}$ perpendicular to the surface
- $d \vec{A}$ is the vector element of the surface area

** Gauss' law
\begin{align*}
\Phi_E &= \oint \vec{E} \cdot d \vec{A} \\
&= \frac{Q_{encl}}{\varepsilon_0}
\end{align*}

Where:
- $\Phi_E$ is the electric flux through a closed surface of area $A$. It is equal to the surface integral of $\vec{E}$.
- $Q_{encl}$ is the total charge enclosed by the surface
- $\varepsilon_0$ is the permittivity of vacuum

** Electric potential energy of 2 point charges
\[U = \frac{1}{4 \pi \varepsilon_0} \frac{qq_0}{r}\]

Where:
- $U$ is the electric potential energy of two point charges
- $\varepsilon_0$ is the permittivity of vacuum
- $q$ and $q_0$ is the value of the two charges
- $r$ is the distance between the two charges

** Electric potential energy of a system of discrete charges
\[U = \frac{1}{2} \sum_{i} \sum_{j \ne i} \frac{q_i q_j}{4 \pi \varepsilon_0 r_{ij}}\]

Where:
- $U$ is the electric potential energy of two point charges
- $\varepsilon_0$ is the permittivity of vacuum
- $q_i$ and $q_j$ is the value of the $i^{th}$ and $j^{th}$ charges
- $r$ is the distance between the $i^{th}$ and $j^{th}$ charges

We will have to consider *all pairwise interactions* for a system of discrete charges. The factor of $\frac{1}{2}$ takes double counting into consideration.

\newpage

** Electric potential energy of a dipole's orientation in an electric field
\begin{align*}
U &= - p E \cos \theta \\
&= - \vec{p} \cdot \vec{E}
\end{align*}

Where:
- $U$ is the electric potential energy the dipole
- $\vec{p}$ is the electric dipole moment
- $p$ is the magnitude of the electric dipole moment
- $\vec{E}$ is the electric field
- $E$ is the magnitude of the electric field
- $\theta$ is the angle between the electric field and the dipole

\newpage

* Electric fields in conductors
In conductors, there is:
- Zero electric field within the conductor
- Zero tangential component of the electric field on the surface of the conductor

A charge inside a neutral spherical metal shell induces charge on its surfaces. The electric field exists even beyond the shell, but *not* within the conductor itself.
\[\includegraphics[scale = 0.65]{charge-inside-conductor}\]

For a conductor that *isn't moving*, the electric field parallel to the conductor *must be zero*, otherwise the conductor will *no longer be static*.
\\

When all charges are at rest, the surface of a conductor is always an equipotential surface. The *electric field* just outside a conductor is always *perpendicular* to the surface.


* Summary of relationships
\[\includegraphics[width = \textwidth]{summary-of-relationships}\]
