[build]
target = "avr-specs/avr-atmega2560.json"
rustflags = ["-C", "link-arg=-Wl,--allow-multiple-definition"]

[target.'cfg(target_arch = "avr")']
runner = "ravedude mega2560 -cb 9600"

[unstable]
build-std = ["core"]
