#+TITLE: Math Module 1A Tutorial
#+AUTHOR: Hankertrix
#+STARTUP: showeverything
#+OPTIONS: toc:2
#+LATEX_HEADER: \usepackage{tikz, pgfplots, xcolor}

\newpage

* Question 1

** (a)

\begin{align*}
|A| &= 5 \\
|B| &= 4 \\
|A \cup B| &= 7 \\
|A \cap B| &= 2
\end{align*}


** (b)

\[|A \cup B| = |A| + |B| - |A \cap B|\]


** (c)

Let the set of $1^{st}$ year students registered at CNYSP be $A$, and the set of students registered at SPMS be $B$.

\[|A| = 50\]
\[|B| = 1102\]
\[|A \cup B| = 1138\]

The number of $1^{st}$ year students registered at SPMS and CNYSP together will be $|A \cap B|$. From (b):

\[|A \cup B| = |A| + |B| - |A \cap B| \]
\[|A \cap B| = |A| + |B| - |A \cup B| \]
\[|A \cap B| = 50 + 1102 - 1138 \]
\[|A \cap B| = 14\]

Hence, there are 14 $1^{st}$ year CNYSP students who also registered at SPMS.


** (d)

\[|A \cup B \cup C| = |A| + |B| + |C| - |A \cap B| - |A \cap C| - |B \cap C| + |A \cap B \cap C| \]


* Question 2

\[|A \times B| = |A| \times |B|\]


* Question 3

** (a)

\[A = \{0\}\]
\[\mathcal{P}(A) = \{ \emptyset, \{0\} \}\]
\[\mathcal{P}(\mathcal{P}(A)) = \{ \emptyset, \{\emptyset\}, \{ \{0\} \}, \{ \emptyset, \{0\} \} \}\]


** (b)

\[2^n = 2^{|A|}\]


* Question 4

** (a)

\[not \text{ } (P \text{ or } Q) \Leftrightarrow (not \text{ } P) \text{ and } (not \text{ } Q)\]
\[not \text{ } (P \text{ and } Q) \Leftrightarrow (not \text{ } P) \text{ or } (not \text{ } Q)\]


** (b)

\begin{align*}
P \Rightarrow Q &\Leftrightarrow not \text{ } (P \text{ and } (not \text{ } Q)) \\
&\Leftrightarrow (not \text{ } P) \text{ or } (not \text{ } (not \text{ } Q)) \\
&\Leftrightarrow (not \text{ } P) \text{ or } Q
\end{align*}


** (c)

\[P \text{ and } Q \text{ or } ((not \text{ } P) \text{ and } (not \text{ } Q))\]

\newpage

* Question 5

** (a)

\[(A \cup B)^c = (A^c \cap B^c)\]

** (b)

\[(A \cap B)^c = (A^c \cup B^c)\]


* Question 6

** (a)

For $f(x) \in \mathbb{R}$, \(\sqrt(3x - x^3)\) must be real. Hence:

\[3x - x^3 \ge 0 \]
\[x(3 - x^2) \ge 0 \]
\[x(3 - x^2) \ge 0 \]
\[x(x^2 - 3) \le 0 \]
\[x(x + \sqrt{3})(x - \sqrt{3}) \le 0\]

\begin{center}
\begin{tikzpicture}
\begin{axis}[axis lines = middle, ymin = -10, ymax = 10]
\addplot[domain = -3:3, color = blue]{x * (x + sqrt(3)) * (x - sqrt(3))};
\end{axis}
\end{tikzpicture}
\end{center}

\[\text{Thus, the domain of } f(x) \text{ is } (-\infty, -\sqrt{3}] \cup [0, \sqrt{3}].\]


** (b)

For $f(x) \in \mathbb{R}$, \(\sqrt{\frac{1 + x}{1 - x}}\) must be real. Hence:

\[\frac{1 + x}{1 - x} \ge 0 \]
\[(1 + x)(1 - x) \ge 0, \text{ }(1 - x) \neq 0\]

\begin{center}
\begin{tikzpicture}
\begin{axis}[axis lines = middle, ymin = -5, ymax = 5]
\addplot[domain = -3:3, color = blue]{(1 + x) * (1 - x)};
\end{axis}
\end{tikzpicture}
\end{center}

Thus, the domain of $f(x)$ is $[-1, 1)$.

\newpage


* Question 7

** (a)

For $f(x) \in \mathbb{R}$, \(\sqrt{2 + x - x^2}\) must be real. Hence:

\[2 + x - x^2 \ge 0\]
\[x^2 - x - 2 \le 0\]
\[(x - 2)(x + 1) \le 0\]

\begin{center}
\begin{tikzpicture}
\begin{axis}[axis lines = middle, ymin = -5, ymax = 5]
\addplot[domain = -3:3, color = blue]{(x - 2) * (x + 1)};
\end{axis}
\end{tikzpicture}
\end{center}

\[\text{Hence, the domain of } f(x) \text{ is } [-1, 2].\]

\newpage

Plotting the graph for $f(x)$ for \(x \in [-2, 1]\):

\begin{center}
\begin{tikzpicture}
\begin{axis}[axis lines = middle, ymin = -2, ymax = 2]
\addplot[domain = -2:1, color = blue]{sqrt(2 + x - x^2)};
\end{axis}
\end{tikzpicture}
\end{center}

\[\text{The range of } f(x) \text{ is } \left[0, \frac{3}{2}\right].\]

\newpage

** (b)

For $f(x) \in \mathbb{R}$, since $x^2 > 0$, $(1 + x)$ must be not be 0 for $f(x)$ to be real. Hence, the domain of $f(x)$ is $\mathbb{R} \setminus \{-1\}$.
\\

Plotting the graph for \(f(x), x \in \mathbb{R} \setminus \{-1\}\):

\begin{center}
\begin{tikzpicture}
\begin{axis}[axis lines = middle, ymin = -10, ymax = 10, samples = 100]
\addplot[domain = -10:10, color = blue]{(x^2) / (1 + x)};
\end{axis}
\end{tikzpicture}
\end{center}

\[\text{Hence, the range of } f(x) \text{ is } (-\infty, -4] \cup [0, \infty].\]


* Question 8

** (a)

For \(f : \mathbb{R} \rightarrow \mathbb{R}\) to be both increasing and decreasing at the same time, it must satisfy the two conditions below:

\[\text{1. } x_1, x_2 \in A, x_1 < x_2 \Rightarrow f(x_1) \le f(x_2)\]
\[\text{2. } x_1, x_2 \in A, x_1 < x_2 \Rightarrow f(x_1) \ge f(x_2)\]

For $f$ to satisfy the conditions \(f(x_1) \le f(x_2) \text{ and } f(x_1) \ge f(x_2)\), $f(x_1)$ must be equal to $f(x_2)$. Thus, $f$ is constant.

\newpage


** (b)

For \(f : \mathbb{R} \rightarrow \mathbb{R}\) to be even and odd at the same time, it must satisfy the two conditions below:

\[\text{1. } x \in A \Rightarrow -x \in A \text{ and } f(-x) = -f(x).\]
\[\text{2. } x \in A \Rightarrow -x \in A \text{ and } f(-x) = f(x).\]
\[\text{Hence, } f(-x) = -f(x) = f(x)\]

The only number that satisfies this condition is 0, thus $f(x) = 0$ for all $x \in \mathbb{R}$.


* Question 9

** (a)

For a function to be even, \(f(-x) = f(x)\):

\begin{align*}
E(-x) &= \frac{1}{2}(f(-x) + f(x)) \\
&= \frac{1}{2}(f(x) + f(-x)) \\
&= E(x)
\end{align*}

Hence, $E(x)$ is even.
\\

For a function to be odd, \(f(-x) = -f(x)\):

\begin{align*}
O(-x) &= \frac{1}{2}(f(-x) - f(x)) \\
&= -\frac{1}{2}(f(x) - f(-x)) \\
&= -O(x)
\end{align*}

Hence, $O(x)$ is odd.


** (b)

\[E(x) + O(x) = \frac{1}{2}(f(x) + f(-x)) + \frac{1}{2}(f(x) - f(-x))\]
\[E(x) + O(x) = \frac{1}{2}(f(x) + f(-x) + f(x) - f(-x))\]
\[E(x) + O(x) = \frac{1}{2}(2f(x))\]
\[E(x) + O(x) = f(x) \rightarrow \text{ Proven }\]

\newpage


** (c)

Suppose \(f(x) = e(x) + o(x)\) where $e(x)$ is even and $o(x)$ is odd.

\[f(-x) = e(-x) + o(-x)\]

Since \(e(-x) = e(x)\) as $e(x)$ is even and \(o(-x) = -o(x)\) as $o(x)$ is odd:

\begin{equation}
f(-x) = e(x) - o(x)
\end{equation}

\begin{equation}
f(x) = e(x) + o(x)
\end{equation}

Solving for $(2) - (1)$:

\[f(-x) - f(x) = e(x) - o(x) - (e(x) + o(x))\]
\[f(-x) - f(x) = - 2o(x)\]
\[2o(x) = - f(-x) + f(x)\]
\begin{align}
o(x) &= \frac{1}{2}(f(x) - f(-x)) \\
&= O(x) \nonumber
\end{align}

Substituting $(3)$ into $(2)$:

\[f(x) = e(x) + \frac{1}{2}(f(x) - f(-x))\]
\[e(x) = f(x) - \frac{1}{2}(f(x) - f(-x))\]
\begin{align*}
e(x) &= \frac{1}{2}(f(x) + f(-x)) \\
&= E(x)
\end{align*}

Since $e(x) = E(x)$ and $o(x) = O(x)$, there is no other way to write $f(x)$ as a sum of odd and even functions.

* Question 10

** (a)

$\indent$ Recurrent formula:

\[v(n) = a_0 = 1, a_1 = 2, a_n = 2a_{n-1}\]
\\

Explicit formula:

\[v(n) = 2^n\]


** (b)

Let $b(n)$ be the number of humans that were bitten on night $n$.

\[b(1) = v(0) = 1\]
\begin{align*}
v(1) &= 1 + b(1) \\
&= 1 + v(0) \\
&= 1 + 1 \\
&= 2
\end{align*}

For \(n \ge 2\):

\[b(n) = v(n - 2)\]
\[v(n) = v(n - 1) + b(n)\]
\[v(n) = v(n - 1) + v(n - 2)\]

Recurrent formula:

\[v(n) = a_0 = 1, a_1 = 2, a_n = a_{n - 1} + a_{n - 2}\]

** Bonus

Proving the base cases:
\\

\begin{align*}
v(0) &= \frac{(\frac{1 + \sqrt{5}}{2})^{0+2} - (\frac{1 - \sqrt{5}}{2})^{0+2}}{\sqrt{5}} \\
&= 1
\end{align*}

\begin{align*}
v(1) &= \frac{(\frac{1 + \sqrt{5}}{2})^{1+2} - (\frac{1 - \sqrt{5}}{2})^{1+2}}{\sqrt{5}} \\
&= 2
\end{align*}

Let \(n \in \mathbb{Z}^+\):
\\

\[v(n) = \frac{(\frac{1 + \sqrt{5}}{2})^{n+2} - (\frac{1 - \sqrt{5}}{2})^{n+2}}{\sqrt{5}}\]
\[v(n - 1) = \frac{(\frac{1 + \sqrt{5}}{2})^{n+1} - (\frac{1 - \sqrt{5}}{2})^{n+1}}{\sqrt{5}}\]
\\

\begin{align*}
v(n) + v(n - 1) &= \frac{(\frac{1 + \sqrt{5}}{2})^{n+2} - (\frac{1 - \sqrt{5}}{2})^{n+2}}{\sqrt{5}} + \frac{(\frac{1 + \sqrt{5}}{2})^{n+1} - (\frac{1 - \sqrt{5}}{2})^{n+1}}{\sqrt{5}} \\
&= \frac{(\frac{1 + \sqrt{5}}{2})^{n+2} - (\frac{1 - \sqrt{5}}{2})^{n+2} + (\frac{1 + \sqrt{5}}{2})^{n+1} - (\frac{1 - \sqrt{5}}{2})^{n+1}}{\sqrt{5}} \\
&= \frac{(\frac{1 + \sqrt{5}}{2})^{n+1}(\frac{1 + \sqrt{5}}{2} + 1) + (\frac{1 - \sqrt{5}}{2})^{n+1}(-\frac{1 - \sqrt{5}}{2} - 1)}{\sqrt{5}} \\
&= \frac{(\frac{1 + \sqrt{5}}{2})^{n+1}(\frac{1 + \sqrt{5}}{2} + 1) - (\frac{1 - \sqrt{5}}{2})^{n+1}(\frac{1 + \sqrt{5}}{2} + 1)}{\sqrt{5}}
\end{align*}

Let \(a = \frac{1 + \sqrt{5}}{2}\) and \(b = \frac{1 - \sqrt{5}}{2}\):

\begin{equation}
v(n) + v(n - 1) = \frac{a^{n+1}(a + 1) - b^{n+1}(b + 1)}{\sqrt{5}} \tag{1}
\end{equation}

Getting the value of $a + 1$ and \(a^2\):

\begin{align*}
a + 1 &= \frac{1 + \sqrt{5}}{2} + 1 \\
&= \frac{3 + \sqrt{5}}{2}
\end{align*}

\begin{align*}
a^2 &= \left(\frac{1 + \sqrt{5}}{2}\right)^2 \\
&= \frac{1 + 2\sqrt{5} + 5}{4} \\
&= \frac{6 + 2\sqrt{5}}{4} \\
&= \frac{3 + \sqrt{5}}{2} \\
&= a + 1
\end{align*}

Hence,
\begin{equation}
a + 1 = a^2 \tag{2}
\end{equation}

\newpage

Getting the value of $b + 1$ and \(b^2\):

\begin{align*}
b + 1 &= \frac{1 - \sqrt{5}}{2} + 1 \\
&= \frac{3 - \sqrt{5}}{2}
\end{align*}

\begin{align*}
b^2 &= \left(\frac{1 - \sqrt{5}}{2}\right)^2 \\
&= \frac{1 - 2\sqrt{5} + 5}{4} \\
&= \frac{6 - 2\sqrt{5}}{4} \\
&= \frac{3 - \sqrt{5}}{2} \\
&= b + 1
\end{align*}

Hence,
\begin{equation}
b + 1 = b^2 \tag{3}
\end{equation}
\\

Substituting $(2)$ and $(3)$ into $(1)$:

\begin{align*}
v(n) + v(n - 1) &= \frac{a^{n+1}(a^2) - b^{b+1}(b^2)}{\sqrt{5}} \\
&= \frac{a^{n+3} - b^{n+3}}{\sqrt{5}} \\
&= \frac{(\frac{1 + \sqrt{5}}{2})^{n+3} - (\frac{1 - \sqrt{5}}{2})^{n+3}}{\sqrt{5}} \\
&= v(n + 1) \rightarrow \textbf{ Proven by induction}
\end{align*}

Thus,
\[v(n) = \frac{(\frac{1 + \sqrt{5}}{2})^{n+2} - (\frac{1 - \sqrt{5}}{2})^{n+2}}{\sqrt{5}}\]
