#+TITLE: Guide to Writing the +Ethics+ Philosophy Essay
#+AUTHOR: Hankertrix
#+STARTUP: showeverything
#+OPTIONS: toc:2

* A helpful reframe
First, do not think of the essay as an ethics essay. It is not a humanities essay that you can just smoke through and expect to get good grades. If you have been looking at the past ethics essays in the PMP folder, don't bother. Those essays probably won't help you, unless the essay was written when CY0002 Ethics is taught by Dr Melvin, then it may be helpful.

Why? Because, Dr Melvin is a philosophy professor, and philosophy is not like most humanities. He expects a philosophy essay, not just any old humanities essay. Philosophy, unlike most other humanities, is actually very technical and has a lot of rigour, like most sciences. There is room for subjectivity, but when it comes to writing arguments, everything is logical and objective. There is little to no room for subjectivity in your arguments. They all have to make sense.

Instead of thinking about the essay as a humanities essay, think of it as a philosophy essay, if you are familiar with one. Otherwise, think of it like writing a research paper. In your research paper, you have some point to prove, or some new discovery that you have made. That is your argument in a philosophy essay, the point to prove. The results section in your research paper is basically the evidence to prove your point. Same thing in a philosophy essay, you bring in evidence to prove your point, and explain how it proves your point. The discussion section in a research paper is where you discuss your results, talk about any caveats, flaws, or issues, and provide suggestions for future improvement or research. The same goes for a philosophy essay, you can point out certain issues in the argument, and then instead of suggesting improvements, you either concede the flaws, or bring in additional constraints and semantics to defend your point. The lecture slides have quite a few examples of arguments being defended after being attacked by a flaw, so you can try to use some of those ideas to defend your point.

* You have actually done this before!
What? Really? Yeap, if you have taken General Paper (GP) in the A-levels, then you have encountered these kinds of essays before. If you were one of those who wrote the philosophy question in GP, then you already know how to write this essay. If you did well in those essays, then just write this essay similarly, as it is almost the same, just that this essay is more rigorous, being a university-level philosophy essay instead of a GP essay.

* Structure of the essay
You probably already know the structure of these kinds of essays. It's the standard introduction, some number of body paragraphs, and then a conclusion.

** Introduction
The introduction is where a philosophy essay differs from a GP and a humanities essay. The introduction in a philosophy essay is usually just stating your position on the matter, and stating the premises and the assumptions that you are making in your argument. It usually also includes a few definitions that are important to your argument. For example, if your argument relates to something being "good", you would want to define what "good" is, and how something is considered "good". However, the essay we have to write is only 2000 words, so don't waste too many words on the introduction, and instead get straight to your arguments. I doubt there is a need to define anything in your introduction, as the questions are phrased in such a way that those definitions should go into your body paragraphs. There also isn't an overarching position to defend or attack, as the questions are all about evaluation, so it doesn't make any sense to take a stance in the introduction. In short, you can and should ignore the introduction and just go straight to the body paragraphs, which are where your arguments are.

** Body paragraphs
I think you should know the structure of the body paragraphs. It's the PEEL structure that is used in GP and humanities essays. I'm not sure if you were taught some other structure, but this is the structure I was taught for my humanities essays, so that's what I recommend. Feel free to use another structure if you prefer. @@latex: \\@@

The PEEL structure is as follows:
- Point
- Elaboration/Explanation
- Evidence/Examples
- Link

*** Point
The point you are trying to make. This is usually the first sentence of the body paragraph and usually isn't too long.

*** Elaboration/Explanation
Here lies the meat of your arguments. It is where you explain the reason for your argument, and why it makes sense. The important question to keep asking yourself when writing this section is "Why?". So after every sentence you write in this section, ask yourself, "Why?" after the sentence you just wrote. Then answer the "Why?" when writing the next sentence. Keep going until you hit something fundamental or foundational that can't really be explained further.

*** Evidence/Examples
Here is where you bring in real-world evidence and examples to illustrate your point and show that your elaboration and explanation make sense, and occur in the real world. Make sure your evidence and examples are related, otherwise, the examples are not doing anything for your argument, and you are just wasting words that can be spent on making other arguments or furthering your explanation.

*** Link
Here is where you link your elaboration and evidence back to your point. Usually, this is just one sentence, and usually starts with "hence" or "therefore". I don't like to think of this as a section on its own, as it doesn't really make much sense to me to have a link at the end, after you have given all of your explanations and evidence. Instead, this should be incorporated into your explanations and examples, by linking them to your point after you have finished writing them. The way to do so is to ask yourself, "So?" after the elaboration or example you have given, and then write the answer to that question as the link.

@@latex: \newpage@@

** Conclusion
The conclusion for a philosophy essay is quite similar to most essays. You just make a summary of your arguments, restate your points, and then end off. Once again, the ethics essay is only 2000 words, so don't waste too many words on the conclusion as well. The conclusion won't do much to help your grades. The important part is your points and arguments made in the body paragraphs, not the conclusion.

** Bonus
If you can point out the flaws in your arguments, usually because they don't apply in a specific circumstance, or break down under certain conditions, dedicate a body paragraph or two to doing so. If you can find a way to defend against those flaws, write them in the same body paragraph to score extra points. However, this is by no means easy to do, and you might have a higher chance of messing up because these situations or circumstances are usually not that simple to reason about, and are often really convoluted. If you start getting confused by the defence you are writing, stop and clarify everything with Dr Melvin or someone else before continuing. Otherwise, it is not going to make sense and that will end up pulling down your grades rather than improving them. If you can't clarify it or still don't understand, or the person you consulted said it doesn't make sense, then you either concede the flaws, come up with some other flaws to defend against, or just write another argument to support your point instead of trying to defend it against the flaw. This is a bonus because it isn't easy to write effectively, and it is very easy to mess up and fall for a fallacy when the reasoning is too complicated to wrap your head around.

@@latex: \newpage@@

* Assessment criteria
- Clarity and distinct originality of thought, with clear links to major topics of the primary readings.
- Compelling use of persuasive and effective arguments in every paragraph to support claims.
- Excellent use of language, with no grammatical errors.
- Consistent demonstration of close reading of primary readings and detailed and in-depth analysis of the relevant theoretical concepts.
- Ability to introduce, review and engage critically with secondary readings (where relevant).

@@latex: \newpage@@

** Meeting the criteria
- The first point about clarity, originality and links to the major topics should be easily met, since most of the essay questions refer to the primary readings in one way or another. You just need to understand what is being discussed in the lectures to fulfil the clarity requirement.
- The difficult part for most would probably be the second point, as coming up with good arguments isn't easy if you haven't had much practice. Try to talk out your points with someone else and see if your arguments make sense. Consult Dr Melvin for feedback, as he can very easily tell you if your arguments are good or not.
- The third point about the use of language and grammar is solved with [[https://www.grammarly.com/][Grammarly]] or [[https://languagetool.org/][LanguageTool]], so just use those tools and stop thinking so much about grammar. You probably can also use ChatGPT to fix your grammar, since it pretty much has perfect grammar. It is highly unlikely that this criterion carries a lot of weight, so you shouldn't think too much about it, and you shouldn't bother with flowery language. Remember that the bulk of your marks will come from how strong your arguments are. Making zero grammatical errors should suffice for this criterion.
- The fourth point shouldn't be too difficult to meet either, since you will likely have to go into the details and have depth in your arguments. If you are answering questions that make use of points from the lecture slides, this criterion is already met.
- The last point should be very easy to meet. It very likely doesn't only refer to the supplementary readings. You can look up philosophy papers or philosophy textbooks and bring in some of the points mentioned if they are relevant to your argument. I'm pretty sure providing real-world examples and evidence also counts under this criterion, so it is very easily met.
- This isn't part of the criteria, but you should consult Dr Melvin as often as possible to clarify your doubts and your understanding of the topics. You should also ask him for feedback often. The more you clarify and understand what you are writing, the better your grade will be, so just consult, consult and consult as much as possible. He can tell you immediately if something you said doesn't make sense, or is incoherent, since he has had years of experience with philosophy.

@@latex: \newpage@@

* Breaking down the given questions

** Question 1
The principle of deontic neutrality suggests that logical systems engaging with deontic concepts should not favour certain normative positions over others. Through a systematic formalisation of the normative statuses of actions, deontic logic functions as a useful tool for representing the nature of ethical reasoning and moral justification. At the same time, deontic logic presupposes certain normative constraints: the NC axiom (\(\neg(Op \wedge O \neg p)\)) presupposes a moral structure in which our moral obligations cannot conflict. The NC axiom is not merely a formal feature of logic: it excludes normative theories that accept moral dilemmas as genuine. Can you identify other examples in which metaethics might appear to be normative theory in disguise? Justify your response.

*** Requirements
1. Identify other examples that make metaethics appear to be normative theory in disguise. You will probably need 2 - 3 examples to fill up the 2000 words. There is one example of this in lecture 5, the difficulty of modelling deontological reasoning using standard decision theory (axioms of probability and the axioms of expected utility theory). The other examples may or may not be covered in the lectures, I'm not sure as of the time of writing, but it is quite likely that you will have to come up with the other examples yourself.
2. Justify your response.

*** Should you answer this question?
No, I don't think you should. I'm quite certain that the later lectures will not cover much regarding this question, which means you may have to come up with the examples yourself, look them up, or ask ChatGPT. I find it difficult to find anything sufficiently in-depth regarding philosophy using Google, and ChatGPT suffers from irrationality, just like humans, so I wouldn't trust it much either. If you decide to do this question, I suggest consulting Dr Melvin to see if the examples you come up with are viable examples.

** Question 2
The ethical decision problem consists of an agent having to select the morally appropriate action \(\phi_i\) from $n$ alternative courses of action, where \(i \in \mathbb{N}, i \in (0, n]\). Examples of action-guiding high-level moral theory include consequentialism, deontology, and virtue ethics. Provide an account of how the different normative camps (consequentialism, deontology, and virtue ethics) can be distinguished from one another and defend high moral theory against other approaches (for instance, mid-level theory, casuistry, narrative ethics, and so on).

*** Requirements
1. State how consequentialism, deontology and virtue ethics can be differentiated. This is just stating what these normative camps are and how they work, which can be found in the lecture slides, under lectures 5, 7 and 8 for consequentialism, and you can just Google for deontology and virtue ethics. I think deontology and virtue ethics will be covered in later lectures, but I'm not sure as of the time of writing. You can also find it in my cheat sheet.
2. Argue that high moral theory is better than other approaches to normative theory, like mid-level theory, casuistry, narrative ethics, and so on. This can be found in the lecture slides as well, under lecture 7. You can also find it in my cheat sheet.

*** Should you answer this question?
Yes, you should. This question isn't that difficult, since quite a lot of what it requires is already covered in the lectures, and you can just pull them and use them directly. Even if deontology and virtue ethics aren't covered in the later lectures, they are relatively easy to understand just from reading the Wikipedia page, which is really all you need to know to differentiate between consequentialism, deontology and virtue ethics.

@@latex: \newpage@@

** Question 3
Machine ethics is broadly concerned with ensuring that the behaviour of machines is ethically acceptable. For instance, how can we give machines ethical principles or decision procedures for discovering ways of resolving the ethical dilemmas they might encounter? Jeremy and W.D. are examples of machine-based implementations of (respectively) the hedonic calculus of Benthamite utilitarianism and Rossian deontology. Critically assess the nature, scope, prospects, and limits of machine-based implementations of normative theory, making reference to Jeremy, W.D., or related machine-based implementations if necessary.

*** Requirements
1. Assess the nature, scope, prospects and limits of machine-based implementations of normative theory.
2. Make references to those machine-based implementations if necessary. Jeremy is in lecture 7. I'm not sure which lecture will W.D. appear, but hopefully, it does appear.

*** Should you answer this question?
Yes, you should. I'm assuming that W.D. will be covered in the later lectures, because it wouldn't make much sense to include that and Rossian deontology when we haven't learnt about it. Either way, regardless of W.D. and Rossian deontology being covered, this question is probably the least philosophical question out of all the given questions. This is essentially just a literature review on machine ethics. The rigour required in this question is probably far less than that required of the other questions, since there are no proper philosophical arguments you have to make. You just need to talk about what machine ethics is, what it does, what it excels at, what the possible use cases are in the present and the future, and its limits and flaws. Nothing super philosophical, and very much like a literature review. Just make sure what you are writing makes sense, which should be a given if you treat the answer to this question like a literature review.

@@latex: \newpage@@

** Question 4
According to the classical version of the trolley problem, a runaway trolley is hurtling unimpeded down the track and about to hit and kill five people. You have access to a lever that could switch the trolley to a different track, although a sixth innocent person will meet an untimely demise as a result of your pulling the lever. Should you pull the lever (\(\phi\)), killing one to save five, or refrain from doing so (\(\neg \phi\))? Researchers at the MIT Media Lab designed an experiment called Moral Machine, with the aim of crowdsourcing people’s decisions on how self-driving cars should prioritize lives in different variations of this trolley problem (for instance, whether self-driving cars should prioritize humans over pets, passengers over pedestrians, women over men, young over the elderly, and so on). Cultural differences in moral preferences were discovered: collectivist cultures are more likely to favour the elderly over the young, participants from poorer countries with weaker institutions are more tolerant of jaywalkers, and so on. What might consequentialism and deontology recommend in the case of the classical version of the trolley problem (\(\phi\) or \(\neg \phi\)) and can normative theory make room for cultural differences in moral preferences?

*** Requirements
1. State what consequentialism recommends in the trolley problem. This should be obvious, using the axioms of expected utility theory and standard decision theory from lecture 4 tells you that you should pull the lever (\(\phi\)) and kill 1 to save 5. Consequentialism is very easily modelled using standard decision theory, so you just have to put it in consequentialist terms, i.e. saving 5 people instead of 1 person is a better outcome because 5 people because we want to maximise the "good", then state what "good" is and why saving more people is more "good" or "better". All these are found in lectures 7 and 8.
2. State what deontology recommends in the trolley problem. This will hopefully be covered in the later lectures, otherwise, it would be quite difficult to write.
3. Talk about the possibility of normative theory (consequentialism, deontology and virtue ethics) making room for cultural differences in moral preferences.

@@latex: \newpage@@

*** Should you answer this question?
Yes, you should. I'm assuming that the part about what deontology recommends in the trolley problem is going to be covered in the later lectures. If that isn't covered, then this question is going to be more difficult, but I am pretty sure that it will be covered. As for whether normative theory can make room for cultural differences, the answer is most likely going to be yes. I think that would be the rational answer, considering that some of the modern versions of these normative theories nowadays are far more complicated and are attempting to fix all the flaws and issues with the standard versions of these normative theories. I reckon that they would have made room for differences in moral preferences already. You should consult Dr Melvin if nothing about it is covered during the lectures, but this question is still doable, though it is probably one of the more difficult ones compared to the other doable questions.

@@latex: \newpage@@

** Question 5
The mainstream approaches to normative theory that we have covered in the second half of the semester include consequentialism, deontology, and virtue ethics. Provide an account of a non-mainstream position in normative theory and offer a critical evaluation of this position with respect to at least one of the mainstream approaches to normative theory.

*** Requirements
1. State a non-mainstream normative theory, i.e. not consequentialism, deontology or virtue ethics, and explain how it works, as well as its flaws. Most of the non-mainstream normative theories are those that are lower level than the mainstream normative theories, which are considered high moral theories. So, non-mainstream normative theories include mid-level theories, casuistry or case-based reasoning, and narrative ethics.
2. Compare the normative theory you have picked to either consequentialism, deontology, or virtue ethics. State how this normative theory is better than at least one of the mainstream theories, and how it is worse than at least one of the mainstream theories.

*** Should you answer this question?
No, you should not. Do not be fooled by how short it is, it is not an easy question to answer. It is the most philosophical question out of all the given questions. If you don't have much experience writing philosophy essays or don't have much exposure to philosophy, I suggest that you just pretend this question doesn't exist. Even so, this question is more difficult to answer than it seems on the surface.

@@latex: \newpage@@

For one, I'm pretty confident that the lectures will not cover much about non-mainstream normative theories, so you will have to look up the non-mainstream normative theory yourself. Without the lecture slides breaking down everything and putting everything in a more digestible form (yes it really is far more digestible than trying to read philosophy papers), coupled with how difficult it is to find anything of depth regarding philosophy online, you are better off staying far away from this question. The non-mainstream normative theories are quite different from the mainstream normative theories, so you have to spend significant time and effort to understand the theory and really know what it entails, and I'm assuming without the help of the lecture slides. If you have a lot of difficulty trying to understand consequentialism, deontology and virtue ethics, I don't think you will stand a chance with the non-mainstream normative theories.

This question should only be attempted by those who want a challenge, and a difficult one at that. There are a lot of moral theories out there, and it is far too easy to mistake a moral theory that isn't covered in the lectures as a non-mainstream normative theory. It may not be, and it may just be one of the theories under the umbrella of the 3 mainstream normative theories. Some examples include social contract theory or contractarianism, natural law theory, and divine command theory, which are all forms of deontology. It is very difficult to tell the difference as non-philosophers. Furthermore, it is very easy to misunderstand the non-mainstream normative theory you picked and completely screw up the essay, throwing away your grades. You will also have to compare the non-mainstream normative theory you picked with at least one of the mainstream normative theories, which means you really have to understand the mainstream normative theory as well.

As I'm pretty confident that the lectures will not cover anything regarding non-mainstream normative theories, you will most likely have to come up with these comparisons yourself, and form the arguments to show which is better or worse yourself, which is by no means an easy feat by any stretch of the imagination. If you do choose to write this question, you should consult Dr Melvin often to clarify things and make sure you got things right, otherwise, you are very likely going to do worse than everyone else who isn't writing this question. For most people, you should just ignore this question.
