#+TITLE: Cells Notes
#+AUTHOR: Hankertrix
#+STARTUP: showeverything
#+OPTIONS: toc:2
#+LATEX_HEADER: \usepackage{siunitx, graphicx}
#+LATEX_HEADER: \graphicspath{ {./images/} }

\newpage

* Definitions

** Unicellular organisms
A unicellular organism is an organism that consists of only a single cell that does everything. Prokaryotes and protists come under this category. The word "prokaryotes" means "before nucleus" in Greek, indicating that they do not have a nucleus. All organisms in the domain Bacteria and Archaea are prokaryotes. We sometimes refer to them as eubacteria and archaeabacteria. The word "eukaryotes", on the other hand, means "true nucleus" in Greek, and protists belong to this category. Almost all eukaryotes besides protists are multicellular organisms.

** Multicellular organisms
Almost all other eukaryotes besides protists are multicellular organisms. The cells in multicellular organisms developed into specialised types, and this phenomenon is called differentiation. The cells cannot "do-it-all" any more and hence they work together to keep the organism "alive".

** Resolution
Resolution refers to the minimum distance that two points can be apart and still be distinguished as two separate points. The limit of resolution of the human eye is only about 100 \(\unit{\micro\metre}\). One way to increase resolution is to increase magnification, such as by using a microscope.

** Compound light microscopes
Compound light microscopes uses sets of magnifying lenses to resolve structures that are separated by more than 200 \(\unit{\nano\metre}\).

** Electron microscopes
Electron microscopes have 1000 times the resolving power of light microscopes and can resolve objects as close as 0.2 \(\unit{\nano\metre}\) apart.

\newpage

** Plasma membrane
A plasma membrane is essentially a sheet of lipids with embedded proteins. It is a common feature to all cells, although the chemical composition may differ. It defines the boundary of a cell. The lipid bilayer forms the foundation of the membrane and the molecules that make up the lipid layers are called phospholipids. Some proteins form channels that span the membrane (transmembrane proteins) and other proteins are integrated into the structure of the membrane (cell surface proteins).

** Diffusion
Diffusion is when there is net movement of molecules from an area of higher concentration to an area of lower concentration. Molecules diffuse down a concentration gradient from higher to lower concentrations, and diffusion ends when equilibrium is reached. Cells move material in and out of a cell via diffusion.
\\

Only certain substances undergo diffusion across the plasma membrane, like molecules such as oxygen, carbon dioxide, and non-polar lipids. Ions and polar molecules cannot cross the interior of the membrane. However, water is able to diffuse freely across the plasma membrane despite being polar thanks to *aquaporins*.
\\

Diffusion causes water molecules to distribute themselves equally on both sides of a semi-permeable membrane. Addition of solute molecules that cannot cross the membrane reduces the number of free water molecules on that side, as they bind to the solute. Diffusion then causes free water molecules to move from the side where water's concentration is higher, to the solute side where its concentration is lower.

** Osmosis
Osmosis is the movement of solvent or water from a region of lower solute concentration to a region of higher solute concentration through a semi-permeable membrane.

** Aquaporins
Aquaporins are selective channels that permit water to cross.

** Osmotic concentration
The concentration of all molecules dissolved in a solution is called the osmotic concentration of the solution.

** Isotonic
Isotonic refers to the situation where the osmotic concentrations of two solutions are equal.

** Hypertonic
If two solutions have unequal osmotic concentration, the solution with the higher solute concentration is said to be hypertonic.

** Hypotonic
If two solutions have unequal osmotic concentration, the solution with the lower solute concentration is said to be hypotonic.

** Osmotic pressure
Osmotic pressure is the pressure caused by the movement of water into a cell.

** Endocytosis
Endocytosis is the engulfing of substances outside the cell to form a vesicle that is brought inside the cell. This is achieved through the folding of membranes.

** Exocytosis
Exocytosis is the discharge of substances from vesicles at the inner surface of the cell. This is achieved through the folding of membranes.

\newpage

** Selective permeability
- Allows cells to control specifically what enters and leaves.
- Involves using proteins in the membrane for transporting substances across.
- Transport can be down a concentration gradient or against a concentration gradient.

** Selective diffusion
- Proteins act as open channels for whatever that is small enough to fit inside the channel.
- This form of diffusion is common in ion transport.

** Facilitated diffusion
- Proteins act as carriers that can bind only to specific molecules and transport them.
- Transport is limited by the availability of carriers.
- When all carriers are in use, then the transport is saturated.

** Nucleoid region
Nucleoid region refers to an area of the cell where the DNA is localised.

** Flagellum (plural: flagella)
The flagellum is a threadlike structure made of protein fibres that extends from the cell surface that aids in locomotion and feeding. There may be one or many flagella.
\\

The flagella of bacteria rotate to generate motion and are made of flagellin, while eukaryotic flagella are made of microtubule beat and do not rotate. The bacterial flagella motor is composed of approximately 35 proteins and has a base and a hook that connects the cell surface to the filament of the flagellum.

** Pilus (plural: pili)
Pilus is a short appendage that aids in attaching to substrates and in exchanging genetic information between cells.

** Peptido
Peptido refers to "peptides" with a number of amino acids.

** Glycan
Glycan refers to complexes composed of sugar units.

** Nucleus
The nucleus is the command and control centre of the cell. It also stores hereditary information. The nuclear surface is bound by a double-membrane called the *nuclear envelop*. Groups of proteins form openings in the nuclear envelope called *nuclear pores* that permit proteins and ribonucleic acid (RNA) to pass in and out of the nucleus.
\\

The DNA of eukaryotes is packaged into linear chromosomes, and chromosomal DNA is organised into nucleosomes which consist of a portion of DNA wrapped around proteins called histones. When the cell is not dividing, the chromosomes exist as threadlike strands called *chromatin*. Whether the tails of histones are methylated (\(-CH_3\)) or acetlylated (\(-COCH_3\)) determines whether the chromatin exists as heterochromatin (more densely compacted) or *euchromatin* (less densely compacted) respectively.

** Nucleolus
The nucleolus is a region of the nucleus where ribosomes are assembled.

** Ribosomes
Ribosomes are structures that build up proteins and consist of ribosomal RNA and several different kinds of proteins.

\newpage

** Endomembrane system
The endomembrane system refers to the collection of internal membranes in the cell that make up organelles such as the endoplasmic reticulum, Golgi complex, lysosomes and vacuoles. Some of the membranes form channels and interconnections. Other portions become isolated spaces enclosed by membranes, known as vesicles.

** Endoplasmic reticulum (ER)
Endoplasmic reticulum (ER) is an extensive system of internal membranes. The portion of the endoplasmic reticulum dedicated to protein synthesis is called the *rough endoplasmic reticulum*. The surface of this region looks pebbly and the rough spots are due to embedded ribosomes.
\\

The portion of the endoplasmic reticulum that aids in the manufacture of carbohydrates and lipids is called the smooth endoplasmic reticulum. The surface of this region looks smooth because embedded ribosomes are scarce.

** Golgi bodies
The Golgi bodies are flattened stacks of membranes scattered through the cytoplasm and their numbers vary depending on the cell. Their function is to collect, package and distribute molecules manufactured in the cell, such as the molecules made by the endoplasmic reticulum.

** Golgi complex
The Golgi complex refers to the collection of Golgi bodies in the cell. The endoplasmic reticulum and the Golgi complex function together as a transport system of synthesised macromolecules in the cell.

** Lysosomes
The lysosomes are membrane-bound structures that contain enzymes that the cell uses to break down macromolecules. The worn-out parts of the cell are broken down and their components are recycled to form new parts. The particles that the cell has ingested are also digested by the lysosomes.

** Vacuoles
Vacuoles are membrane-bound storage compartments. In plants, the *central vacuole* stores water and dissolved substances and in some protists, the *contractile vacuole* is found near the cell surface of some protists and accumulates excess water from inside the cell that it then pumps out.

** Mitochondria
Mitochondria are cellular powerhouses. They are the sites for chemical reactions called *oxidative metabolism* and the organelle is surrounded by two membranes, the inner and outer membrane. Mitochondria also contain their own molecule of circular DNA, but they cannot be grown free of the cell and are totally dependent on the cells within which they occur.

** Chloroplasts
Chloroplasts are the sites of *photosynthesis*, which are only found in photosynthetic organisms such as plants. The organelle is also surrounded by two membranes, the inner and outer membrane. Chloroplasts also contain their own molecule of circular DNA, but they cannot be grown free of the cell and are totally dependent on the cells within which they occur.

** Endosymbiosis
Endosymbiosis is a theory that states that some organelles evolved from a symbiosis in which one cell of a prokaryotic species was engulfed by and lived inside a cell of another species of prokaryote (that was a precursor to eukaryotes). The engulfed species provided their own hosts with advantages because of special metabolic activities. The modern organelles of mitochondria and chloroplasts are believed to have evolved from these endosymbiotic prokaryotes.

\newpage

** Cytoskeleton
The cytoskeleton comprises an internal framework of protein fibres that anchors organelles to fixed locations, supports the shape of the cell, and helps organise ribosomes and enzymes needed for synthesis.
\\

The cytoskeleton is made of three different types of protein fibres:
- Intermediate filaments, which are thick ropes of intertwined protein
- Microtubules, which are hollow tubes made up of the protein tubulin
- Microfilaments, which are long, slender microfilaments made of the protein actin

** Centrioles
Centrioles are complex structures that assemble microtubules in animal cells and the cells of most protists. They occur in pairs and are found near the nuclear envelop. They are also composed of microtubules.

** Cellular motion
Cellular motion is associated with the movement of actin microfilaments or microtubules. Some cells "crawl" by coordinating the rearrangement of actin microfilaments and some cells "swim" by coordinating the beating of microtubules grouped together to form flagella or cilia.

* Cell Theory
1. All organisms are composed of one or more cells.
2. Cells are the smallest living things.
3. Cells arise only by division of previously existing cells.

* Size of cells
Cells are not of the same shapes and sizes, but they are generally small. Larger cells do not work very efficiently. This is why when organisms become bigger, they have to be multicellular instead of simply becoming a larger cell. Many small cells working together is more efficient that having a single enormous cell.

* Small vs large cells
- Larger cells are more difficult to control because of the *longer distance* between the command centre at the core and the peripheral regions, so organisms that comprises many small cells are at an efficiency advantage.
- Smaller cells also have a greater surface area to volume ratio as the volume increases more rapidly than surface area as the cell size grows. Since a cell's surface provides the interior's only opportunity to interact with the environment, a larger surface area is beneficial to the cell.

\newpage

* Types of cells

** Prokaryotic cells
- Lack a nucleus
- Contains a *plasma membrane* surrounding a cytoplasm without interior compartments.
- Might have a *cell wall* that is made of carbohydrates to confer rigid structure.
- Might have a *capsule* that may surround the cell wall.
- The cytoplasm is uniform with little or no internal support framework.
- Ribosomes (sites for protein synthesis) are scattered throughout the cytoplasm.
- Nucleoid region is not membrane-bound and is not a true nucleus. In general, genomic DNA is organised as *circular* chromosomes.
- Does not have an extensive system of internal membranes.
- All bacteria and archaea have this cell type.

*** Bacteria domain
- 1 - 10 \(\unit{\micro\metre}\)
- Cell wall made of *peptidoglycan*
- Cell membrane based on fatty acids
- No membrane-bound organelles

\newpage

*** Archaea domain
- 1 - 10 \(\unit{\micro\metre}\)
- Cell wall made of various molecules such as pseudopeptidoglycan and proteins
- Cell membrane based on non-fatty acids lipids (isoprene)
- No membrane-bound organelles
- Live in extreme conditions such as the Dead Sea (unusual salt composition) and deep sea vents (temperatures above 100 \(\unit{\degreeCelsius}\) and pressure above 200 atmospheres)

The Dead Sea has a salt concentration of 33% w/v, composed of 53% \(MgCl_2\), 37% $KCl$, and 8% $NaCl$. In contrast, the ocean is mostly $NaCl$ and only has a salt concentration of 3% w/v. The human body only has a salt concentration of around 1% w/v, and it is a mixture of $MgCl_2$, $KCl$ and $NaCl$.
\\

The membrane phospholipids in Archaea carry isoprene chains instead of fatty acid chains. The chirality of the central carbon is also different (L-isomer instead of D-isomer). Tetraether membranes are also found in hyperthermophiles, which are archaea.

\newpage

** Eukaryotic cells
- 10 - 100 \(\unit{\micro\metre}\)
- Has a nucleus, which is a membrane-bound compartment for DNA and is also what gives eukaryotes their name
- Larger and more complex than prokaryotic cells
- The size range among eukaryotic cells is much wider because of the diversity (from protists like paramecium to different types of cells of plants and animals)
- Has a plasma membrane encasing the cytoplasm
- The cytoplasm is semi-fluid and contains a network of protein fibres that form a scaffold called a cytoskeleton
- Its internal membranes form compartments called organelles
- Cell wall made of cellulose or chitin in many cases
- Cell membrane based on fatty acids
- All organisms other than bacteria or archaea have this cell type

*** Differences between eukaryotic cells
- The plasma membrane of animal cells contains cholesterol, but plant cells do not
- The cells of plants, fungi and many protists have a cell wall beyond the plasma membrane
- All plants and many protists contain organelles called chloroplasts
- Plants contain a central vacuole
- Only animal cells contain centrioles

* Chart of relative sizes
Below is the chart showing the relative sizes of organisms:

\[\includegraphics[width = \textwidth]{relative-sizes}\]

* DNA packaging
The /E. coli/ chromosome consists of a circular DNA approximately 1 \(\unit{\milli\metre}\), while the bacterium itself is only about 2 \(\unit{\micro\metre}\) long. This means that the DNA has to be packaged and compacted, which is achieved through supercoiling and assistance by a specific set of nucleoid-associated proteins.

\newpage

* Types of bacteria
Bacteria can either be Gram-positive or Gram-negative, and it is distinguished by the structures of the cell wall. This can be tested through Gram staining procedure of a bacterial specimen followed by observation under a light microscope.
\\

Both types of cell walls carry a peptidoglycan layer.

** Gram-positive
- Thicker
- Stained purple

** Gram-negative
- Has an outer membrane next to the peptidoglycan layer
- Stained pink

* Gram stain procedure
1. When crystal violet is applied, both types of cells take in the dye.
2. When Gram's iodine is next added, a crystal of violet-iodine complex is formed inside the cells.
3. After an alcohol wash, only the Gram-positive bacteria retain the crystal violet dye in their cells.
4. Afterwards, safarin dye is added and the pink or red colour of the safarin dye is only visible on Gram-negative cells.

* Structures

** Animal cells
\[\includegraphics[width = \textwidth]{animal-cell-structure}\]

** Plant cells
\[\includegraphics[width = \textwidth]{plant-cell-structure}\]

** Nucleus
\[\includegraphics[width = \textwidth]{nucleus-structure}\]

** Cytoskeleton
\[\includegraphics[width = \textwidth]{cytoskeleton-structure}\]

** Centrioles
\[\includegraphics[width = \textwidth]{centrioles-structure}\]

** Flagella and Cilia
\[\includegraphics[width = \textwidth]{flagella-and-cilia-structure}\]
