#+TITLE: NMR Cheat Sheet
#+AUTHOR: Hankertrix
#+STARTUP: showeverything
#+OPTIONS: toc:2
#+LATEX_HEADER: \usepackage{chemfig, siunitx}

\newpage

* Definitions

** NMR spectroscopy
Nuclear magnetic resonance (NMR) spectroscopy is based on the absorption of radio frequency (RF) radiation by the nucleus in a strong magnetic field. So NMR is basically just applying a magnetic field to an atom or molecule and seeing the resulting emitted RF spectrum.

** Chemical shift
The chemical shift of the compound is defined by the frequency of the resonance expressed with reference to a standard compound which is defined to be at 0ppm. A *shielded* proton is said to be *upfield* while a *deshielded* proton is said to be *downfield* in a NMR spectroscopy.

** Magnetic equivalence
Nuclei having the same resonance frequency in nuclear magnetic resonance spectroscopy and also identical spin-spin interactions with the nuclei of a neighbouring group are *magnetically equivalent*. The spin-spin interaction between magnetically equivalent nuclei does not appear, and thus has no effect on the multiplicity of the respective NMR signals.

** The (n+1) rule
The (n+1) rule states that the multiplicity of a multiplet is given by the number of magnetically equivalent protons in the neighbouring atoms plus one.

\newpage

* Electron Shielding
The magnetic field applied in NMR spectroscopy causes the electrons to spin.
\[\downarrow\]
The electrons will then generate their own magnetic field that opposes the applied magnetic field.
\[\downarrow\]
This magnetic field shields the nucleus from the full effect of the applied magnetic field by a small but measurable amount.
\[\downarrow\]
The effective magnetic field would be hence be different from the applied magnetic field.
\[\downarrow\]
Hence, we can use the electron density around the nucleus to differentiate the signals generated by the different nuclei in a molecule.

** Effect of electron shielding
With greater electron density around the nucleus.
\[\downarrow\]
The nucleus is shielded from the magnetic field to a greater extent.
\[\downarrow\]
With greater shielding, the effective magnetic field felt by the nucleus is weaker.
\[\downarrow\]
The weaker magnetic field causes the energy gap between the two nuclear spin states to be smaller.
\[\downarrow\]
The smaller energy gap means that less energy is required to flip the nuclei from a lower energy spin state to a higher energy spin state.
\[\downarrow\]
The energy is proportional to the frequency, so a nucleus that is shielded by its greater electron density will have a lower resonance frequency compared to a nucleus that has lower electron density.

* Calculating chemical shift (\(\delta\))
\begin{align*}
\text{Chemical Shift, } \delta &= \frac{\text{Frequency of signal - Frequency of reference}}{\text{Spectrometer frequency}} \times 10^6 \\
\delta &= \frac{\text{Observed chemical shift (Number of \si{\hertz} away from TMS)}}{\text{Spectrometer frequency in \si{\mega\hertz}}}
\end{align*}

* Deuterated solvents
Deuterated solvents, which are solvents that have 99.8% of their hydrogen atoms replaced with deuterium, like $CDCl_3$ (instead of $CHCl_3$).

** Why do we use deuterated solvents?
- So that the hydrogen atoms in the solvent do not interfere with the signals given out by the hydrogen atoms in the atom or molecule that we are looking at in NMR spectroscopy.
- The spectrometer can constantly monitor the resonance frequency of the deuterated solvent and adjust the magnetic field to keep the resonance frequency of the deuterated solvent constant.
- Because of the above reason, we can use deuterated solvents as a reference to calibrate the NMR spectroscopy.

** Tetramethylsilane (TMS) as a reference compound
The molecule called Tetramethylsilane (TMS) is often used as a reference as it is a very shielded compound which always gives a resonance signal of 0ppm. TMS is also very unreactive and doesn't react with most other compounds. As such, it is used as a reference to calibrate the scale for NMR spectroscopy.

\[
\chemname{
\chemfig{Si(-[:0]CH_3)(-[:90]CH_3)(-[:180]CH_3)(-[:270]CH_3)}
}{Tetramethylsilane (TMS)}
\]


* Chemical shift (\(\delta\))

** Factors affecting chemical shift
- Inductive effects by electronegative groups
- Magnetic anisotropy
- Hydrogen bonding

** Inductive effects by electronegative groups
Electronegative groups such as $-OH$, $-F$ and $-Cl$ that are attached to the $C-H$ system decrease the electron density around the protons.
\[\downarrow\]
\[\text{There is less shielding around the protons.}\]
\[\downarrow\]
\[\text{So chemical shift increases.}\]

\newpage

** Magnetic anisotropy
When a magnetic field is applied to a molecule that has a $\pi$ system (double or triple bond, or a benzene ring), the applied magnetic field will cause the electrons in the $\pi$ system to spin. This in turn causes the molecule to set up its own magnetic field, called an *induced magnetic field*, at the *centre* of the $\pi$ system, which is at the centre of the double or triple bond for non-aromatic compounds, and at the centre of the benzene ring for aromatic compounds. The induced magnetic field that is set up by the $\pi$ system will always *oppose* the applied magnetic field. Hence, the induced magnetic field will always *oppose* the applied magnetic field at the *centre* of the $\pi$ system.
\\

To determine if the effective magnetic field $H_{eff}$ will be greater or smaller than the applied magnetic field $H_{0}$, we will need to draw the magnetic field lines going out in a circle around the *centre* of the $\pi$ system, where the induced magnetic field is set up. The direction of the magnetic field lines originating from the *induced magnetic field* at the hydrogen atom of interest will tell you if the $H_{eff}$ will be greater or smaller than the applied magnetic field $H_{0}$.
\\

If the direction of the magnetic field lines originating from the induced magnetic field is in the *same* direction as the applied magnetic field at the hydrogen atom of interest, then the effective magnetic field $H_{eff}$ will be *greater* than the applied magnetic field $H_{0}$.
\\

If the direction of the magnetic field lines originating from the induced magnetic field is in the *opposite* direction of the applied magnetic field at the hydrogen atom of interest, then the effective magnetic field $H_{eff}$ will be *smaller* than the applied magnetic field $H_{0}$.
\\

Generally, the hydrogen atoms that are located *in* the centre (or *close* to the centre) of a $\pi$ system will experience a *smaller* effective magnetic field $H_{eff}$ while the hydrogen atoms that are located *away* from the centre of a $\pi$ system (which means they are *towards the side* and not in the middle) will experience a *greater* effective magnetic field $H_{eff}$. Do note that the hydrogen atoms must be directly bonded to the carbon atom with the double or triple bond to be affected by magnetic anisotropy.
\\

Here is a [[https://youtu.be/w8ew5bvdrqg][video]] to watch if you still have trouble understanding the concept.

** Hydrogen bonding
Protons that are involved in hydrogen bonding (usually $-OH$ and $-NH$) are typically observed *over a large range of chemical shift values*. The more hydrogen bonding there is, the more the proton is deshielded and the higher its chemical shift will be.

*** Determining between $-OH$ and $-NH$
$-OH$ and $-NH$ protons can be identified by carrying out a simple $D_2O$ (heavy water) exchange experiment.
1. Run the regular H-NMR experiment
2. Add a few drops of $D_2O$
3. Re-run the H-NMR experiment
4. Compare the two spectra and look for signals that have "disappeared"

*** Why would a signal disappear?
Consider the alcohol case for example:
\[R-OH + D_2O \rightleftharpoons R-OD + HOD\]

During the hydrogen bonding, the alcohol and heavy water can "exchange" -H and -D amongst each other, so the alcohol becomes $R-OD$. Although $D$ is NMR active, its signals are of different energy and will not be seen in the H-NMR. Thus, the signal due to the $-OH$ disappears. The signal due to HOD will appear, however.


* Spin-spin coupling

For spin-spin coupling to occur, the hydrogen atom must be within 3 bonds of a $C-H$ system and the hydrogen atom must not be blocked by an electronegative atom such as $O$, $N$, $S$, or $Cl$.
\\

Generally, you will need to look at the $R$ groups that are within 3 bonds of a hydrogen atom to determine the spin-spin coupling of that particular hydrogen atom.

** Multiplicities of signals
1. Singlet
2. Doublet
3. Triplet
4. Quartet
5. Quintet

** Relative intensities
The relative intensities of the lines in a group of split signals is given by a binomial expansion, or Pascal's Triangle. So for a 1H-NMR, a proton with 0 neighbours, appears as a single line, while a proton with 1 neighbour will have 2 lines of equal intensity, and a proton with 2 neighbours will have 3 lines of intensities in the ratio of 1:2:1.

** Identifying multiplets
Multiplets have the same separation between the signals, which is called a coupling constant ($J$).

** Calculating the coupling constant (\(J\))
\[\text{Operating frequency } (\si{\mega\hertz}) \times \text{Splitting } (\si{ppm}) = \text{Coupling Constant } (\si{\hertz})\]

Splitting is the difference between the $\si{ppm}$ values of each signal of the multiplet. It is the gap between the individual signals of the multiplet. For a multiplet that has more than one gap, such as a quartet, you should take the average of all the gaps to calculate the coupling constant. The final ($J$) value is usually rounded to *one decimal place*.

Coupled protons will have the same $J$ values if they don't have any other couplings.

\newpage

** What causes the signal to split?
A nucleus under examination is perturbed by a nearby nuclear spin.
\[\downarrow\]
The currently observed nucleus will respond the perturbation, which is shown in its resonance signal.
\[\downarrow\]
This spin coupling is *transmitted through the connecting bonds*.
\[\downarrow\]
When the perturbing nucleus becomes the observed nucleus, it also exhibits the same signal splitting with the same coupling constant ($J$).
