#+TITLE: MA1008 Introduction to Computational Thinking Cheat Sheet
#+AUTHOR: Hankertrix
#+STARTUP: showeverything
#+OPTIONS: toc:2
#+LATEX_HEADER: \usepackage{array}

* Definitions

** Programming
Programming is the process of:
- Implementing a representation of the solution for the computer to execute
- Taking an algorithm and encoding it using certain programming language

** Programming language
- A medium through which programmer may give instructions to a computer.
- It must support certain control constructs and data types needed to implement algorithms.

** High-level programming languages
- Provide abstraction from the internal operating detail of the computer.
- Enable the programmers to focus on solving the problem.
- Make the process of developing the algorithm simpler

** Microprocessor
The microprocessor in a computer is a digital device consisting of electronic components like transistors that operate in two states (either *on* or *off*).

*** The two states as voltage levels
- Low voltage (0 volt)
- High voltage (depends on the power supply used by the microprocessor)

*** The two states represented in binary
- 0 for low voltage
- 1 for high voltage

** Datum
A datum is a number.

** Byte
1 byte = 8 bits (2 hex digits)

** Nibble
1 nibble = 4 bits (1 hex digit)

** Word
1 word = 16 or 32 bits depending on CPU architecture (32 bits is used in this course)

** DWord
1 DWord = 64 bits

** Algorithms
Algorithms are the method, procedure, or steps for solving a problem.

*** Expressing an algorithm
- Must be unambiguous, every step must be clear and precise
- Specify the order of steps precisely (sequence)
- Consider all possible decision points (branching and looping)
- Must terminate (no matter which representation is used)

@@latex: \newpage@@

** Flow chart
A representation of an algorithm using diagrams for effective visualisation.

#+ATTR_LATEX: :environment tabular :align |c|m{22em}|
|----------------------+----------------------------------------------------------------------------------------------|
| *Name*               | *Use in flowchart*                                                                           |
|----------------------+----------------------------------------------------------------------------------------------|
| Oval                 | Denotes the beginning or end of a program                                                    |
|----------------------+----------------------------------------------------------------------------------------------|
| Flow line (an arrow) | Denotes the direction of logic flow in a program                                             |
|----------------------+----------------------------------------------------------------------------------------------|
| Parallelogram        | Denotes either an input operation (INPUT) or an output operation (PRINT)                     |
|----------------------+----------------------------------------------------------------------------------------------|
| Rectangle            | Denotes a process to be carried out, like addition                                           |
|----------------------+----------------------------------------------------------------------------------------------|
| Diamond              | Denotes a decision or branch to be made; the program should continue along one of two routes |
|----------------------+----------------------------------------------------------------------------------------------|

** Pseudocode
Directly uses informal English to describe an algorithm step by step with one step per line. It uses the structural conventions of a normal programming language, but is intended for human reading rather than machine reading. Syntax doesn't matter in pseudocode.

*** Guidelines
- Write one statement per line only
- Capitalise the keywords
- Indent to show hierarchy
- End multi-line structures like loops and if statements
- Keep statements programming-language independent

** Variable
A variable is like a labelled box that contains a value inside it. Each variable has its name, like ~price_of_chicken_rice~ and value, like ~2.8~.

*** Why use variables?
- Reuse names instead of values, which is helpful in keeping track of useful information without needing to remember a bunch of numbers
- Easier to change or refactor the code later

** Expressions
Expressions are anything that produces or returns a value. It usually consists of a combination of values (literals, variables, etc) and operations (operators, functions, etc).

*** Examples
- 3.14
- 100 * 15
- Result * 100

** Assignment operator (=)
The assignment operator binds variables and values. The "=" sign is the *assignment operator*, not the equality in mathematics.

*** Syntax
Left-Hand Side (LHS) = Right-Hand Side (RHS)

This means:
- Evaluate the expression on the right-hand side
- Take the resulting value and assign it to the name (variable) on the left-hand side

** Arithmetic operators (~+, -, *, /~)
- Used in common arithmetic
- Each arithmetic operator is a mathematical function that takes one or two operands and performs a calculation on them
- Most computer languages contain a set of such operators that can be used within equations to perform a number of types of sequential calculation

** Identifiers
A name given to an entity in a programming language.
- Helps in differentiating one entity from another
- Name of the entity must be unique to be identified during the execution of the program

*** Attributes of identifiers in Python
- Uppercase and lower case letters A through Z
- The underscore "_"
- The digits 0 through 9
- However, the first character cannot be a digit
- Identifiers are case-sensitive

*** Naming conventions in Python
- Variables names should be in lowercase, with words separated by underscores as necessary to improve readability (~snake_case~).

** Keywords
Keywords are special words that are reserved by a programming language. Programmers should not use keywords to name things.

** Conditional statement
A conditional statement performs different actions depending on whether the condition evaluates to true or false.

** Conditional expression (Boolean expression)
A conditional expression may be composed of a combination of the Boolean constants True or False, Boolean-typed variables, Boolean-valued operators, and Boolean-valued functions.

** Nested ~if~ statements
A nested ~if~ statement is an ~if~ statement inside another ~if~ statement.

** Relational operators (~==, !=, <, <=, >, >=~)
A relational operator compares two numbers (float or int) and returns a Boolean value of either True or False.

#+ATTR_LATEX: :environment tabular :align c|c|c
| Relational Operator | Meaning                  | Example  |
|---------------------+--------------------------+----------|
| ==                  | Equal to                 | a == 1   |
| !=                  | Not equal to             | b != 2   |
| <                   | Less than                | c < 3    |
| <=                  | Less than or equal to    | d <= 4   |
| >                   | Greater than             | f > 5.0  |
| >=                  | Greater than or equal to | g >= 6.0 |

** Program execution and control flow
- Control flow controls which instruction should be executed next.
- By default, program instructions are executed one after another.
- However, some structures can alter the flow, like selection.
- Selection (branching) occurs when an "algorithm" makes a choice to do one of two or more things.
- The flow control in a program is, in essence, logic.
- When writing or reading a program, ensure that you could understand the flow, i.e., what should be executed next for every step.

** Logical operators (Boolean operators)
Logical operators connect Boolean values and expressions and *return* a Boolean value as a result.

#+ATTR_LATEX: :enviroment tabular :align c|c|c
| Operator | Example                           | Meaning                             |
|----------+-----------------------------------+-------------------------------------|
| *not*    | *not* number < 0                  | Change True to False, or vice versa |
| *and*    | (num1 > num2) *and* (num2 > num3) | Return True only if *both* are True |
| *or*     | (num1 > num2) *or* (num2 > num3)  | Return True if *either* one is True |

@@latex: \newpage@@

** Looping
A computer program can dynamically choose how many times it repeats certain instructions during the program runtime.

*** General structure of a loop
1. *Initialise* the loop control variable.
2. *Test*: continue the loop or not?
3. *Loop body*: main computation being repeated.
4. *Update*: Modify the value of the loop control variable so that next time we test, we may exit the loop.

Sometimes, a loop may not have all of them, such as an infinite loop, where the test condition is always true.

*** Types of loops
1. Counter-controlled loop
   The number of repetitions can be *known* before the loop body starts. This loop just repeats the loop on each element in a preset sequence.

2. Sentinel-controlled loop
   The number of repetitions is *not known* before the loop body starts. Hence, a sentinel value that differs from normal data, like -1, is used to stop the loop.

** Iteration
A one-time execution of a loop body is referred to as an iteration of the loop.

** Nested loop
A nested loop is a loop inside another loop. An outer loop may enclose an inner loop.

@@latex: \newpage@@

** Abstraction
- *Simplifies* things
- Identifies what is *important* without worrying too much about the details
- Allows us to *manage complexity*.

*** Why is abstraction important?
- A key element of computing is the complexity of the systems we build.
- Abstraction provides a means to distil what is essential, giving a manageable approach to create computational solutions.
- Abstractions are sometimes represented as *layers* or *hierarchies*, allowing us to view things at different degrees of detail.

** String
A string is a sequence of characters. The sequence of characters is important and is maintained.

** ASCII
- Uses 8 bits to store a character.
- 2^{8} = 256 different characters.

** Unicode
- An extension of ASCII
- Able to include more characters
- Uses 16 bits to store a character
- 2^{16} = 65,536 characters
- The Unicode space is divided into 17 planes.
- Each plane contains 65,536 code points (16-bit).
- Total of 1,114,112 characters, 96,000 used.

** Function
- A function is a *piece of code* that performs some operation.
- The details are hidden (encapsulated) and only it's interface is exposed.
- It is a way to arrange a program to make it easier to understand.
- A function has arguments as inputs and may return one output.

** Method
- A method is a variation on a function.
- It represents a program and has input arguments and output.
- Unlike a function, it is applied in the context of a *particular object*.
- This is indicated by the *dot notation* invocation.

*** Method chaining
Methods can be chained together. For example:
#+NAME: method-chaining
#+begin_src python :results output :exports both
string = "Python is cool!"
print(string.upper())
print(string.upper().find("C"))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: method-chaining
: PYTHON IS COOL!
: 10

** Composite type
- Composite type is a data type which is constructed (composed) using primitive and other composite types.
- A composite type is basically a new data type that is made from existing ones.
- Some examples in Python include tuples, lists, dictionaries (hash maps in most other programming languages) and strings.

** Data structures
- They have particular ways of storing data to make some operations easier or more efficient.
  - They are tuned for certain tasks, and they are often associated with algorithms.
- Different data structures have different characteristics.
  - One suited to solving a *certain problem* may not be suited for another problem.
- A few examples include arrays, linked lists, hash maps and trees.

*** Built-in data structures
Data structures that are so common that they are provided by most programming languages by default.

*** User-defined data structures
Data structures (classes in object-oriented programming) that are designed for a particular task.

** Mutability
The ability to change.

** Mutable
- After creation of the object, the object *can* be changed.
- *Lists* are mutable as you *can* change them after creating them.

** Immutable
- After creation of the object, the object *cannot* be changed.
- *Strings* are immutable as you *cannot* change them after creating them.

@@latex: \newpage@@

* Program translations

** Interpretation approach
- Uses a program known as an interpreter
- Reads one high-level code statement at a time
  - Immediately translates and executes the statement before processing the next one

*** Examples
- Python
- R
- JavaScript
- TypeScript
- Lua
- Lisp

*** Benefits
- Very portable across different computing platforms
- Produces results almost immediately
- Easy to debug
- Program executes more slowly
- Useful for implementing dynamic, interactive features, such as those used on web pages

@@latex: \newpage@@

** Compilation approach
- Uses a program called a compiler
- Reads and translates the entire high-level language program (source) code into its equivalent machine-language instructions in an executable file
- The resulting machine-language instructions can then be executed directly on the computer when the program is launched

*** Examples
- C
- C++
- Rust
- Go
- Zig
- Nim

*** Benefits
- Program runs very fast AFTER compilation
- Smaller in code size after compilation
- Must compile the entire program before execution
- Needs to be re-compiled if to be used on different computing platforms
- Used in large and sophisticated software applications when speed is of the utmost importance

** Combination of compilation and interpretation
It is also possible to use the combination of both translation techniques.

*** Examples
- Java


* Computer organisation

** Central processing unit (CPU)
- Processes information
- Performs operations based on information given

*** Control unit (CU)
- Controls and coordinates the overall operation of the CPU
- Consists of decoders and logic circuits
- Controls the overall operations of the various units and modules
- Driven by a clock signal to ensure that everything happens at the correct instances and in proper sequence

*** Arithmetic/Logic Unit (ALU)
- Performs arithmetic operations as well as Boolean logic functions
- Deals with arithmetic operations like addition, subtraction, multiplication and division (if supported)
- Also performs logic operations (i.e. Boolean operations) like AND, OR, NOT, XOR etc, and bit shifting/rotation

*** Register Array
- Holds the various information used by CPU operations
- A small amount of very high speed internal storage used for frequently accessed data
- Enables data to be stored and retrieved quickly
- Some of these registers are used for more specific functions, like program counter, instruction register, stack pointer, memory address register, accumulator, etc

*** Program counter (PC) (special register)
Tells the control unit where to find the instruction in memory.

*** Instruction register (IR) (special register)
Holds the copy of the instruction to be decoded and executed by the control unit.

*** Data, Address and Control Signals
- Consists of signalling wires that are grouped into data signals, address signals, and control signals
- The signals connect the various internal functional units together
- Extend to the external system bus for other modules (memory and I/O) of the microprocessor

** Memory
- Memory is used to store instructions and data for the CPU
- Consists of high speed electronics components that store the information in binary bit format
- Each location stores an 8-bit (byte) size data
- Each location is allocated a unique address
- Identified by specifying its binary pattern on the address bus
- If data is more than 8 bits in size (e.g. a 32-bit word), consecutive locations are used, and the lowest byte address is used to access the word location

*** Memory size
It is dependent on the number of bits (n) used in its address bus. Memory size = 2^{n} bytes.

- When n = 10, 2^{10} = 1024 bytes or 1 kilobyte (KB)
- When n = 20, 2^{20} = 1024 × 1 KB = 1048576 bytes or 1 megabyte (MB)
- When n = 30, 2^{30} = 1 KB × 1 KB × 1 KB = 1073741824 bytes or 1 Gigabyte (GB)

** Input/Output (I/O) Interface
- Mechanism for transferring information to and from the outside world, such as to interact with users

** System Bus
- The system bus consists of groups of parallel signals that are used to transfer information between the modules in the microprocessor.
- The system bus is used to connect external devices, such as memory and I/O devices, to the functional units within the CPU.

*** Data Bus
- Conveys the information from one module to the other.

*** Control Bus
- Provides the control signals for the modules to work together, such as to determine the direction of data flow, and when each device can access the data bus and address bus.

*** Address Bus
- Used to convey the address information. The signals' pattern on the address bus lines determines the location of the source and destination of the data transfer.


* Information in a computer

** Types of information
- Instructions
- Data

@@latex: \newpage@@

** Information representation

*** Binary format (base-2)
- General expression: b_{n-1} ... b_{k} ... b_{2}b_{1}b_{0}
- Example of an 8-bit binary number: 01001101b
- The decimal (base-10) value can be calculated as:
  2^{n-1} × b_{n-1} + ... + 2^{k} × b_{k} + ... + 2^{2} × b_{2} + 2^{1} × b_{1} + 2^{0} × b_{0}

- The k^{th} bit will have a weightage of 2^{k}.

*** Hexadecimal format (base-16)
- Hexadecimal symbols: 0, 1, 2, ..., 8, 9, A (10), B (11), C (12), D (13), E (14), F (15)
- Each hexadecimal is 4 binary bits
- The binary format data is separated into groups of 4 bits:
  1011 0101 0110 1100 = B56C


* Program execution

** Instruction execution
1. On power up, the program instruction will be typically first loaded into certain default memory locations (together with data).
2. A clocking signal is also applied to the CPU (as well as to the rest of the microprocessor system).
3. Based on the rising or falling edges of the clock, the control unit (CU) will retrieve (fetch) the instruction from the default memory location.
4. The control unit (CU) of a CPU is designed to recognise its own instructions and performs the corresponding operation.

@@latex: \newpage@@

** Fetch
Fetch the instruction from the memory into the instruction register (IR) using the address indicated by the program counter (PC).

** Decode
Decode the machine instruction by the control unit, which is now stored in the instruction register (IR).

** Execute
Execute the instruction. For example, loading the operands into the arithmetic/logic unit (ALU) and get the ALU to operate on them.

@@latex: \newpage@@

* Data types in Python
Python uses duck-typing to figure out the type of a variable.
- Python does not have variable declaration, like Java or C, to announce or create a variable.
- A variable is created by just assigning a value to it and the type of the value defines the type of the variable.
- If another value is re-assigned to the variable, its type can change.

** Why differentiate between data types?
1. The underlying representations for different data types are different.
2. Different data types support different operations, and for these operations to work, we need to supply them with variables of the correct types.
3. The objects we wish to represent in a computer program are of different types in nature and require different data types.

** String (~str~)
- It is a sequence, typically a sequence of characters delimited by single quotes ~'~ or double quotes ~"~.
- The sequence of characters is important and is maintained.
- Use either single or double quotes to create a string.
- Do not use both single and double quotes to create a string.
- Escape a quote by using the backslash character "\".

@@latex: \newpage@@

*** Index (~[]~)
- Characters in a string are in a sequence
- We can identify each character with a unique index (a position in the sequence).
- We can index a character from either end of the sequence.
  - Non-negative values: counting from left, starting at 0
  - Negative values: counting from right, starting at -1
- The index operator is always at the end of the expression and is preceded by something, either a variable or a sequence.

We can use ~[]~ to access particular characters in a string.
#+NAME: string-indexing
#+begin_src python :results output :exports both
string = "Hello World"
print(string[0])
print(string[1])
print(string[-2])
print(string)
print("omg wow"[4])
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-indexing
: H
: e
: l
: Hello World
: w

@@latex: \newpage@@

*** Slice (~[:]~)
~[start : end : step]~
- ~start~ is the index of the start of the subsequence.
- ~end~ is the index of the end of a subsequence (not included).
- ~step~ specifies the step size to jump along the sequence.

#+NAME: string-slicing
#+begin_src python :results output :exports both
string = "Hello World"
print(string[1:4])
print(string[::2])
print(string[::-2])
print(string[0:14:-1])
print("omg wow"[2:6])
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-slicing
: ell
: HloWrd
: drWolH
:
: g wo

*** Length (~len~)
#+NAME: length-of-a-string
#+begin_src python :results output :exports both
string = "Hello World"
print(len(string))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: length-of-a-string
: 11

*** Concatenation (~+~)
#+NAME: concatenate-string
#+begin_src python :results output :exports both
string = "Hello World"
print(string + "!")
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: concatenate-string
: Hello World!

*** Repeat (~*~)
#+NAME: repeat-string
#+begin_src python :results output :exports both
string = "Hello World"
print(string * 3)
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: repeat-string
: Hello WorldHello WorldHello World

*** Comparison
The ASCII or Unicode code obtained using the ~ord~ function is used to compare strings.
#+NAME: string-comparison
#+begin_src python :results output :exports both
print("a" == "a")
print("a" < "b")
print("1" < "9")
print("a" < "B")
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-comparison
: True
: True
: True
: False

*** Membership (~in~)
~a in b~ is True if string ~a~ is contained in string ~b~.
#+NAME: string-membership
#+begin_src python :results output :exports both
string = "abcdef"
print("c" in string)
print("cde" in string)
print("cef" in string)
print(string in string)
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-membership
: True
: True
: False
: True

*** Immutability
- Strings are immutable, which means you cannot change a string after it has been created.
  #+begin_src python :results none
  string = "spam"
  string[1] = "l"  # Error
  #+end_src

- However, you can use it to make another string:
  #+NAME: string-edit
  #+begin_src python :results output :exports both
  string = "spam"
  new_string = string[:1] + "l" + string[2:]
  print(new_string)
  #+end_src

  @@latex: \noindent@@ Output:

  #+RESULTS: string-edit
  : slam

@@latex: \newpage@@

** Lists (~list~)
- A list is an *ordered sequence of items*.
- As with all data structures, lists have a *constructor* that is the same name as the data structure.
- Lists are delimited with square brackets (~[]~).

*** Creation
Constructing a list or initialising a list both mean creating a list.

- Creating an empty list
  #+begin_src python :results none
  l = list()
  l = []
  #+end_src

- Creating a list from an iterable data structure, like a set, a tuple, or a string

  #+NAME: list-create-from-iterable
  #+begin_src python :results output :exports both
  print("List from tuple: ", list((1, 2, 3, 4)))
  print("List from set: ", list({1, 2, 3, 4}))
  print("List from string: ", list("1234"))
  #+end_src

  @@latex: \noindent@@ Output:

  #+RESULTS: list-create-from-iterable
  : List from tuple:  [1, 2, 3, 4]
  : List from set:  [1, 2, 3, 4]
  : List from string:  ['1', '2', '3', '4']

- Creating a list with predefined items
  #+begin_src python :results none
  l = [1, 2, 3, 4]
  l = [1, 3.14159, "a", True]
  #+end_src

*** Index (~[]~)
- Items in a list are in a sequence
- We can identify each item in the list with a unique index (a position in the sequence).
- We can index an item from either end of the sequence.
  - Non-negative values: counting from left, starting at 0
  - Negative values: counting from right, starting at -1
- The index operator is always at the end of the expression and is preceded by something, either a variable or a sequence.

We can use ~[]~ to access particular items in a list.
#+NAME: list-indexing
#+begin_src python :results output :exports both
l = [1, "omg wow", 420.69, False]
print(l[0])
print(l[1])
print(l[-2])
print(l)
print(["hey", 5, True][0])
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: list-indexing
: 1
: omg wow
: 420.69
: [1, 'omg wow', 420.69, False]
: hey

@@latex: \newpage@@

*** Slice (~[:]~)
~[start : end : step]~
- ~start~ is the index of the start of the subsequence.
- ~end~ is the index of the end of a subsequence (not included).
- ~step~ specifies the step size to jump along the sequence.

#+NAME: list-slicing
#+begin_src python :results output :exports both
l = [1, "omg wow", 420.69, False]
print(l[1:4])
print(l[::2])
print(l[::-2])
print(l[0:3:-1])
print(["hey", 5, True, "lovely"][2:4])
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: list-slicing
: ['omg wow', 420.69, False]
: [1, 420.69]
: [False, 'omg wow']
: []
: [True, 'lovely']

*** Length (~len~)
#+NAME: length-of-a-list
#+begin_src python :results output :exports both
l = [1, "omg wow", 420.69, False]
print(len(l))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: length-of-a-list
: 4

*** Concatenation (~+~)
#+NAME: concatenate-list
#+begin_src python :results output :exports both
l_1 = [1, "omg wow", 420.69, False]
l_2 = ["Finger licking good!", True, "I'm loving it!"]
print(l_1 + l_2)
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: concatenate-list
: [1, 'omg wow', 420.69, False, 'Finger licking good!', True, "I'm loving it!"]

*** Repeat (~*~)
#+NAME: repeat-list
#+begin_src python :results output :exports both
l = [1, "omg wow", 420.69, False]
print(l * 2)
l = [3]
print(l * 5)
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: repeat-list
: [1, 'omg wow', 420.69, False, 1, 'omg wow', 420.69, False]
: [3, 3, 3, 3, 3]

*** Comparison
- The items of a list are compared starting from the first item.
- This means for the greater than, or less than operators, the list that has the higher value at the front of the list is considered to be greater than the list with the same value at the back of the list.
- The boolean ~True~ is changed into 1 and the boolean ~False~ is changed to 0 comparing lists.
- For two lists to be equal, all items in both lists must be the same, and have the same order.
#+NAME: list-comparison
#+begin_src python :results output :exports both
print([4, 3, 2, 1] > [1, 2, 3, 4])
print([4, 3, 2, 1] == [1, 2, 3, 4])
print([True, 3, 2, 1] >= [1, 2, 3, 4])
print([False, 2, 3, 4] <= [1, 2, 3, 4])
print(["a", "list", "of", "strings"] <= ["string", "list"])
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: list-comparison
: True
: False
: True
: True
: True

*** Membership (~in~)
~a in b~ is True if ~a~ is contained in the list ~b~.
#+NAME: list-membership
#+begin_src python :results output :exports both
l = [1, "omg wow", 420.69, False]
print(1 in l)
print(420 in l)
print("omg wow" in l)
print("omg" in l)
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: list-membership
: True
: False
: True
: False

*** Minimum (~min~)
- Gets the smallest element in the list.
- Only applicable to *lists containing strings only* or *lists containing numeric values (~int~ and ~float~) and boolean values*.
- The boolean ~True~ is changed into 1 and the boolean ~False~ is changed to 0 when evaluating the minimum of a list.

#+NAME: list-min
#+begin_src python :results output :exports both
l_1 = [1, 2, 420.69, 699]
l_2 = [1, 2, True, False]
l_3 = ["ooo", "a", "list", "of", "Only", "Strings"]
print(min(l_1))
print(min(l_2))
print(min(l_3))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: list-min
: 1
: False
: Only

*** Maximum (~max~)
- Gets the largest element in the list.
- Only applicable to *lists containing strings only* or *lists containing numeric values (~int~ and ~float~) and boolean values*.
- The boolean ~True~ is changed into 1 and the boolean ~False~ is changed to 0 when evaluating the maximum of a list.

#+NAME: list-max
#+begin_src python :results output :exports both
l_1 = [1, 2, 420.69, 699]
l_2 = [1, 2, True, False]
l_3 = ["ooo", "a", "list", "of", "Only", "Strings"]
print(max(l_1))
print(max(l_2))
print(max(l_3))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: list-max
: 699
: 2
: ooo

*** Sum (~sum~)
- Gets the sum of the elements of the list.
- Only applicable to lists containing numeric values (~int~ and ~float~) and boolean values.
- The boolean ~True~ is changed into 1 and the boolean ~False~ is changed to 0 when evaluating the maximum of a list.

#+NAME: list-sum
#+begin_src python :results output :exports both
l_1 = [1, 2, 420.69, 699]
l_2 = [1, 2, True, False]
print(sum(l_1))
print(sum(l_2))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: list-sum
: 1122.69
: 4

*** Mutability
Lists are mutable, which means you can change them after you create them.
#+NAME: list-mutability
#+begin_src python :results output :exports both
l = [1, "omg wow", 420.69, False]
l[1] = "changed the list hehe"
print(l)
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: list-mutability
: [1, 'changed the list hehe', 420.69, False]

*** List of lists
A list can be nested inside another list.
#+NAME: nested-list
#+begin_src python :results output :exports both
l = [1, [1, "a", "list", True], 420.69, False]
print(l[1])
print(l[2])
print(l[1][2])
l[1][3] = "hehe changed the inner list"
print(l)
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: nested-list
: [1, 'a', 'list', True]
: 420.69
: list
: [1, [1, 'a', 'list', 'hehe changed the inner list'], 420.69, False]

*** Differences from strings
- Lists can contain a *mixture of Python objects (types)* while strings can only hold characters. (This is not recommended though, your list should only hold items of the same type, otherwise it makes things very difficult to work with.)
- Lists are mutable, which means you can change them.
- Lists are designated with square brackets (~[]~), with elements separated by commas (~,~), while strings use double quotes ~"~ or single quotes ~'~.

** Tuples (~tuple~)
- Tuples are immutable lists, or lists that cannot be changed.
- They are designated by *commas (~,~)*, *NOT* round brackets (~()~).
- Round brackets are often used to make tuples more readable, and used to group the items (like in nested tuples), but they are not what makes a tuple.

*** Creation
Constructing a tuple or initialising a tuple both mean creating a tuple.

- Creating an empty tuple
  #+begin_src python :results none
  t = tuple()
  #+end_src

- Creating a tuple from an iterable data structure, like a set, a list, or a string

  #+NAME: tuple-create-from-iterable
  #+begin_src python :results output :exports both
  print("Tuple from list: ", tuple([1, 2, 3, 4]))
  print("Tuple from set: ", tuple({1, 2, 3, 4}))
  print("Tuple from string: ", tuple("1234"))
  #+end_src

  @@latex: \noindent@@ Output:

  #+RESULTS: tuple-create-from-iterable
  : Tuple from list:  (1, 2, 3, 4)
  : Tuple from set:  (1, 2, 3, 4)
  : Tuple from string:  ('1', '2', '3', '4')

- Creating a tuple with predefined items
  #+begin_src python :results none
  t = (1, 2, 3, 4)
  t = (1, 3.14159, "a", True)
  t = (1, )
  t = 1,
  #+end_src

*** Index (~[]~)
- Items in a tuple are in a sequence
- We can identify each item in the tuple with a unique index (a position in the sequence).
- We can index an item from either end of the sequence.
  - Non-negative values: counting from left, starting at 0
  - Negative values: counting from right, starting at -1
- The index operator is always at the end of the expression and is preceded by something, either a variable or a sequence.

We can use ~[]~ to access particular items in a tuple.
#+NAME: tuple-indexing
#+begin_src python :results output :exports both
t = (1, "omg wow", 420.69, False)
print(t[0])
print(t[1])
print(t[-2])
print(t)
print(("hey", 5, True)[0])
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: tuple-indexing
: 1
: omg wow
: 420.69
: (1, 'omg wow', 420.69, False)
: hey

@@latex: \newpage@@

*** Slice (~[:]~)
~[start : end : step]~
- ~start~ is the index of the start of the subsequence.
- ~end~ is the index of the end of a subsequence (not included).
- ~step~ specifies the step size to jump along the sequence.

#+NAME: tuple-slicing
#+begin_src python :results output :exports both
t = (1, "omg wow", 420.69, False)
print(t[1:4])
print(t[::2])
print(t[::-2])
print(t[0:3:-1])
print(("hey", 5, True, "lovely")[2:4])
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: tuple-slicing
: ('omg wow', 420.69, False)
: (1, 420.69)
: (False, 'omg wow')
: ()
: (True, 'lovely')

*** Length (~len~)
#+NAME: length-of-a-tuple
#+begin_src python :results output :exports both
t = (1, "omg wow", 420.69, False)
print(len(t))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: length-of-a-tuple
: 4

*** Concatenation (~+~)
#+NAME: concatenate-tuple
#+begin_src python :results output :exports both
t_1 = (1, "omg wow", 420.69, False)
t_2 = ("Finger licking good!", True, "I'm loving it!")
print(t_1 + t_2)
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: concatenate-tuple
: (1, 'omg wow', 420.69, False, 'Finger licking good!', True, "I'm loving it!")

*** Repeat (~*~)
#+NAME: repeat-tuple
#+begin_src python :results output :exports both
t = (1, "omg wow", 420.69, False)
print(t * 2)
t = (3,)
print(t * 5)
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: repeat-tuple
: (1, 'omg wow', 420.69, False, 1, 'omg wow', 420.69, False)
: (3, 3, 3, 3, 3)

*** Comparison
- The items of a tuple are compared starting from the first item.
- This means for the greater than, or less than operators, the tuple that has the higher value at the front of the tuple is considered to be greater than the tuple with the same value at the back of the tuple.
- The boolean ~True~ is changed into 1 and the boolean ~False~ is changed to 0 comparing tuples.
- For two tuples to be equal, all items in both tuples must be the same, and have the same order.
#+NAME: tuple-comparison
#+begin_src python :results output :exports both
print((4, 3, 2, 1) > (1, 2, 3, 4))
print((4, 3, 2, 1) == (1, 2, 3, 4))
print((True, 3, 2, 1) >= (1, 2, 3, 4))
print((False, 2, 3, 4) <= (1, 2, 3, 4))
print(("a", "tuple", "of", "strings") <= ("string", "tuple"))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: tuple-comparison
: True
: False
: True
: True
: True

*** Membership (~in~)
~a in b~ is True if ~a~ is contained in the tuple ~b~.
#+NAME: tuple-membership
#+begin_src python :results output :exports both
t = (1, "omg wow", 420.69, False)
print(1 in t)
print(420 in t)
print("omg wow" in t)
print("omg" in t)
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: tuple-membership
: True
: False
: True
: False

*** Minimum (~min~)
- Gets the smallest element in the tuple.
- Only applicable to *tuples containing strings only* or *tuples containing numeric values (~int~ and ~float~) and boolean values*.
- The boolean ~True~ is changed into 1 and the boolean ~False~ is changed to 0 when evaluating the minimum of a tuple.

#+NAME: tuple-min
#+begin_src python :results output :exports both
t_1 = (1, 2, 420.69, 699)
t_2 = (1, 2, True, False)
t_3 = ("ooo", "a", "tuple", "of", "Only", "Strings")
print(min(t_1))
print(min(t_2))
print(min(t_3))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: tuple-min
: 1
: False
: Only

*** Maximum (~max~)
- Gets the largest element in the tuple.
- Only applicable to *tuples containing strings only* or *tuples containing numeric values (~int~ and ~float~) and boolean values*.
- The boolean ~True~ is changed into 1 and the boolean ~False~ is changed to 0 when evaluating the maximum of a tuple.

#+NAME: tuple-max
#+begin_src python :results output :exports both
t_1 = (1, 2, 420.69, 699)
t_2 = (1, 2, True, False)
t_3 = ("ooo", "a", "tuple", "of", "Only", "Strings")
print(max(t_1))
print(max(t_2))
print(max(t_3))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: tuple-max
: 699
: 2
: tuple

*** Sum (~sum~)
- Gets the sum of the elements of the tuple.
- Only applicable to tuples containing numeric values (~int~ and ~float~) and boolean values.
- The boolean ~True~ is changed into 1 and the boolean ~False~ is changed to 0 when evaluating the maximum of a tuple.

#+NAME: tuple-sum
#+begin_src python :results output :exports both
t_1 = (1, 2, 420.69, 699)
t_2 = (1, 2, True, False)
print(sum(t_1))
print(sum(t_2))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: tuple-sum
: 1122.69
: 4

*** Immutability
- Tuples are immutable, which means you cannot change a tuple after it has been created.
  #+begin_src python :results none
  t = (1, "omg wow", 420.69, False)
  t[1] = "tuple"  # Error
  #+end_src

- However, you can use it to make another tuple:
  #+NAME: tuple-edit
  #+begin_src python :results output :exports both
  t = (1, "omg wow", 420.69, False)
  new_tuple = t[:1] + ("tuple",) + t[2:]
  print(new_tuple)
  #+end_src

  @@latex: \noindent@@ Output:

  #+RESULTS: tuple-edit
  : (1, 'tuple', 420.69, False)

*** Tuple of tuples
A tuple can be nested inside another tuple.
#+NAME: nested-tuple
#+begin_src python :results output :exports both
t = (1, (1, "a", "tuple", True), 420.69, False)
print(t[1])
print(t[2])
print(t[1][2])
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: nested-tuple
: (1, 'a', 'tuple', True)
: 420.69
: tuple

@@latex: \newpage@@

** Dictionaries (~dict~)
- A dictionary is an associative array, or associative list, or a map.
- You can think of it as a list of pairs.
  - The key, which is first element of the pair, is used to retrieve the second element, which is the value.
- Hence, we map a key to a value in a dictionary.
- The key acts as a "lookup" to find the associated value.
- Just like a dictionary, you look up a word by its spelling to find the associated definition.
- A dictionary can be searched to locate the value associated with a key.
- The key of the dictionary must be immutable, so strings, integers and tuples are allowed, but *lists are NOT*.
- The value can be any Python object.

*** Creation
Constructing a dictionary or initialising a dictionary both mean creating a dictionary.

- Creating an empty dictionary
  #+begin_src python :results none
  dic = dict()
  dic = {}
  #+end_src

- Creating a dictionary with predefined items
  #+begin_src python :results none
  dic = {"omg": "lol"}
  dic = {1: "lol"}
  dic = {5: 42069}
  #+end_src

*** Index (~[]~)
Items in a dictionary can be indexed using its respective key.

We can use ~[]~ to access particular values in a dictionary.
#+NAME: dictionary-indexing
#+begin_src python :results output :exports both
dic = {
    "bill": 25,
    "tax": 3
}
print(dic["bill"])
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: dictionary-indexing
: 25

*** Adding items (~[]~)
Items can also be added to the dictionary using the indexing operator.
#+NAME: add-to-dictionary
#+begin_src python :results output :exports both
dic = {
    "bill": 25,
    "tax": 3
}
dic["petrol"] = 10
print(dic)
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: add-to-dictionary
: {'bill': 25, 'tax': 3, 'petrol': 10}

*** Removing items (~del~)
Items can be removed from the dictionary using ~del~ keyword with the indexing operator.
#+NAME: remove-from-dictionary
#+begin_src python :results output :exports both
dic = {
    "bill": 25,
    "tax": 3
}
del dic["tax"]
print(dic)
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: remove-from-dictionary
: {'bill': 25}

*** Length (~len~)
#+NAME: length-of-a-dictionary
#+begin_src python :results output :exports both
dic = {
    "bill": 25,
    "tax": 3
}
print(len(dic))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: length-of-a-dictionary
: 2

*** Membership (~in~)
~a in b~ is True if the key ~a~ is contained in the dictionary ~b~.
#+NAME: dictionary-membership
#+begin_src python :results output :exports both
dic = {
    "bill": 25,
    "tax": 3
}
print("bill" in dic)
print(25 in dic)
print("3" in dic)
print("tax" in dic)
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: dictionary-membership
: True
: False
: False
: True

@@latex: \newpage@@

*** For loop (~for~)
A ~for~ loop iterates over the *keys* of the dictionary.
#+NAME: dictionary-for-loop
#+begin_src python :results output :exports both
dic = {
    "bill": 25,
    "tax": 3
}
for key in dic:
    print(key)
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: dictionary-for-loop
: bill
: tax

** Integers (~int~)
Integers are like whole numbers, including the negative numbers. They can be negative (-1, -2, -3, etc), positive (1, 2, 3, etc) or zero (0).

** Floats (~float~)
Floats represent real numbers and have a decimal point, like 2.8, 7.1 and 9.0001.

** Boolean (~bool~)
In most computer programming languages, a Boolean data type is a data type with only two possible values, either True or False.

@@latex: \newpage@@

* Python syntax

** Statements
Each line of code in a Python program is called a *statement*. Python interprets and runs the statements one by one.

Python is sensitive to the end of line in text files, which marks the end of a statement. In text editors, we press "Enter".

*** Continuation of a statement
- The symbol "\" is used to continue a statement with the next line so that the two lines can be joined as one statement.
- It improves readability in the text editor.

** Comments
- The pound sign "#" in Python indicates a comment.
- *Anything after "#"* is ignored during interpretation.

@@latex: \newpage@@

** If statements
- A colon must be used to mark the start of a block
- An indentation must be used for the entire block

*** Example
#+begin_src python :results none
a = 5
b = 1
if a > b:
    print("a > b")
#+end_src

*** If-else statements
#+begin_src python :results none
a = 5
b = 1
if a > b:
    print("a > b")
else:
    print("b < a")
#+end_src

*** If-elif-else statements
#+begin_src python :results none
a = 5
b = 10
if a > b:
    print("a > b")
elif a > 4:
    print("a > 4")
else:
    print("b < a")
#+end_src

@@latex: \newpage@@

** While loops
- The ~while~ statement allows repetition of a group of Python code as long as a condition (Boolean expression) is True.
- It is structurally similar to an if statement but repeats the block until the condition becomes False.
- When the condition becomes False, repetition ends and control moves on to the code following the repetition.

*** Syntax
#+begin_src python :results none
count = 0
while count < 10:
    count += 1
#+end_src

** While-else loops (avoid using as much as possible)
- The ~while~ loop can have an associated ~else~ statement.
- The ~else~ block is executed when the loop finishes under normal conditions. It is the last thing the loop does as it exits.
- The ~else~ block is entered after the ~while~ loop's Boolean expression becomes False.
- This occurs even when the expression is initially False and the ~while~ loop has never run.
- It is a handy way to perform some final tasks when the loop ends normally.

*** Syntax
#+begin_src python :results none
count = 0
while count < 10:
    count += 1
else:
    print("Done looping")
#+end_src

** Break statement
- The ~break~ statement can be used to *immediately* exit the execution of the current loop and skip past all the remaining parts of the loop.
- Note that "skip past" also means that the ~break~ statement also *skips* the ~else~ block as well.
- The ~break~ statement is useful for stopping computation when the "answer" has been found or when continuing the computation is otherwise useless.

*** Syntax
#+begin_src python :results none
count = 0
while count < 10:
    count += 1
    if count == 8:
        break

# The else clause is skipped in this case
# as the loop is broken out of when the count hits 8
else:
    print("Done looping")
#+end_src

@@latex: \newpage@@

** Continue statement
- The ~continue~ statement skips some portion of the ~while~ block that we are executing and have control flow back to the beginning of the ~while~ loop.
- Exit early from this iteration of the loop (not the loop itself), and keep executing the ~while~ loop.
- The ~continue~ statement continues with the next iteration of the loop.

*** Syntax
#+begin_src python :results none
count = 0
while count < 10:
    count += 1
    if count == 3:
        print("It's a three!")
        continue

    # This print statement is skipped when the count is 3
    print("count is", count)
#+end_src

@@latex: \newpage@@

** For loops
- For loops have the ability to iterate over the items of any sequence, such as a list or a string.
- Each item in the sequence is assigned to the iterating variable, which can be any variable.
- The ~for~ loop completes when the last of the elements has been assigned to the iterating variable, or when the entire sequence is exhausted.

*** Syntax
#+begin_src python :results none
for i in range(10):
    print("i is", i)

for char in "Hello World!":
    print("Current char is", char)

for drink in ("coffee", "tea", "milo"):
    print("Current drink is", drink)
#+end_src

*** For-else
#+begin_src python :results none
for i in range(10):
    print("i is", i)
else:
    print("Done looping")
#+end_src

*** For-else-break
#+begin_src python :results none
for i in range(10):
    if i == 5:
        break
    print("i is", i)

# This else statement is skipped as
# the loop is broken out of when i is 5
else:
    print("Done looping")
#+end_src

*** For-else-break-continue
#+begin_src python :results none
for i in range(10):
    if i == 5:
        break
    if i == 3:
        print("It's a three!")
        continue

    # This print statement is skipped when i is 3
    print("i is", i)

# This else statement is skipped as
# the loop is broken out of when i is 5
else:
    print("Done looping")
#+end_src

** Pass statement
- The ~pass~ statement has no effect (it does nothing) but it helps in indicating an *empty* statement, suite, or block.
- Use the ~pass~ statement when you have to put something in a statement (syntactically, you cannot leave it blank or Python will complain), but what you really want is nothing.
- Python has the syntactical requirement that code blocks after ~if~, ~for~, ~while~, ~except~, ~def~, ~class~, etc cannot be empty.
- It can be used to *test a statement*, like opening a file or iterating through a collection to see if it works.
- You can also use ~pass~ as a placeholder.

*** Syntax
#+begin_src python :results none
for i in range(10):
    pass
#+end_src

@@latex: \newpage@@

** List comprehension
- List comprehensions are a Python syntactic structure to construct lists concisely.
- The first variable before the ~for~ is what is placed into the list.
- The ~for~ loop is just a regular for loop.
- Any ~for~ loops after the first for loop will be *nested inside* the for loop before it. If there is a ~if~ statement at the end of the previous for loop, the next ~for~ loop will be placed inside the ~if~ statement. (This is absolutely not recommended as it makes code impossible to read.)
- Any ~if~ statements after the ~for~ loop will determine what will be added to the list. Basically, if the item doesn't meet the condition in the ~if~ statement, it's not added to the list.

*** Syntax
#+NAME: list-comprehension-syntax
#+begin_src python :results output :exports both
print([i for i in range(11)])
print([i for i in range(21) if i % 2 == 0])
print([i for i in range(21) if i % 2 == 0 and i >= 10])

# Please don't do this, just use a regular for loop instead
print([x + y for x in range(9) if x % 2 == 0 for y in range(9) if y % 2 != 0])
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: list-comprehension-syntax
: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
: [10, 12, 14, 16, 18, 20]
: [1, 3, 5, 7, 3, 5, 7, 9, 5, 7, 9, 11, 7, 9, 11, 13, 9, 11, 13, 15]

@@latex: \newpage@@

*** Equivalent code using for loops
1. The first list comprehension:
   #+NAME: list-comprehension-equivalent-1
   #+begin_src python :results output :exports both
   l = []
   for i in range(11):
       l.append(i)
   print(l)
   #+end_src

   @@latex: \noindent@@ Output:

   #+RESULTS: list-comprehension-equivalent-1
   : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

2. The second list comprehension:
   #+NAME: list-comprehension-equivalent-2
   #+begin_src python :results output :exports both
   l = []
   for i in range(21):
       if i % 2 == 0:
           l.append(i)
   print(l)
   #+end_src

   @@latex: \noindent@@ Output:

   #+RESULTS: list-comprehension-equivalent-2
   : [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

3. The third list comprehension:
   #+NAME: list-comprehension-equivalent-3
   #+begin_src python :results output :exports both
   l = []
   for i in range(21):
       if i % 2 == 0 and i >= 10:
           l.append(i)
   print(l)
   #+end_src

   @@latex: \noindent@@ Output:

   #+RESULTS: list-comprehension-equivalent-3
   : [10, 12, 14, 16, 18, 20]

   @@latex: \newpage@@

4. The fourth list comprehension:
   #+NAME: list-comprehension-equivalent-4
   #+begin_src python :results output :exports both
   l = []
   for x in range(9):
       if x % 2 == 0:
           for y in range(9):
               if y % 2 != 0:
                   l.append(x + y)
   print(l)
   #+end_src

   @@latex: \noindent@@ Output:

   #+RESULTS: list-comprehension-equivalent-4
   : [1, 3, 5, 7, 3, 5, 7, 9, 5, 7, 9, 11, 7, 9, 11, 13, 9, 11, 13, 15]


** Method in general
#+begin_src python :results none
object.method()
#+end_src

@@latex: \noindent@@ We say that ~object~ is calling the method ~method~.


** Whitespace
Python counts the "Tab", "Space bar" and "Enter" as white spaces.
- The purpose of whitespace is to separate words in a statement.
- For the most part, you can place white spaces anywhere in your program to make the code more readable.

** Indentation
An indentation is a leading whitespace at the start of a statement. In Python, a group of indented statements is called a *suite* or a *block*. A *compound statement* is a set of statements being used as a group.

Purpose of indentation:
- Makes the code more readable
- For grouping, particularly for control flow such as branching and looping

@@latex: \newpage@@

** Modulus operator (Remainder operator) (~%~)
Returns the remainder of the division of the left operand by the right.

*** Syntax
#+begin_src python :results none
x % y
#+end_src

@@latex: \noindent@@ The remainder of ~x/y~.

*** Example
#+NAME: modulus
#+begin_src python :results output :exports both
print(8 % 3)
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: modulus
: 2

@@latex: \newpage@@

** Arithmetic operators

#+ATTR_LATEX: :environment tabular :align |c|m{32em}|
|----------+--------------------------------------------------------------------------------------------------------------------------------|
| Operator | Meaning                                                                                                                        |
|----------+--------------------------------------------------------------------------------------------------------------------------------|
| ~+~      | Add two operands or unary plus                                                                                                 |
|----------+--------------------------------------------------------------------------------------------------------------------------------|
| ~-~      | Subtract the right operand from the left or unary minus                                                                        |
|----------+--------------------------------------------------------------------------------------------------------------------------------|
| ~*~      | Multiply two operands                                                                                                          |
|----------+--------------------------------------------------------------------------------------------------------------------------------|
| ~/~      | Floating point division: divide the left operand by the right one (always results in a ~float~)                                |
|----------+--------------------------------------------------------------------------------------------------------------------------------|
| ~%~      | Modulus: remainder of the division of the left operand by the right                                                            |
|----------+--------------------------------------------------------------------------------------------------------------------------------|
| ~//~     | Floor division (integer division): the resultant value is a whole integer, although the result's type is not necessarily ~int~ |
|----------+--------------------------------------------------------------------------------------------------------------------------------|
| ~**~     | Exponent: the left operant is raised to the power of the right operand                                                         |
|----------+--------------------------------------------------------------------------------------------------------------------------------|

** Augmented assignment operators

#+ATTR_LATEX: :environment tabular :align c|c
| Shortcut | Equivalent  |
|----------+-------------|
| ~x += 2~ | ~x = x + 2~ |
| ~x -= 2~ | ~x = x - 2~ |
| ~x /= 2~ | ~x = x / 2~ |
| ~x *= 2~ | ~x = x * 2~ |
| ~x %= 2~ | ~x = x % 2~ |

** Chained comparisons
In Python, chained comparisons work just like you would expect in a mathematical expression.

*** Examples
- ~0 <= x <= 5~ is the same as ~0 <= x and x <= 5~.
- ~0 <= x <= 5 > 10~ is the same as ~0 <= x and x <= 5 and x > 10~.

@@latex: \newpage@@

** Operator precedence

#+ATTR_LATEX: :environment tabular :align c|c|c|c
| *Precedence* | *Associativity* | *Operator*                     | *Description*               |
|--------------+-----------------+--------------------------------+-----------------------------|
|           18 | Left-to-right   | ~()~                           | Parentheses (grouping)      |
|           17 | Left-to-right   | ~f(args...)~                   | Function call               |
|           16 | Left-to-right   | ~x[index:index]~               | Slicing                     |
|           15 | Left-to-right   | ~x[index]~                     | Indexing an array           |
|           14 | Right-to-left   | ~**~                           | Exponentiation              |
|           13 | Left-to-right   | ~~x~                           | Bitwise not                 |
|           12 | Left-to-right   | ~+x~                           | Positive                    |
|           12 | Left-to-right   | ~-x~                           | Negative                    |
|           11 | Left-to-right   | ~*~                            | Multiplication              |
|           11 | Left-to-right   | ~/~                            | Division                    |
|           11 | Left-to-right   | ~%~                            | Modulo (Remainder operator) |
|           10 | Left-to-right   | ~+~                            | Addition                    |
|           10 | Left-to-right   | ~-~                            | Subtraction                 |
|            9 | Left-to-right   | ~<<~                           | Bitwise left shift          |
|            9 | Left-to-right   | ~>>~                           | Bitwise right shift         |
|            8 | Left-to-right   | ~&~                            | Bitwise AND                 |
|            7 | Left-to-right   | ~^~                            | Bitwise XOR                 |
|            6 | Left-to-right   | \vert                          | Bitwise OR                  |
|            5 | Left-to-right   | ~in~, ~not in~, ~is~, ~is not~ | Membership                  |
|            5 | Left-to-right   | ~<~, ~<=~, ~>~, ~>=~           | Relational                  |
|            5 | Left-to-right   | ~<>~, ~==~                     | Equality                    |
|            5 | Left-to-right   | ~!=~                           | Inequality                  |
|            4 | Left-to-right   | ~not x~                        | Boolean NOT                 |
|            3 | Left-to-right   | ~and~                          | Boolean AND                 |
|            2 | Left-to-right   | ~or~                           | Boolean OR                  |
|            1 | Left-to-right   | ~lambda~                       | Lambda expression           |

@@latex: \newpage@@

* Documentation for Python functions

** Floor division operator (~//~)
The floor division operator takes the floor of the left number divided by the right number. Flooring a number means to round the number down to the integer. For example, flooring 5.987 will result in 5, and flooring -3.14 will result in -4.

*** Syntax
~x // y~

** Modulus operator (remainder operator) (~%~)
The modulus operator takes the remainder of the left number divided by the right number.

*** Syntax
~x % y~

*** Formula used to calculate the remainder
~x % y = x - y * (x // y)~

** ~input~
~input~ is a built-in function in Python to get an input.
- It prints the message string on the screen and waits until the user types anything and presses "Enter".
- It returns a *string* no matter what is given, even a number.

*** Usage
#+begin_src python :results none
user_input = input("Please enter an input: ")
#+end_src

@@latex: \noindent@@ ~user_input~ will be a *string*.

** ~print~
~print~ is another built-in function in Python that displays related messages and data on the shell screen. It uses a *comma* to separate the elements.

#+NAME: print
#+begin_src python :results output :exports both
a = 1
b = 2
print("a is", a, "and b is", b)
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: print
: a is 1 and b is 2

*** ~sep~ parameter (optional)
~sep~ takes a *string* that specifies what *string* to use to separate the objects passed to the function, if there is more than one. It defaults to a space character, " ".

#+NAME: sep
#+begin_src python :results output :exports both
a = 1
b = 2
print("a is", a, "and b is", b, sep=" @ ")
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: sep
: a is @ 1 @ and b is @ 2

*** ~end~ parameter (optional)
~end~ takes a *string* that specifies what the end of the printed string should be. It defaults to a new line "=\n=".

#+NAME: end
#+begin_src python :results output :exports both
print("Hello world!")
print("My first program.")
print("Hello world!", end=" ")
print("My first program.")
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: end
: Hello world!
: My first program.
: Hello world! My first program.

** ~range~
~range([start], end[, step])~
- ~start~ is the starting number of the sequence. The default value is 0.
- ~end~ is the number to generate numbers up to, but not including this number.
- ~step~ is the difference between each number in the sequence. The default value is 1.

*** ~range(end)~
- Python sets ~start~ to 0 and ~step~ to 1.

#+NAME: range-end
#+begin_src python :results output :exports both
print(list(range(11)))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: range-end
: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

*** ~range(start, end)~
- Python sets ~step~ to 1.

#+NAME: range-start-end
#+begin_src python :results output :exports both
print(list(range(1, 11)))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: range-start-end
: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

*** ~range(start, end, step)~

#+NAME: range-start-end-step
#+begin_src python :results output :exports both
print(list(range(1, 11, 2)))
print(list(range(11, 2, -2)))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: range-start-end-step
: [1, 3, 5, 7, 9]
: [11, 9, 7, 5, 3]

** ~ord~
Takes a character as input and returns the Unicode of the character. For standard symbols, this is the same as in ASCII.

#+NAME: ord
#+begin_src python :results output :exports both
print(ord("a"))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: ord
: 97

** ~chr~
Takes an ASCII or UTF-8 code and returns the corresponding character.

#+NAME: chr
#+begin_src python :results output :exports both
print(chr(97))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: chr
: a

** String method: ~string.upper~
This method will output a new string, which is the same as the string on which it was called, except all letters in the string will now be in uppercase.

#+NAME: string-upper
#+begin_src python :results output :exports both
string = "Shouting!"
print(string.upper())
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-upper
: SHOUTING!

** String method: ~string.lower~
This method will output a new string, which is the same as the string on which it was called, except all letters in the string will now be in lowercase.

#+NAME: string-lower
#+begin_src python :results output :exports both
string = "WHISPERING"
print(string.lower())
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-lower
: whispering

** String method: ~string.title~
This method will output a new string, which is the same as the string on which it was called, except that the string will be in title case, which means that every word in the string will be capitalised.

#+NAME: string-title
#+begin_src python :results output :exports both
string = "john f. kennedy"
print(string.title())
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-title
: John F. Kennedy

** String method: ~string.capitalize~
- This method will output a new string, which is the same as the string on which it was called, except that the first letter of the first word of the string will be capitalised.
- Take note that capitalize is using the American spelling with a "z", instead of the British spelling with a "s".

#+NAME: string-capitalise
#+begin_src python :results output :exports both
string = "this is a sentence."
print(string.capitalize())
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-capitalise
: This is a sentence.

** String method: ~string.find~
- This method takes a single character and outputs the *index* of the character (first seen from left to right).
- If the character is not found ~-1~ is returned.

#+NAME: string-find
#+begin_src python :results output :exports both
string = "Find me!"
print(string.find("m"))
print(string.find("a"))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-find
: 5
: -1

** String method: ~string.count~
This method counts the number of occurrences of the substring you pass to the method.

#+NAME: string-count
#+begin_src python :results output :exports both
string = "This is an pretty long sentence."
print(string.count("i"))
print(string.count("t"))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-count
: 2
: 3

** String method: ~string.join~
This method takes a *string* to be joined and outputs a new string where the base string joins the target string.

#+NAME: string-join
#+begin_src python :results output :exports both
string_1 = "1234"
string_2 = "abcd"
print(string_1.join(string_2))
print(string_2.join(string_1))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-join
: a1234b1234c1234d
: 1abcd2abcd3abcd4

@@latex: \newpage@@

** String method: ~string.split~
- This method takes a *string* and generates a list of strings by splitting the string at the given string.
- The default character the string splits at is *whitespace*.
- This method returns a list of strings.

#+NAME: string-split
#+begin_src python :results output :exports both
l = "oooo a list of strings"
print(l.split())
print(l.split("o"))
print(l.split("st"))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-split
: ['oooo', 'a', 'list', 'of', 'strings']
: ['', '', '', '', ' a list ', 'f strings']
: ['oooo a li', ' of ', 'rings']

@@latex: \newpage@@

** String method: ~string.format~
- This method takes any number of arguments and keyword arguments which are substituted into the string that the format method is being called on.
- The string that calls this method should have placeholders inside curly brackets {}.
- The placeholders can be either be identified using named indexes ~{price}~, or numbered indexes ~{0}~, or empty placeholders ~{}~.

#+NAME: string-format
#+begin_src python :results output :exports both
print("{} is a nice number.".format(4200.696969))
print("{meh:.2f} is a meh number.".format(meh=4200.696969))
print("{0:.4f} is a meh number.".format(4200.696969))
print("{:_.6f} is a nice number.".format(4200.696969))
print("{nice:,.6f} is a nice number.".format(nice=4200.696969))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-format
: 4200.696969 is a nice number.
: 4200.70 is a meh number.
: 4200.6970 is a meh number.
: 4_200.696969 is a nice number.
: 4,200.696969 is a nice number.

*** ~:<~ formatting type
Left aligns the result (within the available space given).

#+NAME: string-format-format-type-left-align
#+begin_src python :results output :exports both
print("{:<20} 20 spaces".format(4200.696969))
print("{:*<15} 15 stars".format(4200.696969))
print("{:#<10} 10 hashes".format(4200.696969))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-format-format-type-left-align
: 4200.696969          20 spaces
: 4200.696969**** 15 stars
: 4200.696969 10 hashes


*** ~:>~ formatting type
Right aligns the result (within the available space given).

#+NAME: string-format-format-type-right-align
#+begin_src python :results output :exports both
print("{:>20} 20 spaces".format(4200.696969))
print("{:*>15} 15 stars".format(4200.696969))
print("{:#>10} 10 hashes".format(4200.696969))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-format-format-type-right-align
:          4200.696969 20 spaces
: ****4200.696969 15 stars
: 4200.696969 10 hashes

*** ~:^~ formatting type
Centre aligns the result (within the available space given).

#+NAME: string-format-format-type-centre-align
#+begin_src python :results output :exports both
print("{:^20} 20 spaces".format(4200.696969))
print("{:*^15} 15 stars".format(4200.696969))
print("{:#^10} 10 hashes".format(4200.696969))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-format-format-type-centre-align
:     4200.696969      20 spaces
: **4200.696969** 15 stars
: 4200.696969 10 hashes

*** ~:=~ formatting type
Places the sign to the left most position instead of just left of the number when there is padding.

#+NAME: string-format-format-type-pad-number
#+begin_src python :results output :exports both
print("{:20} 20 spaces".format(-4200.696969))
print("{:=20} 20 spaces".format(-4200.696969))
#+end_src

#+RESULTS: string-format-format-type-pad-number
:         -4200.696969 20 spaces
: -        4200.696969 20 spaces

@@latex: \noindent@@ Output:

#+RESULTS: string-format-format-type-add-sign
: 4200.696969 positive number
: -4200.696969 negative number
: 0 zero

*** ~:+~ formatting type
Use a plus sign or a minus sign to indicate if the result is positive or negative respectively.

#+NAME: string-format-format-type-add-plus-sign
#+begin_src python :results output :exports both
print("{:+} positive number".format(4200.696969))
print("{:+} negative number".format(-4200.696969))
print("{:+} zero".format(0))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-format-format-type-add-plus-sign
: +4200.696969 positive number
: -4200.696969 negative number
: +0 zero

*** ~:-~ formatting type
- Use a minus sign for negative values only.
- This is the default behaviour.

#+NAME: string-format-format-type-add-minus-sign
#+begin_src python :results output :exports both
print("{:-} positive number".format(4200.696969))
print("{:-} negative number".format(-4200.696969))
print("{:-} zero".format(0))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-format-format-type-add-minus-sign
: 4200.696969 positive number
: -4200.696969 negative number
: 0 zero

*** ~:<space>~ formatting type
- Replace the ~<space>~ with an actual space character.
- Use a space to insert an extra space before positive numbers (and a minus sign before negative numbers).

#+NAME: string-format-format-type-add-space
#+begin_src python :results output :exports both
print("{: } positive number".format(4200.696969))
print("{: } negative number".format(-4200.696969))
print("{: } zero".format(0))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-format-format-type-add-space
:  4200.696969 positive number
: -4200.696969 negative number
:  0 zero

*** ~:,~ formatting type
Use a comma as a thousand separator.

#+NAME: string-format-format-type-use-comma
#+begin_src python :results output :exports both
print("{:,} positive number".format(4200.696969))
print("{:,} negative number".format(-4200.696969))
print("{:,} zero".format(0))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-format-format-type-use-comma
: 4,200.696969 positive number
: -4,200.696969 negative number
: 0 zero

*** ~:_~ formatting type
Use an underscore as a thousand separator.

#+NAME: string-format-format-type-use-underscore
#+begin_src python :results output :exports both
print("{:_} positive number".format(4200.696969))
print("{:_} negative number".format(-4200.696969))
print("{:_} zero".format(0))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-format-format-type-use-underscore
: 4_200.696969 positive number
: -4_200.696969 negative number
: 0 zero

*** ~:b~ formatting type
Binary format, only applicable to integers.

#+NAME: string-format-format-type-binary-format
#+begin_src python :results output :exports both
print("{:b} positive number".format(42069))
print("{:b} negative number".format(-42069))
print("{:b} zero".format(0))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-format-format-type-binary-format
: 1010010001010101 positive number
: -1010010001010101 negative number
: 0 zero

*** ~:c~ formatting type
Converts the value into the corresponding Unicode character. Only applicable to positive integers.

#+NAME: string-format-format-type-convert-to-unicode
#+begin_src python :results output :exports both
print("{:c} Unicode character 100".format(100))
print("{:c} Unicode character 69".format(69))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-format-format-type-convert-to-unicode
: d Unicode character 100
: E Unicode character 69

*** ~:d~ formatting type
Decimal format.

#+NAME: string-format-format-type-decimal-format
#+begin_src python :results output :exports both
print("{:d} positive number".format(42069))
print("{:d} negative number".format(-42069))
print("{:d} zero".format(0))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-format-format-type-decimal-format
: 42069 positive number
: -42069 negative number
: 0 zero

*** ~:e~ formatting type
Scientific format, with a lower case e.

#+NAME: string-format-format-type-scientific-format-lower-e
#+begin_src python :results output :exports both
print("{:e} positive number".format(4200.696969))
print("{:.2e} negative number".format(-4200.696969))
print("{:.4e} zero".format(0))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-format-format-type-scientific-format-lower-e
: 4.200697e+03 positive number
: -4.20e+03 negative number
: 0.0000e+00 zero

*** ~:E~ formatting type
Scientific format, with an upper case E.

#+NAME: string-format-format-type-scientific-format-upper-e
#+begin_src python :results output :exports both
print("{:E} positive number".format(4200.696969))
print("{:.2E} negative number".format(-4200.696969))
print("{:.4E} zero".format(0))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-format-format-type-scientific-format-upper-e
: 4.200697E+03 positive number
: -4.20E+03 negative number
: 0.0000E+00 zero

*** ~:f~ formatting type
Fix point number format.

#+NAME: string-format-format-type-fix-point
#+begin_src python :results output :exports both
print("{:f} positive number".format(4200.696969))
print("{:.2f} negative number".format(-4200.696969))
print("{:.4f} zero".format(0))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-format-format-type-fix-point
: 4200.696969 positive number
: -4200.70 negative number
: 0.0000 zero

*** ~:F~ formatting type
Fix point number format, in uppercase format (show inf and nan as INF and NAN).

#+NAME: string-format-format-type-fix-point-upper
#+begin_src python :results output :exports both
print("{:F} positive number".format(4200.696969))
print("{:.2F} negative number".format(-4200.696969))
print("{:.4F} zero".format(0))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-format-format-type-fix-point-upper
: 4200.696969 positive number
: -4200.70 negative number
: 0.0000 zero

*** ~:g~ formatting type
General format.

#+NAME: string-format-format-type-general-format
#+begin_src python :results output :exports both
print("{:g} positive number".format(4200.696969))
print("{:.2g} negative number".format(-4200.696969))
print("{:.4g} zero".format(0))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-format-format-type-general-format
: 4200.7 positive number
: -4.2e+03 negative number
: 0 zero

*** ~:G~ formatting type
General format (using an upper case E for scientific notations).

#+NAME: string-format-format-type-general-format-upper
#+begin_src python :results output :exports both
print("{:G} positive number".format(4200.696969))
print("{:.2G} negative number".format(-4200.696969))
print("{:.4G} zero".format(0))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-format-format-type-general-format-upper
: 4200.7 positive number
: -4.2E+03 negative number
: 0 zero

*** ~:o~ formatting type
Octal format, only applicable to integers.

#+NAME: string-format-format-type-octal-format
#+begin_src python :results output :exports both
print("{:o} positive number".format(42069))
print("{:o} negative number".format(-42069))
print("{:o} zero".format(0))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-format-format-type-octal-format
: 122125 positive number
: -122125 negative number
: 0 zero

*** ~:x~ formatting type
Hex format, lowercase.

#+NAME: string-format-format-type-hex-format-lower
#+begin_src python :results output :exports both
print("{:x} positive number".format(42069))
print("{:x} negative number".format(-42069))
print("{:x} zero".format(0))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-format-format-type-hex-format-lower
: a455 positive number
: -a455 negative number
: 0 zero

*** ~:X~ formatting type
Hex format, uppercase.

#+NAME: string-format-format-type-hex-format-upper
#+begin_src python :results output :exports both
print("{:X} positive number".format(42069))
print("{:X} negative number".format(-42069))
print("{:X} zero".format(0))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-format-format-type-hex-format-upper
: A455 positive number
: -A455 negative number
: 0 zero

*** ~:n~ formatting type
Number format.

#+NAME: string-format-format-type-number-format
#+begin_src python :results output :exports both
print("{:n} positive number".format(4200.696969))
print("{:n} negative number".format(-4200.696969))
print("{:n} zero".format(0))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-format-format-type-number-format
: 4200.7 positive number
: -4200.7 negative number
: 0 zero

*** ~:%~ formatting type
Percentage format.

#+NAME: string-format-format-type-percentage-format
#+begin_src python :results output :exports both
print("{:%} positive number".format(4200.696969))
print("{:.2%} negative number".format(-4200.696969))
print("{:.4%} zero".format(0))
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: string-format-format-type-percentage-format
: 420069.696900% positive number
: -420069.70% negative number
: 0.0000% zero

** List method: ~list.append~
- This method takes an element, which can be any Python object, and adds it to the end of the list.
- Note that this method *changes the list* in place and does *not* return any value.
#+NAME: list-append
#+begin_src python :results output :exports both
l = [1, "omg wow", 420.69, False]
l.append("lol")
print(l)
l.append(True)
print(l)
l.append(69)
print(l)
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: list-append
: [1, 'omg wow', 420.69, False, 'lol']
: [1, 'omg wow', 420.69, False, 'lol', True]
: [1, 'omg wow', 420.69, False, 'lol', True, 69]

@@latex: \newpage@@

** List method: ~list.extend~
- This method takes a *list* and adds the elements of the given list to the end of the original list.
- This method cannot take an element to add to the back of the original list, use ~list.append~ for that.
- Using this method to add a string to the list will add all the characters in the string into the list instead of the string as one item.
- Note that this method *changes the list* in place and does *not* return any value.

#+NAME: list-extend
#+begin_src python :results output :exports both
l_1 = [1, "omg wow", 420.69, False]
l_2 = ["extended l_1 hehe", "lovely", 6969, True]
l_1.extend(l_2)
print(l_1)
l_1.extend(5)    # Error
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: list-extend
: [1, 'omg wow', 420.69, False, 'extended l_1 hehe', 'lovely', 6969, True]

** List method: ~list.pop~
- This method takes an index and removes the item corresponding to that index from the list.
- Note that this method *changes the list* in place and does *not* return any value.
#+NAME: list-pop
#+begin_src python :results output :exports both
l = [1, "omg wow", 420.69, False]
l.pop(2)
print(l)
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: list-pop
: [1, 'omg wow', False]

** List method: ~list.insert~
- This method takes an index and an element, which can be any Python object, and adds the element at the given index in the list.
- The element that was in the given index will be pushed back.
- Essentially, the given index will be the same index you can use to get the added element back from the list.
- Note that this method *changes the list* in place and does *not* return any value.

#+NAME: list-insert
#+begin_src python :results output :exports both
l = [1, "omg wow", 420.69, False]
l.insert(3, 6969)
print(l)
print(l[3])
l.insert(0, "I'm at the front")
print(l)
print(l[0])
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: list-insert
: [1, 'omg wow', 420.69, 6969, False]
: 6969
: ["I'm at the front", 1, 'omg wow', 420.69, 6969, False]
: I'm at the front

** List method: ~list.remove~
- This method takes an element and removes it from the list.
- Note that this method *changes the list* in place and does *not* return any value.

#+NAME: list-remove
#+begin_src python :results output :exports both
l = [1, "omg wow", 420.69, False]
l.remove(420.69)
print(l)
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: list-remove
: [1, 'omg wow', False]

** List method: ~list.sort~
- This method sorts the list lexicographically.
- This means that everything is converted to a number if possible and the list can only be either a *list of strings* or a *list of numeric (~int~ and ~float~) and boolean values*.
- Strings will be compared using their ASCII character code.
- The boolean ~True~ is changed into 1 and the boolean ~False~ is changed to 0 when sorting a list.
- Note that this method *changes the list* in place and does *not* return any value.

#+NAME: list-sort
#+begin_src python :results output :exports both
l = [1, True, 420.69, False]
l.sort()
print(l)
l = ["ooo", "a", "list", "of", "Only", "Strings"]
l.sort()
print(l)
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: list-sort
: [False, 1, True, 420.69]
: ['Only', 'Strings', 'a', 'list', 'of', 'ooo']

** List method: ~list.reverse~
- This method reverses the list in place.
- This means that the method will *change the list* in place and *not* return any value.
#+NAME: list-reverse
#+begin_src python :results output :exports both
l = [1, "omg wow", 420.69, False]
l.reverse()
print(l)
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: list-reverse
: [False, 420.69, 'omg wow', 1]

** Dictionary method: ~dict.items~
This method returns all the key value pairs in a list-like structure called ~dict_items~, containing the key value pairs as tuples.
#+NAME: dict-items
#+begin_src python :results output :exports both
dic = {
    "bill": 25,
    "tax": 3
}
print(dic.items())
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: dict-items
: dict_items([('bill', 25), ('tax', 3)])

** Dictionary method: ~dict.keys~
This method returns all the keys of the dictionary in a list-like structure called ~dict_keys~.
#+NAME: dict-keys
#+begin_src python :results output :exports both
dic = {
    "bill": 25,
    "tax": 3
}
print(dic.keys())
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: dict-keys
: dict_keys(['bill', 'tax'])

** Dictionary method: ~dict.values~
This method returns all the values of the dictionary in a list-like structure called ~dict_values~.
#+NAME: dict-values
#+begin_src python :results output :exports both
dic = {
    "bill": 25,
    "tax": 3
}
print(dic.values())
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: dict-values
: dict_values([25, 3])

** Dictionary method: ~dict.clear~
- This method clears the dictionary, which means the dictionary becomes an empty dictionary again.
- This method *changes* the dictionary in place and *does not* return any value.
#+NAME: dict-clear
#+begin_src python :results output :exports both
dic = {
    "bill": 25,
    "tax": 3
}
dic.clear()
print(dic)
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: dict-clear
: {}

** Dictionary method: ~dict.update~
- This method takes a dictionary and updates the original dictionary with the keys and values from the new dictionary.
- The *value in the new dictionary* is used if the new dictionary also has keys that are in the original dictionary
- This method *changes* the dictionary in place and *does not* return any value.
#+NAME: dict-update
#+begin_src python :results output :exports both
dic = {
    "bill": 25,
    "tax": 3
}
new_dic = {
    "bill": 50,
    "petrol": 20
}
print(dic)
#+end_src

@@latex: \noindent@@ Output:

#+RESULTS: dict-update
: None
: {'bill': 50, 'tax': 3, 'petrol': 20}

@@latex: \newpage@@

* ASCII Table

#+ATTR_LATEX: :environment longtable
| DEC | OCT | HEX |      BIN | Symbol | Description                            |
|-----+-----+-----+----------+--------+----------------------------------------|
|  32 | 040 |  20 | 00100000 | SP     | Space                                  |
|  33 | 041 |  21 | 00100001 | !      | Exclamation mark                       |
|  34 | 042 |  22 | 00100010 | "      | Double quotes (or speech marks)        |
|  35 | 043 |  23 | 00100011 | #      | Number sign                            |
|  36 | 044 |  24 | 00100100 | $      | Dollar                                 |
|  37 | 045 |  25 | 00100101 | %      | Per cent sign                          |
|  38 | 046 |  26 | 00100110 | &      | Ampersand                              |
|  39 | 047 |  27 | 00100111 | '      | Single quote                           |
|  40 | 050 |  28 | 00101000 | (      | Open parenthesis (or open bracket)     |
|  41 | 051 |  29 | 00101001 | )      | Close parenthesis (or close bracket)   |
|  42 | 052 |  2A | 00101010 | *      | Asterisk                               |
|  43 | 053 |  2B | 00101011 | +      | Plus                                   |
|  44 | 054 |  2C | 00101100 | ,      | Comma                                  |
|  45 | 055 |  2D | 00101101 | -      | Hyphen-minus                           |
|  46 | 056 |  2E | 00101110 | .      | Period, dot or full stop               |
|  47 | 057 |  2F | 00101111 | /      | Slash or divide                        |
|  48 | 060 |  30 | 00110000 | 0      | Zero                                   |
|  49 | 061 |  31 | 00110001 | 1      | One                                    |
|  50 | 062 |  32 | 00110010 | 2      | Two                                    |
|  51 | 063 |  33 | 00110011 | 3      | Three                                  |
|  52 | 064 |  34 | 00110100 | 4      | Four                                   |
|  53 | 065 |  35 | 00110101 | 5      | Five                                   |
|  54 | 066 |  36 | 00110110 | 6      | Six                                    |
|  55 | 067 |  37 | 00110111 | 7      | Seven                                  |
|  56 | 070 |  38 | 00111000 | 8      | Eight                                  |
|  57 | 071 |  39 | 00111001 | 9      | Nine                                   |
|  58 | 072 |  3A | 00111010 | :      | Colon                                  |
|  59 | 073 |  3B | 00111011 | ;      | Semicolon                              |
|  60 | 074 |  3C | 00111100 | <      | Less than (or open angled bracket)     |
|  61 | 075 |  3D | 00111101 | =      | Equals                                 |
|  62 | 076 |  3E | 00111110 | >      | Greater than (or close angled bracket) |
|  63 | 077 |  3F | 00111111 | ?      | Question mark                          |
|  64 | 100 |  40 | 01000000 | @      | At sign                                |
|  65 | 101 |  41 | 01000001 | A      | Uppercase A                            |
|  66 | 102 |  42 | 01000010 | B      | Uppercase B                            |
|  67 | 103 |  43 | 01000011 | C      | Uppercase C                            |
|  68 | 104 |  44 | 01000100 | D      | Uppercase D                            |
|  69 | 105 |  45 | 01000101 | E      | Uppercase E                            |
|  70 | 106 |  46 | 01000110 | F      | Uppercase F                            |
|  71 | 107 |  47 | 01000111 | G      | Uppercase G                            |
|  72 | 110 |  48 | 01001000 | H      | Uppercase H                            |
|  73 | 111 |  49 | 01001001 | I      | Uppercase I                            |
|  74 | 112 |  4A | 01001010 | J      | Uppercase J                            |
|  75 | 113 |  4B | 01001011 | K      | Uppercase K                            |
|  76 | 114 |  4C | 01001100 | L      | Uppercase L                            |
|  77 | 115 |  4D | 01001101 | M      | Uppercase M                            |
|  78 | 116 |  4E | 01001110 | N      | Uppercase N                            |
|  79 | 117 |  4F | 01001111 | O      | Uppercase O                            |
|  80 | 120 |  50 | 01010000 | P      | Uppercase P                            |
|  81 | 121 |  51 | 01010001 | Q      | Uppercase Q                            |
|  82 | 122 |  52 | 01010010 | R      | Uppercase R                            |
|  83 | 123 |  53 | 01010011 | S      | Uppercase S                            |
|  84 | 124 |  54 | 01010100 | T      | Uppercase T                            |
|  85 | 125 |  55 | 01010101 | U      | Uppercase U                            |
|  86 | 126 |  56 | 01010110 | V      | Uppercase V                            |
|  87 | 127 |  57 | 01010111 | W      | Uppercase W                            |
|  88 | 130 |  58 | 01011000 | X      | Uppercase X                            |
|  89 | 131 |  59 | 01011001 | Y      | Uppercase Y                            |
|  90 | 132 |  5A | 01011010 | Z      | Uppercase Z                            |
|  91 | 133 |  5B | 01011011 | [      | Opening bracket                        |
|  92 | 134 |  5C | 01011100 | \      | Backslash                              |
|  93 | 135 |  5D | 01011101 | ]      | Closing bracket                        |
|  94 | 136 |  5E | 01011110 | ^      | Caret - circumflex                     |
|  95 | 137 |  5F | 01011111 | _      | Underscore                             |
|  96 | 140 |  60 | 01100000 | `      | Grave accent                           |
|  97 | 141 |  61 | 01100001 | a      | Lowercase a                            |
|  98 | 142 |  62 | 01100010 | b      | Lowercase b                            |
|  99 | 143 |  63 | 01100011 | c      | Lowercase c                            |
| 100 | 144 |  64 | 01100100 | d      | Lowercase d                            |
| 101 | 145 |  65 | 01100101 | e      | Lowercase e                            |
| 102 | 146 |  66 | 01100110 | f      | Lowercase f                            |
| 103 | 147 |  67 | 01100111 | g      | Lowercase g                            |
| 104 | 150 |  68 | 01101000 | h      | Lowercase h                            |
| 105 | 151 |  69 | 01101001 | i      | Lowercase i                            |
| 106 | 152 |  6A | 01101010 | j      | Lowercase j                            |
| 107 | 153 |  6B | 01101011 | k      | Lowercase k                            |
| 108 | 154 |  6C | 01101100 | l      | Lowercase l                            |
| 109 | 155 |  6D | 01101101 | m      | Lowercase m                            |
| 110 | 156 |  6E | 01101110 | n      | Lowercase n                            |
| 111 | 157 |  6F | 01101111 | o      | Lowercase o                            |
| 112 | 160 |  70 | 01110000 | p      | Lowercase p                            |
| 113 | 161 |  71 | 01110001 | q      | Lowercase q                            |
| 114 | 162 |  72 | 01110010 | r      | Lowercase r                            |
| 115 | 163 |  73 | 01110011 | s      | Lowercase s                            |
| 116 | 164 |  74 | 01110100 | t      | Lowercase t                            |
| 117 | 165 |  75 | 01110101 | u      | Lowercase u                            |
| 118 | 166 |  76 | 01110110 | v      | Lowercase v                            |
| 119 | 167 |  77 | 01110111 | w      | Lowercase w                            |
| 120 | 170 |  78 | 01111000 | x      | Lowercase x                            |
| 121 | 171 |  79 | 01111001 | y      | Lowercase y                            |
| 122 | 172 |  7A | 01111010 | z      | Lowercase z                            |
| 123 | 173 |  7B | 01111011 | {      | Opening brace                          |
| 124 | 174 |  7C | 01111100 | \vert  | Vertical bar                           |
| 125 | 175 |  7D | 01111101 | }      | Closing brace                          |
| 126 | 176 |  7E | 01111110 | ~      | Equivalency sign - tilde               |
| 127 | 177 |  7F | 01111111 | DEL    | Delete                                 |
