#+TITLE: CC0006 Sustainability Cheat Sheet
#+AUTHOR: Hankertrix
#+STARTUP: showeverything
#+OPTIONS: toc:2

* Definitions

** Sustainability
The ability for something to sustain itself.

** Sustainable development
- Sustainable development is development that meets the needs of the present without compromising the ability of future generations to meet their own needs.
- Sustainable development aims for a world in which:
  - Economic growth is widespread.
  - Extreme poverty is eradicated.
  - Community is strengthened through relevant policies that promote social trust and equal opportunities for everyone.
  - The environment is protectued from human-induced degradation.

*** Necessary conditions to achieve sustainable development
1. We need to know what the needs of the present are.
2. We need to know the needs and abilities of future generations.
3. How our actions are affecting the world of the future.
4. We need to decide on ways to change, and implement those changes.

*** Goals
1. Economic development
2. Social Inclusion
3. Environmental sustainability

** Multidisciplinary
The additive knowledge of different disciplines.

** Interdisciplinarity
The integration and synthesis of different disciplines.

** Transdisciplinarity
This refers to approaches that go across, between, and beyond disciplines.

** Circular economy
The circular economy is based on three principles, namely:
1. Eliminate waste and pollution
2. Circulate products and materials
3. Regenerate nature

Some ideas include having waste build capital (make money) instead of reducing it, such as using safe and compostable materials that can help grow more food. Another is to have a return-and-renew kind of product cycle instead of a buy-and-throw-away one.

The circular economy replaces the concept of end-of-life materials, like food products, with reusing or recycling in both the production and consumption of the products.

** Poverty
Poverty, in the sustainable development context, not only implies a lack of income and productive resources to ensure sustainable living. It also implies hunger and malnourishment, social discrimination, exclusion, and the lack of participation in decision-making.

** Purchasing Power Parity (PPP)
Purchasing Power Parity (PPP) is a theoretical exchange rate at which you can buy the same amount of goods and services with another currency. An example is that if a burger in London costs £2 while the same burger costs S$4 in Singapore, it would imply a PPP exchange rate of £1 to S$2.

** Official Development Assistance (ODA)
Government aid that is mainly donated by *high-income countries* promotes and specifically targets the economic development and welfare of developing countries. It is mainly used for economic development in poor countries, like to build capital or capacity. Some examples of this are paving roads, building power grids, clinics and schools, as well as providing training and salaries for teachers and healthcare workers.

Official Development Assistance came into existence around 1970, and the goal was that high-income countries would donate around 1% of their GDP to help lower-income countries. 70% of it was intended to come mainly through government-to-government grants and low-interest loans. The remaining 30% was intended to come through private contributions, such as corporations, foundations and charitable organisations.

An all-time high ODA was mobilised in 2021, about 179 billion US dollars, which was around 4.4% higher than the donations received in 2020. However, the ODA is still significantly less than the intended amount. The actual intended ODA in 2021 was expected to be about $280 billion US dollars.

*** How does it work?
- Foreign aid cannot be a long-term way of life in developing countries.
- It is a temporary helping hand to push poor countries on the ladder of economic development so that they can self-sustain their growth for the longer term.
- Once these countries reach a certain level of economic growth, they will no longer need financial help.
- China and Korea are examples of this process as they heavily relied on foreign aid in the past, then progressively graduated from aid and have recently significant donor countries themselves.

*** Distributing foreign aid
- Project-based approaches such as financing a local business, building a well, or providing uniforms so the children can attend school. Public health aid is also widely supported, such as offering vaccinations, or developing cheap and effective drugs to treat malaria and other similar diseases in low-income countries.
- Observing the development effects of various projects and practices to then decide which ones to adopt and which ones to discard.

*** Effectiveness of ODA
- ODA has been the most stable external resource for developing countries in the last few decades.
- It has successfully helped countries control AIDS, malaria and tuberculosis, and lowered the mortality rate of children and mothers during pregnancy.

** Gender pay gap
The gender pay gap is the average gap between men's and women's wages and salaries, before or after controlling for the type of work, the level of qualification and some other relevant factors.

** Environmental inequality
Environmental inequality is the uneven exposure to environmental risks and hazards, often coupled with the systematic exclusion of people from environmental decision-making processes.

Environmental inequality is often invisible, and has been all too easy for politicians to ignore.

*** Possible solutions in the context of Singapore
- Changing mindsets:
  Changing some policies to accommodate the changing demographics of Singapore or enhancing the existing social structures are insufficient in addressing environmental inequality, we need to fundamentally change our mindset about poverty and inequality.

- Learning from Sweden:
  The experience of many northern European countries, particularly Scandinavian countries, demonstrates that strong welfare states can see high levels of inclusive growth.

- More public debate:
  We need to resist the inner urge to define and explain away inequality. We should instead make a conscious effort to move beyond defensiveness and ideology.

** Food security
Food security exists when people when all people at all times have physical and economic access to sufficient, safe and nutritious food that meets their dietary needs and food preferences for an active and healthy life.

*** Stability
Stability refers to a secure population, household or individual access to adequate food at all times, protected from sudden shocks or cyclical events that can threaten the availability of and access to food resources.

*** Utilisation
Utilisation refers to the utilisation of food in conjunction with adequate diet, clean water, sanitation and healthcare to a state of nutritional well-being, demonstrating the importance of non-food inputs for food security.

*** Food availability
Food availability refers to the availability of sufficient quantities and appropriate quality of food products that are either locally produced or supplied by imports, including food aid.

*** Food accessibility
Food accessibility refers to adequate access to food resources for a nutritious diet.

** Global food system
The global food system is the sum of actors, sectors and interactions along the food value chains, which includes research and development, input supply, production, harvesting, storage, transportation, processing, retailing, wholesaling, preparation, consumption and the disposal of food.

** Economy
The economy constitutes of two simple blocks, production and consumption. Minerals and other natural resources from the environment are used for production. The waste material from our consumption is then sent back to the environment. Hence, we are completely dependent on the environment for our survival on Earth.

** Greenhouse effect
The greenhouse effect is a natural process tha makes life possible on Earth. The effect is as follows:
- Some solar radiation is reflected by the Earth and the atmosphere.
- Most radiation is absorbed by the Earth's surface and warms it.
- Some of the infrared radiation passes through the atmosphere, and some is absorbed and re-emitted in all directions by greenhouse gas molecules. The effect of this is to warm the Earth's surface and the lower atmosphere.
- Infrared radiation is emitted by the Earth's surface.

Generally, the greater the amount of greenhouse gases in the atmosphere, the warmer the planet is.

*** Ramping up the greenhouse effect
- Burning excessive amounts of fossil fuels adds an excessive amount of carbon dioxide to the air.
- Greenhouse gases are trapping much more heat than required, which increases the average global temperature.

** Energy poverty
Energy poverty is the lack of access to sustainable and modern energy services and products.


* The complexity of sustainable development
- It is a long range of interconnected but unique problems.
- There are multiple causes, hard to define "the problem".
- There is no generalisable solution, and there's no definite right or wrong. Instead, there is only better or worse.
- The solutions tend to ramify throughout the system.
- The solutions can take a long time to evaluate.


* Perspectives of sustainable development

** Society perspective
- Environmental justice and unequal distribution of climate change effects
- Understanding human behaviour to implement changes for sustainability.
- Risk of political conflict or humanitarian crises due to climate change or environmental degradation

*** In Singapore
- Additional 200 hectares of nature parks for citizens and wildlife to enjoy
- Planting one million trees across the island to absorb CO_{2}, provide shade, and reduce temperatures.
- Programmes to reduce human-wildlife conflicts.

** Economic perspective
- Sustainability accountants are needed for sustainable capital investments
- Integration of financial decision-making and sustainability work
- Stating potential social and environmental impact on profits
- Effect on valuation and investment

** Environmental perspective
- Laws of nature govern processes of climate change and environmental degradation
- Intrinsic value of nature
- Human dependence on natural resources
- Natural climate solutions, such as using mangrove forests to protect against storms and floods
- Tree planting

*** In Singapore
- More green spaces
- Education and appreciation for local wildlife
- Limit pollution of water
- Conservation initiatives


* Goal of having no poverty

** Extreme poverty
- In 2015, more than 734 million people lived in extreme poverty (making $1.90 a day or less), which is about 10% of the world's population.
- More than 160 million children are at risk of continuing to live in extreme poverty.
- We cannot think about sustainable development when there are still millions of people who are living in extreme poverty in some parts of the world.
- As such, eradicating poverty everywhere, in all forms, is the first of the 17 sustainable development goals adopted by the United Nations.

** Progress on poverty

*** Positive
- The number of people living in extreme poverty has been declining gradually in the last three decades.
- In 1990, about 1.9 billion people were living in extreme poverty, which is about 36% of the world's population back then.
- In 2010, this number went down to about 1 billion, or about 16% of the world's population.
- Between 2015 and 2017, there has been a substantial decrease in the poverty rate worldwide.
- About 10% of the world's population is presently living in poverty.

*** Negative
- The rate of poverty decline has significantly slowed in recent times.
- The Covid-19 pandemic has led to the first rise in extreme poverty in three decades.
- Estimates suggest that the pandemic has pushed an additional 199-124 million people back into extreme poverty in 2020.
- The pandemic caused income and job losses, and work slowdowns have damaged poor households.

** New target
The World Bank now targets to have no more than 3% of the world's population living under the poverty line by 2030.

** Measuring poverty
- Global institutions calculate the poverty line by considering the cost of food, clothing, healthcare and shelter and reach a final amount if you earn less than that amount, then you can't afford basic human needs and are thus considered poor.
- Professor Jeffrey Sachs, a world-renowned economist, suggests that the ideal definition of poverty should be measured by people's ability to meet a broad range of basic needs that are needed not only for survival, but also for human dignity, such as food, clean water, sanitation, shelter, clothing, access to healthcare, basic education, transport, energy and connectivity.
- To calculate the international poverty line, the World Bank uses the average of the national poverty line in 15 very poor countries, converted to PPP estimates.
- Every country has *its own* poverty line.
- The international poverty line is currently US$2.15 a day.

** Profile of the global poor

*** Regions
- The majority of the global poor are located in Sub-Saharan Africa and in South Asia.
- In South Asia, the poverty rate in 2010 was as high as 30%, but the number has rapidly declined in recent times.
- However, in Sub-Saharan Africa, the poverty line sometimes grows.
- The extreme poverty rate in the Middle East and North Africa has increased from about 2.3% in 2013 to about 10% in 2018.
- East Asia has achieved one of the fastest economic growths, and hence has seen one of the fastest decline in the rates of extreme poverty in any region. Most of this decline came from China.
- Sub-Saharan Africa and South Asia need a breakthrough, as they house about 76% of the world's extremely poor.

*** Characteristics
- The poor are predominantly rural, young, and under-educated. Women are over-represented among the poor globally.
- In 2018, half of the poor were children younger than 15.

** Lifting Sub-Saharan Africa out of poverty
The way to lift Sub-Saharan Africa out of poverty is to increase overall economic growth.

*** Farm productivity
- Small farmers in Sub-Saharan Africa achieve an average yield of about half a ton to one ton of grain per hectare. This is extremely low as other countries in the developing world can achieve 4 to 5 times it.
- The reason for this is that the Sub-Saharan African farmers are simply too poor to spend money on soil refilling. They cannot afford to buy the nitrogen, potassium and phosphorus necessary for decent crop yields. This results in a poverty trap where they can't afford to acquire the resources to get decent crop yields and hence remain poor.
- Hence, a high priority for Sub-Saharan Africa is to roll out government programmes that can help the poorest farmers get the resources that they need for farming. Once they have higher crop yields and hence higher income, they will be able to acquire these resources on their own.

*** Other changes
- Vital investments are needed to build up critical infrastructure, such as roads, rails, power, ports and communication networks.
- Mass electrification is needed.
- A lot of investment is needed in health and education.
- These investments might not lead to the desired changes if the population of Sub-Saharan Africa keeps growing.
- As such, lowering the fertility rate should also be another priority.

** Lifting South Asia out of poverty

*** Current problems
- South Asia has a huge population and hence high population density.
- South Asia also has the worst levels of human deprivation in the world.
- India's child malnutrition levels are nearly double that of Sub-Saharan Africa.
- Extremely low enrollment in primary education, gender disparity and high levels of corruption are some issues that need an immediate fix.


* Social inclusion
Social inclusion is a vision for a discrimination-free society where every individual has equal rights and opportunities, specifically the opportunities to fulfil their economic potential.

All individuals are interconnected within a wider social system with harmoniously maintained relationships. Society has respect for human rights, cultural diversity and democratic governance. Most importantly, there is some degree of social mobility, which means a child born into poverty doesn't have to end up in poverty.

** Factors of social exclusion
- Income
- Class
- Gender
- Race
- Ethnicity
- Religion
- Sexual orientation

*** Example
- Massive poverty and exclusion faced by Native Americans in the United States, or the Maoris in New Zealand.

** UN goals
1. A peaceful and inclusive society for all
2. Fewer inequalities
3. Safe, resilient and sustainable cities
4. Inclusive and equitable education for all
5. Healthy lives and well-being for all
6. No gender inequality

** Measuring income inequality
- The Gini coefficient is a statistical measure of income inequality within a country or social group. The index measures income distribution across a population and varies from 0 to 1, where 0 represents perfect equality while 1 represents perfect inequality.
- South Africa ranks as the country with the lowest level of income equality in the world. The richest 10% hold 70% of the wealth of the country, while more than half of South Africa live in poverty.
- The United States and several South American countries have some of the highest levels of income inequality, but Canada is an exception.
- Western, Central and Eastern Europe enjoy relatively equal income.
- Some of the world's poorest countries have some of the highest Gini coefficients, like the Central African Republic, which is among the world's poorest countries, has a Gini coefficient of about 0.61.
- However, the Gini coefficient doesn't tell anything about a country's overall wealth, income, quality of life, or general economic well-being.
- This means that high-income and low-income countries can have the same Gini coefficient if income is distributed equally within them.
- For example, the United States and Turkey have the same Gini coefficient of about 0.39, but the US has a GDP per capita of about eight times that of Turkey.

** Forces of income inequality
- Racial discrimination
- Social discrimination
- Ethnic discrimination
- Gender discrimination
- Religious discrimination
- Discrimination based on sexual orientation
- Skills, education and globalisation
- Technology and digital revolution
- Political influence and economic winners
- Redistribution policies

*** Examples
- Black workers in the United States earn 30% less than their white counterparts.
- Women in Singapore earn 6% less than men.
- A person with a higher level of education often has more advanced skills that few others can offer, which leads to higher wages. The returns on education have increased strikingly in recent times, which leaves the less-educated behind.
- Competition from emerging economies like China is further reducing prospects for workers without advanced skills in developed countries.
- The recent digital revolution has led to the increased use of data science, robotics, artificial intelligence and several other information technologies, which creates enormous amounts of wealth for people with such skills, or for the people who use their existing wealth to invest in such technologies and related infrastructure. This also eliminates middle-skill jobs, or jobs requiring repetitive tasks, such as packaging or basic manufacturing.
- Wealthy people use the power of their wealth to gain political influence to influence policy in their favour, such as tax breaks, subsidies or favourable regulatory changes. With such policies, they earn even more money. There are now more ways in the social media age to gain political influence and eventually gain more wealth.
- Redistribution policies like progressive taxes and social transfers are used in an attempt to reduce inequality. An example of social transfer is public retirement benefits. However, a lot of advanced countries need to be using these tools more effectively as high-income corporations are enjoying even lower effective tax rates.

** How to reduce income inequality?
- Customised policies and specific reforms such as policies to establish social mobility can help, so that kids that grow up poor don't become poor adults.
- Tax on the rich needs to be increased.
- Review tax breaks and offshore tax havens for wealthy people.
- Have greater social support for low-income households.
- Increase training, re-skilling and educational opportunities for the poor.
- Implement pensions, unemployment child benefits for the needy.

** Gender inequality
- It has existed for a long time in most societies around the world.
- Men have been in the paid labour force, while women carried out farm labour or home-based production while also raising the children.
- Women's participation in paid work has significantly increased, but the inequality remains in the form of a gender pay gap.
- Gender inequality is the highest in Asia, the Middle East and North Africa. Women in Asia are only employed about 50% of the time and earn 50% - 52% of what their male counterparts earn.
- Sub-Saharan Africa shows a very high employment ratio of women, but the earning ratio of women is very low.
- Women do three times as much unpaid care work as men.
- Increasing automation is also threatening more jobs that women are in due to their nature.
- Globally, women's jobs are 1.8 times more vulnerable to crises like COVID-19 than men's jobs.
- Almost 1 in 3 women have been subjected to physical, sexual or non-sexual violence at least one time in their lifetime.

** Measuring gender inequality
- The Gender Inequality Index (GII) focuses on analysing women's reproductive health, labour market participation and empowerment in the form of women's participation in parliament and higher education.
- The Gender Development Index (GDI) focuses on life expectancy, education and income to understand if such achievements are distributed evenly between men and women.

** Goals to eradicate gender equality
- End all forms of discrimination against all women and girls everywhere.
- Eliminate all forms of violence against all women and girls in the public and private spheres.
- Eliminate all harmful practices, such as child, early and forced marriage.
- Recognise and value unpaid care and domestic work through the provision of public services, etc.
- Ensure women's full and effective participation and equal opportunities for leadership at all levels of decision-making.
- Ensure universal access to sexual and reproductive health and reproductive rights.

** Possible solutions for gender inequality
- Legal reforms to give equal rights to women in property matters, ownership of a business, participation in education, politics, and other significant matters and areas.


* Food security
- In 2020, there were 2.37 billion people worldwide who were lacking food or unable to eat a healthy diet regularly.
- 149.2 million children under 5 are stunted, which makes up 22% of children worldwide.
- 45.4 million children under 5 suffer from wasting, which makes up 6.7% of children worldwide.
- 38.9 million children under 5 are overweight, which makes up 5.7% of children worldwide.
- The number of undernourished people increased from 607 million people in 2014 to 720 - 811 million people in 2020. More than half of the world's undernourished people are found in Asia.

** Conflict
- In 2020, the World Food Programme was awarded the Nobel Peace Prize for acting as a driving force in efforts to prevent the use of hunger as a weapon of war. War and conflict can cause food insecurity and hunger while food insecurity and hunger can cause latent conflicts to flare up and trigger the use of violence.
- Conflict is the single greatest challenge to the goal of zero hunger as almost 60% of the world's 811 million hungry people live in areas affected by armed violence.

** Climate change
- Agriculture contributes about a quarter of total greenhouse gas emissions globally. It comes mainly from changes in land use, like deforestation and the loss of carbon from soils. There's also methane produced from the gas of ruminating animals like cows. Since climate change causes disturbance to the stable conditions that agriculture relies on, the risk of conflict and migration is increased as people's livelihoods are threatened.
- Sea level rise in low-lying coastal areas is one example of the threat climate change poses to people's livelihoods. Bangladesh and Vietnam are hotspots for such impacts, which result in an increase in salinity levels in agricultural lands.
- Floods and water-logging caused by cyclones and typhoons as well as prolonged drought periods also affect people's livelihoods and food security.
- By 2050, the World Bank estimates that salinity issues in Bangladesh will most likely lead to significant shortages of drinking water and irrigation, and increased soil salinity in both coastal and inland areas, which could result in a decline in rice yield by 15.6%.
- Vietnam is also prone to strong storms, rising temperatures and seasonal variability in rainfall.

** Singapore context
- Imports 90% of its food currently
- Less than 1% of land in Singapore is allocated for farming
- Has 220 farms that currently produce 10% of Singapore's food supply
- 16kg of leafy vegetables consumed per person in 2019
- Imported vegetables in Singapore are 10% - 20% cheaper than their local counterparts due to the lack of economies of scale in Singapore
- Has 77 vegetable farms, with 2 rooftop farms and 25 indoor farms
- Imported more than 125,000 tonnes of seafood in 2019
- Local farms currently produce 10% of the fish supply
- Wants to increase domestic fish production to 15%
- Has 109 sea-based fish farms across the straits of Johor and in the waters off southern Singapore
- Has 12 land-based fish farms
- Consumes about 2 billion eggs per year
- 26% of the eggs come from local farms and efforts are underway to increase domestic egg production
- Has 3 local egg farms
- Imports almost 100% of its fruits
- Currently diversifying sources of import supply can buffer against disruptions in one important region
- Currently boosting its local production and the goal is to produce 30% of nutritional needs locally by 2030, called 30 by 30. This is triple the current domestic production of food
- Leading the development of lab-grown artificial meat
- The first country in the world to approve the sale of lab-grown meat to consumers in December 2020

*** Where vegetables come from
- 41% from Malaysia
- 27% from China
- 7% from India
- 5% from Australia
- 4% locally produced
- 16% from various other countries

*** Where fishes come from
- 21% from Indonesia
- 19% from Vietnam
- 9% from Norway
- 7% from Thailand
- 5% locally produced
- 24% from various other countries

*** Where eggs come from
- 72% from Malaysia
- 26% locally produced
- 1% from Ukraine
- 1% from Thailand
- < 1% from various other countries

*** Where fruits come from
- 39% from Malaysia
- 11% from China
- 8% from South Africa
- 7% from the Philippines
- 7% from Australia
- 28% from various other countries

*** Sustenir agriculture (indoor farm)
- Founded in 2013
- Entered the Singapore market in 2015 with kale
- Don't use pesticides
- They grow kale, rocket, lettuce and ice plants by germinating them in specially designed foam cubes
- Invests heavily in automation for their processes

** The agri-food industry
- World's largest economic sector which employs half of the global workforce, many of which are subsistence farmers and fishermen.
- Responsible for 25% - 30% of global greenhouse emissions uses 68% of our freshwater and drives degradation of marine and terrestrial ecosystems.
- Creates economic profit and the expense of the natural environment.
- Generates social injustices between countries and among actors in the chain from production to consumption and waste.
- The global population is predicted to hit 10 billion in the 2050s, which means that in less than 30 years, the agri-food industry needs to support about 2 billion more people compared to today.
- This is in addition to fixing the problem of over 2 billion people worldwide who already go hungry today.
- Economic growth tends to lead to an increase in food consumption per capita.
- As people get richer, they consume more food.
- 50% more food is produced today compared to 1960.
- As such, the individual consumption and demand for food is likely to increase as incomes increase, alongside the increase in population.

** Meat
- Higher quality foods like meat are also what people go for when they can afford to.
- Hence, the richer we are, the more meat we consume.
- Meat consumption worldwide has been on a steady rise for decades, driven by increasing individual incomes and population growth.
- Too much consumption of red and processed meat is linked to health problems like cancer.
- Meat is a major contributor to greenhouse gas emissions and environmental degradation.
- Meat and dairy also generally have a larger impact on global warming compared to plants due to deforestation and the loss of carbon from the soil. The contribution from the storage and transport of meat is much smaller.
- One-third of the world's fish stocks are in decline due to overfishing.
- Countries rely on aquaculture to meet growing long-term demand.
- The global demand for meat is projected to grow by 78% in 2050.
- The global market for plant-based meat is expected to be worth over SGD 16 billion by 2025.

** Environmental impacts of agriculture
- Single largest cause of biodiversity loss
- Consumptive use of freshwater
- Loading of nutrients
- Pollution due to pesticides
- Soil erosion and degradation
- Water pollution
- Depletion of freshwater resources

** Strategies for sustainably producing more food
- Desirable to increase production with minimal expansion of agricultural land
- Avoiding degenerative practices on current agricultural land
- Having more sustainable agricultural practices
- Shifting diets towards more plant-based food
- Developing food technology
- Reducing food waste

** Food waste
- In 2020, a third of produced food was wasted.
- This means we can make a lot more food available without increasing production by reducing waste.
- 70% of produce is wasted before getting it to the end consumer.
- Researchers at NUS used the larvae of black soldier flies to convert food waste into nutritious compost, which can then be used to grow local food or animal feed.
- When food waste is converted to compost soil, which is then used to grow new food for consumption, it can be considered a closed food loop within Singapore.

** Global land use
- 27% of global land area is used for livestock
- 26% of global land area is forests
- 19% of global land area is barren
- 10% of global land area is glaciers
- 8% of global land area is shrubs
- 7% of global land area is used for crops
- 1% of global land area is freshwater
- 1% of global land area is built-up areas


* Water

** Major concerns
- 17 countries, which are home to one-quarter of the world's population, face high levels of baseline water stress. For example, India's water challenges extend beyond surface water stress. The country has more than 3 times the population of these other 16 extremely highly water-stressed countries combined. In addition to rivers, lakes and streams, its groundwater resources are severely overdrawn, largely to provide water for irrigation.
- 44 countries face a high level of water stress. Such water stress causes severe threats to human lives, livelihoods and business sustainability.
- Population growth, socio-economic development and urbanisation will increase water demand.
- Climate change can make precipitation and demand more unpredictable.
- Some families reported that available water was unaffordable or inaccessible due to physical or social constraints. For example, those living in semi-arid environments experience persistent water shortages. In Brazil, many households experience problems with water that limited handwashing ability despite the country having abundant water resources.
- For some, handwashing was forgone due to unexpected shutoffs or contamination. Some households also prioritise consumption over hygiene when the water supply is limited.
- Two-thirds of the global population had no safe toilets in 2015.
- A third of the global population had no safe water supply in 2015.
- Water sources are becoming more polluted.
- Funding for water and sanitation services is inadequate.
- Adults are too sick to work and children are too sick to study.
- Governance and delivery systems are weak.
- Agriculture and industry are getting thirstier and climate change is taking a heavy toll.
- 2.2 billion people lack safely managed drinking water in 2017, which is one-third of the global population.
- 4.2 billion people lack safely managed sanitation in 2017, which is two-fifths of the global population.
- More than 670 million people still practice open defecation.
- 2 in 5 healthcare facilities worldwide had no soap and water or alcohol-based hand rub in 2016.
- 3 billion people worldwide lack basic handwashing facilities at home.
- Water scarcity could displace 700 million people by 2030.
- Some countries experience a funding gap of 61% for achieving water and sanitation targets.
- Climate change-related floods, droughts and other water-related disasters account for 70% of all deaths due to natural disasters worldwide.
- Agriculture needs to grow by roughly 70% by 2050. Since agriculture is the largest water user, efficient and sustainable irrigation is necessary to achieve global food security goals.
- There is a shortage of funds, as well as water, to maintain irrigation facilities.
- The World Bank proposes that water must be treated as an economic good, using financial instruments to encourage water savings and generate revenues to address both issues.
- Sophisticated economic instruments such as market-driven pricing, volumetric charges, and treatable water rights are a low priority in many developing countries.
- More than 40% of the residents in cities of the Global South, mainly developing nations, will lack affordable and good quality water daily.
- Lack of access to piped-in water means that families must buy water from private sources or bottled water, which can cost up to 50 times as much as piped utility water.
- When water is expensive or inaccessible, households are forced to sacrifice their health and time to provide free but likely unsafe ground and surface water, or sacrifice food, electricity, education, healthcare, or other household needs to buy water.
- South Africa's Cape Town's water crisis in 2018 got so bad that there were competitions to see who could wash their clothes the least. The city was just 90 days away from having no water at all. They will need significant investment to secure adequate water supplies and safeguard functioning freshwater ecosystems for future generations.
- Water will be an increasing source of international tensions.
- Future wars would be over water.
- The matter of water diversion was a devastating issue of life and death.
- Lack of communication over natural resources can be a bad sign for cooperation.
- While most water conflicts are intro-state, transboundary tensions are likely to intensify.
- Downstream nations fear or resent the effect on their waters due to the action of upstream countries.
- For example, in Mexico, the river that created the Grand Canyon and fed a vast delta has been almost completely dry for 2 decades.
- Water basins in South Asia, the Middle East and East Africa are major hotspots with many violent conflicts.
- The Nile basin has fewer conflicts, which reflects the past negotiations between the basin's ten member states to replace colonial-era water agreements.
- India and Bangladesh are particularly concerned about China's thirsty north and water diversion plans.
- In the Mekong Basin, a few Southeast Asian countries are anxious too.

** Water pollution
- An "invisible crisis" that involves water inequality and gender inequality, that will worsen as the planet warms, causing more damage to health, ecosystems and economics than is commonly understood.
- Contaminated water kills more people as compared to disasters and conflicts.
- Globally, deaths from diarrhoea caused by unclean drinking water are estimated at half a million each year, and most of them are young children.
- More than 300,000 children die every year from diarrhoeal diseases caused by unsafe water and poor sanitation in Africa.
- Africa is also at a high risk of desertification, which will reduce the availability of fresh water and increase the risk of water inequality in the future.
- More than 25% of the population in Africa must walk 30 minutes or more to collect water, a burden that falls on women and girls.
- This trend of women being responsible for water collection spans many developing nations and takes time away from income generation.
- Water pollution also disproportionately affects the poor and socially discriminated communities.
- 80% of the world's wastewater is released into the environment without treatment due to poor water infrastructure.
- Water shortage concerns have overshadowed water pollution.
- The use of nitrogen as a fertiliser has increased by more than 700% since 1960, with nearly all the growth occurring in Asia.
- Long-term exposure to non-point source pollution for agriculture during childhood results in lower earnings when the children enter adulthood.
- Such economic inequality and water pollution will create a vicious cycle and result in intergenerational poverty.
- Nanoplastics, with an upper size limit of one micrometre, are tiny enough to remain and disperse through a water column where organisms, including humans, can easily consume them, instead of them sinking of floating like large microplastics do.

** Water security framework

*** Good governance
Adequate legal regimes, institutions, infrastructure and capacity are in place.

*** Transboundary cooperation
Sovereign states discuss and coordinate their actions to meet the varied and sometimes competing interests for mutual benefit.

*** Peace and political stability
The negative effects of conflicts are avoided, including reduced water quality or quantity, compromised water infrastructure, human resources, related governance, and social or political systems.

*** Financing
Innovative sources of financing complement funding by the public sector, including investments from the private sector and micro-financing schemes.

*** Drinking water and human well-being
Populations have access to safe sufficient and affordable water to meet basic needs for drinking sanitation and hygiene to safeguard health and well-being, and to fulfill basic human rights.

*** Economic activities and development
Adequate water supplies are available for food and energy production, industry, transport and tourism.

*** Water-related hazards and climate change
Populations are resilient to water-related hazards including floods, droughts and pollution.

*** Ecosystems
Ecosystems are preserved and can deliver their services, on which both nature and people rely, including the provision of fresh water.

** Singapore's water story
- More than 5 million consumers use 800 Olympic-sized swimming pools of water every single day, which is about 340 million gallons a day, with homes consuming about 45% and industries taking up the rest.
- By 2060, Singapore's water demand could almost double, with the industrial sector using about 70%.
- By 2060, NEWater and desalination will meet up to 85% of Singapore's future water demand.
- Singapore was ranked 170th of 193 countries for water resources in the 2006 United Nations World Water Development Report.
- The poor availability was not because we lack rainfall, but because there is a limited land area to catch and store the rain.
- Even though Singapore's water supply comes mostly from more expensive water sources such as NEWater and desalinated water, these sources are weather-independent sources that will strengthen the resilience of Singapore's water supply against the effects of dry weather caused by climate change.
- Between 2003 and 2016, households cut their water use per person, per day from 165 litres to 148 litres. The long-term goal is 140 litres by 2030.
- A study surveyed 400 local households, from 2018 to 2019, found that 66% of the households used running water to wash their toilets instead of a bucket or a pail. 41.5% of households used the same method for pet care, and 50% of households washed food under running taps and washed their laundry using a washing machine when it was not fully loaded. 94% of households washed their dishes under running taps instead of using basins.
- Under the mandatory water efficiency labelling scheme, suppliers must list the water efficiency of their water fitting and device on display so that consumers can make more informed choices.
- As Singapore becomes more urbanised and downpours become more frequent and intense, the risk of floods will increase.

*** First National Tap - Rainwater
- Singapore has 17 reservoirs, including the largest reservoir, the Marina Catchment that has an area of 10,000 hectares.
- Unprotected catchments in western and northern Singapore where limited residential, and light uses were allowed.
- Urban catchment areas like stormwater collection systems were designed such that only the cleaner parts of the stormwater are extracted and pumped into the reservoir. The immediate runoff that is the most polluted bypasses the collection facilities.
- The Marina Barrage was built across the Marina Channel, where the five rivers running through the city centre, including the Singapore River, meet before emptying into the sea.
- The 16th and 17th reservoirs were formed, creating a dam at the mouth of the Punggol and Serangoon rivers in northeastern Singapore.
- Catchment areas currently make up two-thirds of Singapore and will occupy 90% of Singapore's land area by 2060.
- Singapore has more than 8,000 kilometres of waterways, much of it being in urban areas.
- Singapore is one of the few countries in the world that harvest stormwater on a large scale for its water supply.
- Rainwater is channelled through an island-wide network of drains, canals and rivers to the reservoirs for storage.
- Rainwater is then treated at water treatment plants to become potable water for homes and industries.

*** Second National Tap - Imported water from Johor, Malaysia
- In 1965, water supply sources in Singapore comprised solely of reservoirs in the central catchment inherited from the British and water supply was not sufficient to meet demand.
- Singapore had to depend on Johor for its water supply and two water agreements were signed in the early 1960s.
- The 1961 water agreement between the Johor state government and Singapore expired on 31st August 2011.
- Singapore continues to import water from Johor under the 1962 water agreement, which allows us to draw water from the Johor River until 2061.
- The Johor River fell to a historic low of 20% of its capacity due to climate change in 2016.
- Singapore has been importing water from Malaysia for many years.
- Singapore has been able to reduce its reliance on imported water thanks to the next tap.
- There have been conflicts between Malaysia and Singapore over how much Singapore should pay for water from Malaysia, and hence the government is looking to minimise the amount of water imported from Johor by 2061.

*** Third National Tap - Recycled water
- Singapore is one of the few countries in the world that has two separate collection systems, one for rainwater and one for used water.
- Used water is then sent to treatment plants or water reclamation plants, where it goes through rigorous processing, such as microfiltration, reverse osmosis and ultraviolet disinfection to make the water safe for consumption. This is called NEWater.
- NEWater is a high-grade reclaimed water produced from treated used water that is further purified using advanced membrane technologies and ultraviolet disinfection, making it ultra clean and safe to drink.
- Presently, Singapore's 5 NEWater plants can meet up to 50% of the nation's current water needs.
- However, the use of advanced technologies makes producing NEWater a lot more expensive.
- Singapore collects used water through the Deep Tunnel Sewerage System (DTSS) and underground sewers for treatment at a water reclamation plant.
- Treated used water can then be sent to NEWater facilities for further treatment to obtain ultra-clean, high-grade reclaimed water.
- Sometimes, such water is treated and discharged to the sea.
- NEWater is mainly used for industries, but it is also used to top up our reservoirs to further enhance our water security.

*** Fourth National Tap - Desalinated water
- Desalination turns seawater into potable water.
- The most energy-intensive of the 4 national taps.
- Singapore currently uses reverse osmosis for its desalination, producing drinking water by pushing seawater through membranes to remove dissolved salts and minerals.
- The cost of desalinated water is more than twice that of NEWater.
- Singapore has two desalination plants that can produce up to 25% of its water needs.
- Singapore will continue investing in research and technology to find better and less expensive ways of desalting seawater.

*** Deep Tunnel Sewerage System (DTSS)
- By 2050, whenever you flush the toilet, take a shower, or wash the dishes, the used water will flow into the underground network of tunnel sewers and be channelled by gravity to one of the 3 coastal water reclamation plants for treatment.
- When completed, the DTSS will shrink the land area occupied by used water infrastructure by 50% and collect every drop of used water for treatment and purification.


* Energy and greenhouse gas emissions
- Present global carbon dioxide emissions are about 180 times higher than in 1850.
- In 2000, 23 to 24 million tons of CO_{2} were emitted. In 2020, this amount has reached 35 million tons, which is an increase of almost 50% within 20 years.
- All these carbon dioxide emissions are going into the Earth's atmosphere and increasing the atmospheric concentration of CO_{2}. The unit used to measure the concentration of CO_{2} is parts per million or ppm, which is the number of molecules of CO_{2} present in every 1 million molecules of air.
- The atmospheric concentration of CO_{2} in 2019 was higher than any other time in the last 2 million years.
- There are 6 major greenhouse gases, CO_{2}, methane nitrous oxides and 3 fluorinated gases.
- There are three main factors to analysing the impact of greenhouse gases, which are:
  - Concentration, which refers to the amount of the gas present in the atmosphere.
  - Lifetime, which refers to how long the gas stays in the atmosphere. Most greenhouses gases remain in the atmosphere for thousands of years. CO_{2} stays in the atmosphere for much longer as compared to other gases.
  - Global warming potential, which refers to how capable the gas is in trapping heat. The global warming potential of methane is much higher than CO_{2}.

- When all factors are taken into account, CO_{2} is determined to be the main driver of climate change.
- 76% of global greenhouse gas emissions are caused by carbon dioxide.
- Almost 44% of global CO_{2} emissions come from electricity and heat generation. The next major contributor is the transport sector.
- Fossil fuels, such as coal, oil and gas are predominantly used to generate electricity and heat and power transportation vehicles, which contributes massively to CO_{2} emissions.
- Most fossil fuels have carbon as their main component. For example, coal is almost fully carbon and we burn it to generate energy. During the combustion process, the carbon in the coal combines with oxygen in the air to form carbon dioxide, which releases energy.
- The Intergovernmental Panel on Climate Chage (IPCC) suggests limiting the global temperature increase to 1.5 degrees centigrade above pre-industrial levels.
- The present temperature increase is about 1.1 degrees centigrade above pre-industrial levels.
- Adverse consequences of climate change like extreme weather events and sea-level rise are already being experienced.
- Some of the major impacts of climate change can be avoided by limiting the temperature increase to 1.5 degrees centigrade.
- Going above the 1.5 degree limit can result in long-lasting and irreversible damage, such as losing some ecosystems like forests and marine ecosystems for good.
- Forests act as carbon sinks, which means they act like a sponge and soak up carbon emissions.
- Since the 1960, forests have soaked up about 25% of total CO_{2} emissions contributed by fossil fuel burning.
- The Amazon rainforest is the world's largest tropical rainforest, but deforestation and climate change are affecting the Amazon rainforest's ability to soak up carbon.
- Significant parts of the Amazon rainforest have started emitting more CO_{2} than they absorbed.
- Around 700 million people still don't have access to electricity.
- 10% of the world's population (roughly 734 million people) live in extreme poverty.
- About 690 million people globally are undernourished and about 14 million children under the age of 5 suffer from severe acute malnutrition.
- We need to grow in a way such that everyone in the world has access to clean, affordable and sustainable energy so that no one lives in extreme poverty and no child suffers from malnutrition.

** Effects of global warming
- Global warming leads to climate change. When there is an increase in the conccentration of CO_{2} in the atmosphere, the global temperature increases. This leads to adverse effects such as:
  - Increased frequency and intensity of hot extremes
  - Marine heatwaves
  - Heavy precipitation
  - Reductions in Arctic sea ice and snow cover
  - Extreme weather
  - Negatively impacts food production
  - Negatively impacts water supply
  - Negatively impacts human health

- Climate-fuelled disasters killed 475,000 people between 2000 and 2019 and which resulted in more than $2.50 trillion lost.
- From 1980 to 1999, more than 4,000 natural disasters were reported resulting in 1.19 million deaths and losses of $1.5 trillion. From 2000 to 2019, these numbers have risen to 7,400 natural disasters resulting in 1.23 million deaths and losses of about $3 trillion.
- The frequency and intensity of extreme weather events and natural disasters have increased tremendously.
- Climate change will impact everyone. However, richer countries are more able to deal with the impact of climate change compared to poorer countries as richer countries have more resources, a skilled workforce, a better system in place, a well-functioning government and access to advanced technologies to deal with the impacts of climate change.


* Sustainable development goals (SDG)
- SDG 1: End extreme poverty.
- SDG 7: Ensure access to affordable, sustainable and modern energy for all, as well as end energy poverty.
- SDG 8: Decent work and economic growth for all, which means raising incomes per person in poor countries and allow them to narrow the gap with high-income countries.
- SDG 11: Make cities and human setllements sustainable through decarbonisation and sustainability.
- SDG 13: Take urgent action to combat climate change.


* Energy
- In 2010, 1.2 billion people did not have access to electricity, and this number decreased to 771 million in 2020.
- Electricity, which was invented back in the 19th century, still has not reached millions of people.
- The Organisation for Economic Co-operation and Development (OECD) countries use much more energy per person than the global average, while people in Africa and Asia still live in the dark.


* Possible actions to tackle climate change
- Advanced technologies, clean energy, and behaviour change is the first step towards decarbonisation of the economy.

** Mitigation
Mitigation is essential and is our only shot to deal with climate change. The two methods to mitigate climate change are energy efficiency and low carbon transition.

*** Low carbon transition
- Low carbon transition means transitioning to an economy where as little carbon is used as possible.
- There are two ways to achieve a low carbon transition
  1. Decarbonising the energy system, which is to produce and use energy with lower emissions of carbon dioxide.
  2. Making shifts in sectors of the economy that contribute a lot to greenhouse gas emissions, such as transport. Instead of using diesel or petrol powered vehicles, electric vehicles or vehicles powered by other clean fuels, such as hydrogen fuel, should be used instead.

- A low carbon transition cannot happen overnight, as most of the world's energy is still produced by fossil fuels.
- These plants also generate plenty of employment, so there is no way to shut them down overnight. It will take some time and must happen gradually.
- Cutting edge technologies that reduce the carbon footprint of these fossil fuel power generation systems can help a lot. For example, carbon capture and storage can capture CO_{2} on-site and store it in an underground storage site for a longer term.
- There are still some technical and financial challenges to using these technology.
- Innovation will play a crucial role in ensuring our success in emission mitigation.

*** Clean sources of energy
1. Solar thermal energy: Using direct sunlight to heat water or air and using this fluid for residential or industrial purposes. Some examples include solar-powered water heaters and solar-powered swimming pools.
2. Concentrated solar thermal energy: Concentrating sunlight at a point to heat fluids, and ultimately high pressure vapour, which are then used to drive turbines to generate electricity.
3. Solar photovoltaics (PV): Generate electricity using photovoltaics panels.
4. Passive solar heating: Use the Sun to naturally heat the buildings.
5. Onshore wind energy: Land-based wind farms.
6. Offshore wind energy: Wind farms in bodies of water, where the wind speed is much higher. Offshore wind farms are more expensive than their onshore counterparts, but the cost has decreased substantially in the recent years and is projected to decrease even further.
7. Hybrid system: A system consisting of a combination of solar photovoltaics and wind turbines. Sunlight is available during the day while wind speed is higher at night, and hence both sources of energy complement each other well.
8. Run-of-river hydropower
9. Storage hydropower systems
10. Pumped storage hydropower systems
11. Wave energy
12. Tidal energy
13. Geothermal energy
14. Energy from biomass
15. Nuclear energy
16. Energy from hydrogen fuel

*** Benefits of renewable energy
- We have the dual challenge of reducing our emissions and ensuring access to sustainable and modern energy for all.
- Renewable energy can address both challenges as it doesn't run out, never emits greenhouse gases, saves money in most cases, and has the potential to generate massive employment.
- The renewable power industry employs 12 million people in 2020. Solar photovoltaics leads the field with about 4 million jobs.
- This employment number will likely increase as we move towards renewable energy.
- These jobs are green jobs and they also ensure much-needed access to electricity in remote and energy-poor communities.
- Renewable power plants can be installed at a much smaller scale and decentralised operation is also possible, which means that the power plants don't have to be connected to a large power grid. This makes it possible to supply electricity to remote locations.
- Prices of renewable energy is relatively immune to market fluctuations.
- The recent surge in natural gas prices raised electricity tariffs in many countries, including Singapore. Many retail electricity companies shut down their operations in Singapore due to not being able to supply electricity at previously-promised prices.
- Using renewable energy might safeguard us from such fluctuations, especially for countries that are heavily dependent on imported fuels for electricity generation, such as Singapore.
- Some renewable energy systems have already reached grid parity, which means generating electricity through solar photovoltaics costs the same as generating electricity from conventional sources.

*** Challenges of renewable energy
- Renewable energy sources are intermittent, which means that they are not available all the time.
- The sun doesn't shine at night and the wind doesn't always blow at the same speed.
- This creates the need to store energy whenever it is available, which increases the cost of these systems.
- Renewable energy needs a lot of land area and some countries do not have much free land to spare, such as Singapore. These countries will need to be more innovative in their approach to using renewable sources of energy, such as using rooftop spaces, water bodies and generating electricity in neighbouring countries and transmitting it to their own countries may be some typical solutions.
- In the beginning, people found wind turbines to be ugly and raised many other objections against renewable energy.
- However, public awareness and acceptability have improved over time.
- Massive investment in research and development is needed to help overcome all the technical and financial challenges of renewable energy.

*** Energy efficiency
- Greater energy output per unit of energy input.
- Use of technologies, systems or methods that require less energy for perform the same task, eliminating energy waste.
- Energy applicances convert energy sources into other useful energy services, such as lighting, cooling or heating.
- During this conversion, some energy is lost, which should be reduced, as reducing this loss would mean that the energy efficiency of the system has improved.
- Energy-efficient household appliances are now available on the market and consumers have the option to buy an energy efficient air-con, refrigerator, light bulbs, and other devices.
- Enormous amounts of energy can be saved in heating, cooling, ventilating, and other applications by using energy-efficient appliances.
- Energy efficiency helps to reduce greenhouse gas emissions as less energy is used to perform a certain task.
- When less energy is used, the demand for energy decreases at a country level, which might be a relief for countries, specifically the ones that are heavily on imported energy, like Singapore. Singapore imports almost all the gas it uses to generate electricity.
- Energy-efficient systems save money in the long term.
- The upfront cost of energy-efficient systems is relatively higher. For example, an energy-efficient refrigerator will cost more than a conventional refrigerator.
- However, over the lifetime of the appliance, money is saved due to the reduction in the electricity used.
- There is a potential to adopt energy efficient systems in almost every sector of the economy, such as buildings, households, transport, or even electricity generation. Some examples include:
  - Zero energy buildings: Buildings that have increased energy efficiency and use renewable energy.
  - Efficient energy generation and distribution.
  - Efficient vehicles.
  - Behaviour change: Use less energy, adopt energy-efficient appliances, cut wastage. For example, using the air-con for 4 hours instead of 5 hours, switching off appliances when they are not in use, taking shorter showers to save water as well as electricity.
  - Long-distance freight transport, maritime and shipping.

- Technology alone is insufficient to solve the problem of climate change. No matter how many advanced technologies we have, if we don't mitigate emissions by changing our behaviour, adopting clean energy and energy-efficient systems, and making a shift in our consumption, there is a lower likelihood of solving the problem of climate change.
- Renewable energy adoption remains low, at 29% of our total electricity generation. The remaining 71% is still being produced by fossil fuels.
- Energy-efficiency improvement is much lower that the required number for the sustainable development scenario.
- Policies that push the adoption of clean energy and energy efficiency a bit faster are needed.

** Adaptation (climate resilience)
- Adaptation keep us safe and buy us some time until we implement mitigation measures to slow down climate change and ultimately eliminate it.
- The objective is to reduce our exposure to climate risks.
- Some examples include:
  - Building new flood defences and barriers against storm surge.
  - Protecting crops from high temperatures and droughts.

** Policies
- Policy instruments may help to accelerate the adoption of clean energy and the overall decarbonisation of teh economy.

