#+TITLE: Rotation of Rigid Bodies Notes
#+AUTHOR: Hankertrix
#+STARTUP: showeverything
#+OPTIONS: toc:2
#+LATEX_HEADER: \usepackage{siunitx, graphicx}
#+LATEX_HEADER: \graphicspath{ {./images/} }

* Definitions

** Tangential quantity
In circular motion, a tangential quantity, like tangential velocity and tangential acceleration, refers to the quantity that is tangent to the circumference of the circle.

** Radial quantity
In circular motion, a radial quantity, like radial velocity and radial acceleration, refers to the quantity that is perpendicular to the tangent of the circumference of the circle. That means that the quantity is either directed towards the centre of the circle, or directed outwards from the centre of the circle.

** Rotational analogue of Newton's Second Law
The sum of torques, or the net torque, about a *fixed axis* is equal to the product of the moment of inertia (\(I\)) about the *same axis* and the angular acceleration (\(\alpha\)) about the *same axis*.
\\

Essentially:
\[\sum \vec{\tau} = I \vec{\alpha}\]

Make sure that all quantities are calculated for the *same fixed axis*.
\\

If an object is rotating with acceleration, as long as the axis the object is rotating about passes through its centre of mass ($CM$), we can still use the relation above, but with a stricter condition that *all quantities* are calculated *about the centre of mass*.
\[\sum \vec{\tau}_{CM} = I_{CM} \vec{\alpha}_{CM}\]

\newpage

* Formulas

** Arc length (\(s\))
\(s\) is the arc length or the tangential length, and it is given by:
\[s = r \theta, \ \theta \text{ in radians}\]

Where $r$ is the radius of the circle that the object is rotating about.

** Angular displacement (\(\theta\))
\[\text{Angular displacement: } \theta = \frac{s}{r}\]

** Period (\(T\))
The period is the time taken for an object to complete one full rotation, or spin a full circle.

** Frequency (\(f\))
\[\text{Frequency: } f = \frac{1}{T} \text{ where } T \text{ is the period}\]

** Angular velocity (\(\omega\))
\begin{align*}
\text{Angular velocity: } \omega &= \frac{d \theta}{dt} \\
&= 2 \pi f \\
&= \frac{2 \pi}{T} \\
&= \frac{v_{tan}}{r}
\end{align*}

** Angular acceleration (\(\alpha\))
\[\text{Angular acceleration: } \alpha = \frac{d \omega}{dt}\]

** Comparing angular and linear quantities
The linear counterpart refers to the quantity in the tangential direction.

\begin{center}
\begin{tabular}{ c|c }
\(\textbf{Angular}\) & \(\textbf{Linear}\) \\
\hline
\(\theta\) & \(s = r\theta\) \\
\(\omega\) & \(v_{tan} = r\omega\) \\
\(\alpha\) & \(a_{tan} = r\alpha\) \\
\end{tabular}
\end{center}

For constant acceleration (both angular and linear), we have the following relations:
\begin{center}
\begin{tabular}{ c|c }
\(\textbf{Angular}\) & \(\textbf{Linear}\) \\
\hline
\(\omega_f = \omega_i + \alpha t\) & \(v_f = v_i + at\) \\
\(\theta - \theta_0 = \omega_i t + \frac{1}{2} \alpha t^2\) & \(x - x_0 = v_i + \frac{1}{2} a t^2\) \\
\(\omega_f^2 = \omega_i^2 + 2 \alpha(\theta - \theta_0)\) & \(v_f^2 = v_i^2 + 2a(x - x_0)\)
\end{tabular}
\end{center}

** Total linear acceleration
Total linear acceleration is given by:
\begin{align*}
\vec{a} &= \vec{a}_{tan} + \vec{a}_{radial} \\
&= \vec{a}_{tan} - \frac{(\vec{v}_{tan})^2}{R} \hat{r} \\
&= \vec{a}_{tan} - R \omega^2 \hat{r}
\end{align*}

** Torque (\(\vec{\tau}\)) (\(\unit{kg.m^2.s^{-2}}\))
\[\vec{\tau} = \vec{r} \times \vec{F}\]

The magnitude of the torque is given by:
\[\tau = rF \sin \theta\]

** Moment of inertia (MOI)

*** Discrete point masses
For a system of discrete point masses, the moment of inertia is:
\begin{align*}
I &= m_1 r_1^2 + m_2 r_2^2 + \cdots \\
&= \sum_{i} m_i r_i^2
\end{align*}

Where $m$ is the masses of the particles that make up the body, and $r$ is the *perpendicular distances* of the particles from the *rotation axis*.

*** Continuous mass distribution
For a system with continuous mass distribution, the moment of inertia is:
\begin{align*}
I &= \lim_{\Delta m_i \rightarrow 0} \sum_{i} \Delta m_i r_i^2 \\
&= \int r^2 \, dm
\end{align*}

** Parallel axis theorem
\[l_P = I_{CM} + Md^2\]

Where $I_P$ refers to the moment of inertia about any other axis *parallel* to the axis through the object's centre of mass.

** Perpendicular axis theorem
The perpendicular axis theorem is *only applicable to flat (plane) objects*. It states that the sum of the moments of inertia of a plane object about *any two perpendicular* axes in the plane of the object, is *equal* to the moment of inertia about an axis through their point of intersection perpendicular to the plane of the object.
\\

For example, if the flat object lies on the $x - y$ plane, then:
\[I_z = I_x + I_y\]

** Rotational kinetic energy
\[K = \frac{1}{2} I \omega^2\]

Where $I$ is the moment of inertia of the body about a given rotation axis, and $\omega$ is the angular speed of the body.

\newpage

** Work-energy theorem for rotational motion
\begin{align*}
W &= \int \tau \, d \theta \\
&= \frac{1}{2} I \omega_f^2 - \frac{1}{2} I \omega_i^2
\end{align*}

Where \(\omega_f\) is the final angular velocity and $\omega_i$ is the initial angular velocity. Essentially, the work down by the force is the change in kinetic energy of a rotating object.
\\

The instantaneous power of the torque is:
\begin{align*}
P &= \frac{dW}{dt} \\
&= \tau \frac{d \theta}{dt} \\
&= \tau \omega
\end{align*}

\newpage


* Moment of inertia of common shapes
\[\includegraphics[width = \textwidth]{moments-of-inertia-1}\]

\[\includegraphics[width = \textwidth]{moments-of-inertia-2}\]

\newpage


* Rolling without slipping
When an object rolls without slipping, the length of the arc covered by the rotation in some duration is equal to the translational distance covered by the centre of mass, i.e.:
- Translational distance\(= v_{CM} \Delta t\)
- Rotational arc length\(= R \omega \Delta t\)

Where $\Delta t$ is the time interval during which the object is rolling. Thus:
\[v_{CM} = R \omega \text{ for rolling without slipping}\]

Note that \(v_{tan} = R \omega\) is always true, where \(v_{tan}\) is the tangential speed of a point on the circumference. Here, \(v_{CM}\) is the translational speed of the centre of mass and hence, \(v_{CM} = R \omega\) is only true for rolling without slipping.

** Kinetic energy

The total kinetic energy for an object that is rolling without slipping is the sum of the kinetic energy of pure rotation and the kinetic energy of pure translation, which is:
\[K_{total} = \frac{1}{2} I_{CM} \omega^2 + \frac{1}{2} mv_{CM}^2\]


* Differential quantities

** Cartesian coordinates

\[\includegraphics[scale = 0.4]{cartesian-coordinates}\]

Only the line and the volume elements below are generally applicable, as surface area elements depend on the surface specified in the question.

*** Line element
\[d \vec{l} = \hat{x} \, dx + \hat{y} \, dy + \hat{z} \, dz\]

*** Surface area elements
- \(d \vec{s}_x = \hat{x} \, dy \, dz\)
- \(d \vec{s}_y = \hat{y} \, dx \, dz\)
- \(d \vec{s}_z = \hat{z} \, dx \, dy\)

*** Volume element
\[dV = dx \, dy \, dz\]

** Cylindrical coordinates

\[\includegraphics[scale = 0.4]{cylindrical-coordinates}\]

The radial distance on the $x - y$ plane is given by the quantity $s$ while most texts use either $r$ or $\rho$. We use $r$ for a different radial distance in spherical coordinates and $\rho$ to mean density.
\\

\(\phi\) goes from \(0\) to $2\pi$.

\[x = s \cos \phi\]
\[y = s \sin \phi\]
\[z = z\]

*** Line element
\[d \vec{l} = \hat{s} \, ds + \hat{\phi} (sd \phi) + \hat{z} \, dz\]

*** Volume element
\[dV = s \, ds \, d \phi \, dz\]

** Spherical coordinates

\[\includegraphics[width = \textwidth]{spherical-coordinates}\]

\(\phi\) goes from $0$ to $2\pi$ while $\theta$ goes from $0$ to $\pi$.

\[x = r \sin \theta \cos \phi\]
\[y = r \sin \theta \sin \phi\]
\[z = r \cos \theta\]

*** Line element
\[d \vec{l} = \hat{r} \, dr + \hat{\phi} (r \sin \theta \, d \phi) + \hat{\theta} (r d \theta)\]

*** Volume element
\[dV = r^2 \sin \theta \, dr \, d \theta \, d \phi\]
