// The firmware for the Arduino cone layer
//
// Using the template generated by:
// https://github.com/Rahix/avr-hal-template

#![no_std]
#![no_main]
#![feature(abi_avr_interrupt)]

// Modules
mod constants;
mod movement;
mod serial;
mod stepper_driver;
mod timer;
mod utils;

// Use declarations
use heapless::Vec;
use movement::{Command, MovementHandler};
use panic_halt as _;
use serial::new_serial_handler;
use stepper_driver::{new_stepper_driver, StepperDriver};

/// Function to execute
#[arduino_hal::entry]
fn main() -> ! {
    //

    // Setup code

    // Get the peripherals and the pins on the arduino
    let peripherals = arduino_hal::Peripherals::take().unwrap();
    let pins = arduino_hal::pins!(peripherals);

    // Initialise the console serial handler
    let mut console_serial_handler =
        new_serial_handler!(USART0, peripherals, pins);

    // Initialise the bluetooth serial handler
    let mut bluetooth_serial_handler =
        new_serial_handler!(USART2, peripherals, pins);

    // Initialise the timer
    timer::init_and_start(peripherals.TC0);

    // Initialise a new stepper driver
    let mut stepper_driver_e0 = new_stepper_driver!(E0, pins);
    let mut stepper_driver_e1 = new_stepper_driver!(E1, pins);
    let mut stepper_driver_x = new_stepper_driver!(X, pins);
    let mut stepper_driver_y = new_stepper_driver!(Y, pins);
    let mut stepper_driver_z = new_stepper_driver!(Z, pins);

    // Test for the time taken for the stepper drivers to reach maximum speed
    let acceleration = 50.0;
    let max_speed = 500.0;
    let steps_to_move = 1_000_000;
    stepper_driver_e0.set_acceleration(acceleration);
    stepper_driver_e1.set_acceleration(acceleration);
    stepper_driver_x.set_acceleration(acceleration);
    stepper_driver_y.set_acceleration(acceleration);
    stepper_driver_z.set_acceleration(acceleration);
    stepper_driver_e0.set_maximum_speed(max_speed);
    stepper_driver_e1.set_maximum_speed(max_speed);
    stepper_driver_x.set_maximum_speed(max_speed);
    stepper_driver_y.set_maximum_speed(max_speed);
    stepper_driver_z.set_maximum_speed(max_speed);
    stepper_driver_e0.move_by_steps(steps_to_move);
    stepper_driver_e1.move_by_steps(steps_to_move);
    stepper_driver_x.move_by_steps(steps_to_move);
    stepper_driver_y.move_by_steps(steps_to_move);
    stepper_driver_z.move_by_steps(steps_to_move);

    /* // Initialise the vector holding the left side motors
    let mut left_side_motors: Vec<StepperDriver, 2> = heapless::Vec::new();

    // Add the stepper drivers on the left side to the vector
    left_side_motors.push(stepper_driver_e0).unwrap_or_default();
    left_side_motors.push(stepper_driver_e1).unwrap_or_default();

    // Initialise the vector holding the right side motors
    let mut right_side_motors: Vec<StepperDriver, 2> = heapless::Vec::new();

    // Add the stepper drivers on the right side to the vector
    right_side_motors.push(stepper_driver_x).unwrap_or_default();
    right_side_motors.push(stepper_driver_y).unwrap_or_default();

    // Initialise the movement handler
    let mut movement_handler = MovementHandler::new(
        left_side_motors,
        right_side_motors,
        stepper_driver_z,
        true,
        false,
    ); */

    // Print that the Arduino is initialised
    console_serial_handler.write_string("Arduino initialised!\n");

    // Initialise the start time
    let start_time = timer::micros();

    // Initialise the boolean to store whether the time has been printed
    let mut printed = false;

    // Safety: We are not in a critical section,
    // so enabling interrupts is fine.
    // Enable interrupts globally.
    unsafe { avr_device::interrupt::enable() }

    // The main loop to run
    loop {
        //

        // Test for the time taken for the stepper drivers
        // to reach maximum speed
        stepper_driver_e0.run();
        stepper_driver_e1.run();
        stepper_driver_x.run();
        stepper_driver_y.run();
        stepper_driver_z.run();

        // Check if all of the stepper drivers have reached maximum speed
        if stepper_driver_e0.speed() == max_speed
            && stepper_driver_e1.speed() == max_speed
            && stepper_driver_x.speed() == max_speed
            && stepper_driver_y.speed() == max_speed
            && stepper_driver_z.speed() == max_speed
            && !printed
        {
            // Get the time taken to reach maximum speed
            let time_taken_to_reach_maximum_speed =
                timer::micros() - start_time;

            // Print the time taken to reach maximum speed
            console_serial_handler
                .write_string("Time taken to reach max speed: ");
            console_serial_handler
                .write_number(time_taken_to_reach_maximum_speed as i32);
            console_serial_handler.write_string(" microseconds\n");

            // Set the boolean to true to signify that the time has been printed
            printed = true;
        }

        /* // Parse the input from the serial connection
        let input = bluetooth_serial_handler.handle_input();

        // Match the input
        match input {
            Some(Command::HandleJoystick(arguments)) => {
                movement_handler.handle_joystick(arguments)
            }
            Some(Command::LayConesInAStraightLine(arguments)) => {
                movement_handler.lay_cones_in_a_straight_line(arguments)
            }
            Some(Command::DropCone(arguments)) => {
                movement_handler.drop_cone(arguments)
            }
            None => {},
        }

        // Call the function to run all of the motors
        movement_handler.run_all_motors(); */
    }
}
